root = r'C:\TPM-Workspace\06-Code\IntuitiveFusionPOC\apps\web\src'


def edit(rel, pairs):
    p = f'{root}\\{rel}'
    s = open(p, encoding='utf8').read()
    for a, b in pairs:
        assert a in s, (rel, a[:80])
        s = s.replace(a, b, 1)
    open(p, 'w', encoding='utf8').write(s)


edit('app/supplier/register/register-form.tsx', [
    ("  const [done, setDone] = useState(false);\n", "  const [done, setDone] = useState<null | { held: boolean }>(null);\n  const [questions, setQuestions] = useState<\n    Array<{ id: string; label: string; type: 'YESNO' | 'TEXT'; mandatory: boolean }>\n  >([]);\n  const [answers, setAnswers] = useState<Record<string, string>>({});\n  const [privacy, setPrivacy] = useState({ shareProfile: true, productUpdates: false });\n  // the organisation's own onboarding questions, if it has set any (FR-0215)\n  useEffect(() => {\n    void api<typeof questions>(`/supplier/onboarding-questions${token ? `?token=${encodeURIComponent(token)}` : ''}`)\n      .then(setQuestions)\n      .catch(() => setQuestions([]));\n  }, [token]);\n"),
    ("      await api('/supplier/register', {\n        method: 'POST',\n        body: { ...(token ? { token } : {}), name, email, company, abn, password },\n      });\n      setDone(true);", "      const r = await api<{ sanctionsStatus?: string }>('/supplier/register', {\n        method: 'POST',\n        body: {\n          ...(token ? { token } : {}),\n          name,\n          email,\n          company,\n          abn,\n          password,\n          answers: Object.fromEntries(Object.entries(answers).filter(([, v]) => v !== '')),\n          privacy,\n        },\n      });\n      setDone({ held: r.sanctionsStatus === 'MATCH' });"),
    ("        <p className=\"font-bold\">You are registered.</p>\n        <p className=\"mt-1 text-sm\">\n          <Link href=\"/login\">Sign in</Link> with your email and the password you just chose. You will land in\n          the supplier portal.\n        </p>", "        <p className=\"font-bold\">You are registered.</p>\n        {done.held && (\n          <p className=\"mt-1 text-sm\" data-testid=\"held-notice\">\n            Your account is on hold while a screening result is reviewed by the buyer. You will be told when it is\n            active.\n          </p>\n        )}\n        <p className=\"mt-1 text-sm\">\n          <Link href=\"/login\">Sign in</Link> with your email and the password you just chose. You will land in\n          the supplier portal.\n        </p>"),
    ("      <Button type=\"submit\" loading={busy} disabled={!ready}>\n        Create account\n      </Button>", "      {questions.map((q) => (\n        <Field key={q.id} label={q.label} required={q.mandatory} error={fields[`answers.${q.id}`] ?? ''}>\n          {q.type === 'YESNO' ? (\n            <Select value={answers[q.id] ?? ''} onChange={(e) => setAnswers({ ...answers, [q.id]: e.target.value })}>\n              <option value=\"\">Choose…</option>\n              <option value=\"YES\">Yes</option>\n              <option value=\"NO\">No</option>\n            </Select>\n          ) : (\n            <Input value={answers[q.id] ?? ''} onChange={(e) => setAnswers({ ...answers, [q.id]: e.target.value })} maxLength={2000} />\n          )}\n        </Field>\n      ))}\n      <fieldset className=\"rounded-md border border-border p-3\">\n        <legend className=\"px-1 text-sm font-semibold\">Your privacy choices</legend>\n        <label className=\"flex min-h-[44px] items-center gap-3 text-sm\">\n          <input type=\"checkbox\" className=\"size-5 accent-[var(--if-color-accent)]\" checked={privacy.shareProfile} onChange={(e) => setPrivacy({ ...privacy, shareProfile: e.target.checked })} />\n          Let buyers at this organisation see my company profile\n        </label>\n        <label className=\"flex min-h-[44px] items-center gap-3 text-sm\">\n          <input type=\"checkbox\" className=\"size-5 accent-[var(--if-color-accent)]\" checked={privacy.productUpdates} onChange={(e) => setPrivacy({ ...privacy, productUpdates: e.target.checked })} />\n          Send me product updates by email\n        </label>\n        <p className=\"mt-1 text-xs text-text-muted\">You can change these at any time on your company profile.</p>\n      </fieldset>\n      <Button type=\"submit\" loading={busy} disabled={!ready}>\n        Create account\n      </Button>"),
    ("import { Button, Field, Input } from '@if/ui';", "import { Button, Field, Input, Select } from '@if/ui';"),
])
edit('app/supplier/register/page.tsx', [
    ("            Your company starts with sanctions screening marked as pending. Already registered?{' '}", "            Your company is screened against watchlists when you register. Already registered?{' '}"),
])
print('ok')
