"""M14: generate the roadmap register (packages/shared/src/roadmap-data.ts) and docs/todo-inventory.md from the RTM.

Every requirement the RTM puts in tier S (stubbed) or D (deferred) gets one line, with a TODO(<id>) / DEFERRED(<id>)
marker so the inventory can be found by search. Status for S items:
  PARTIAL  - the id is referenced by built code, tests or a milestone evidence document
  PLANNED  - not referenced anywhere in built work: shown as "coming soon"
Run: PYTHONIOENCODING=utf-8 python _work/gen_roadmap.py && npx prettier --write packages/shared/src/roadmap-data.ts
"""

import csv
import glob
import json
import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
R = json.load(open(os.path.join(ROOT, "_work", "register.json"), encoding="utf8"))
rows = list(csv.DictReader(open(os.path.join(ROOT, "docs", "RTM.csv"), encoding="utf-8-sig")))

# description per id (same provisional-id rule as build_docs.py)
desc = {}
xn = 0
for d in R["Functional"][1:]:
    rid = d.get("A", "")
    text = (d.get("C", "") or "").strip()
    if not rid:
        xn += 1
        rid = f"FR-X{xn:02d}"
        text = text or (d.get("J", "") or "").strip()
    desc[rid] = text
for d in R["NonFunctional"][1:]:
    desc[d["A"]] = (d.get("C", "") or "").strip()
for d in R["Security"][1:]:
    desc[d["A"]] = (d.get("C", "") or "").strip()


def title(text: str) -> str:
    text = re.sub(r"\s+", " ", text).strip()
    if not text:
        return "No description in the requirements register"
    text = re.sub(r"^(The )?(platform|system|solution|customer|portal) (shall|should|must|will) ", "", text, flags=re.I)
    text = text[:1].upper() + text[1:]
    text = re.sub(r"\be\.g\.?,?", "for example", text)
    text = re.sub(r"\bi\.e\.?,?", "that is", text)
    cut = next((k for k, ch in enumerate(text) if k >= 40 and ch in ".;:" and text[k + 1 : k + 2] in ("", " ")), None)
    out = text[:cut] if cut is not None and cut <= 170 else text
    if len(out) > 170:
        out = out[:167].rsplit(" ", 1)[0] + "..."
    return out


# which area (page) a stubbed category belongs to
AREA = {
    "Request Intake & AI": "/app/requests",
    "Procurement Plan": "/app/plans",
    "Tender Portal": "/app/tenders",
    "Supplier Portal": "/supplier",
    "Evaluation": "/app/evaluations",
    "Evaluation Report": "/app/evaluations",
    "Contract Award & Legal": "/app/contracts",
    "Contract Management": "/app/contracts",
    "Reporting & Dashboards": "/app/reports",
    "Admin & Configuration": "/admin",
    "Data Migration": "/admin/migration",
    "Collaboration & AI Authoring": "/app/collaboration",
    "RFx / Tender Collaboration": "/app/collaboration",
    "Authentication & Identity": "/admin/users",
}

# is the id mentioned in built work?
built_text = ""
for pattern in ("apps/**/*.ts", "apps/**/*.tsx", "e2e/*.ts", "docs/M*-Evidence.md", "docs/swap-points.md"):
    for f in glob.glob(os.path.join(ROOT, pattern), recursive=True):
        # nav.ts only lists ids on its "coming soon" placeholders, which is not delivery
        if "node_modules" in f or os.sep + ".next" in f or os.sep + "dist" in f or f.endswith(os.sep + "nav.ts"):
            continue
        built_text += open(f, encoding="utf-8", errors="ignore").read()


def mentioned(rid: str) -> bool:
    return re.search(r"(?<![A-Za-z0-9-])" + re.escape(rid) + r"(?![0-9A-Za-z])", built_text) is not None


# requirements delivered by a roadmap batch (maintained by hand, checked by a test)
delivered = {}
for batch, info in json.load(open(os.path.join(ROOT, '_work', 'delivered.json'), encoding='utf8')).items():
    for rid in info['ids']:
        delivered[rid] = batch

items = []
for r in rows:
    tier = r["POC tier"]
    if tier not in ("S", "D"):
        continue
    rid = r["Req ID"]
    cat = r["Category"]
    if tier == "S":
        status = "BUILT" if rid in delivered else ("PARTIAL" if mentioned(rid) else "PLANNED")
        area = AREA.get(cat)
        assert area, f"no area for stub category {cat!r} ({rid})"
    else:
        status = "DEFERRED"
        area = None
    items.append(
        dict(id=rid, tier=tier, status=status, category=cat, area=area, priority=r["Priority"], title=title(desc.get(rid, "")), batch=delivered.get(rid))
    )


def ts(s):
    return json.dumps(s, ensure_ascii=False)


lines = [
    "// GENERATED by _work/gen_roadmap.py from docs/RTM.csv - do not edit by hand.",
    "// One line per stubbed (S) or deferred (D) requirement; the marker comment is what todo-inventory.md is built from.",
    "import type { RoadmapItem } from './roadmap.js';",
    "",
    "export const ROADMAP_DATA: readonly RoadmapItem[] = [",
]
for it in items:
    marker = f"TODO({it['id']})" if it["tier"] == "S" else f"DEFERRED({it['id']})"
    area = ts(it["area"]) if it["area"] else "null"
    lines.append(
        f"  {{ id: {ts(it['id'])}, tier: {ts(it['tier'])}, status: {ts(it['status'])}, category: {ts(it['category'])}, "
        f"area: {area}, priority: {ts(it['priority'])}, title: {ts(it['title'])}{', batch: ' + ts(it['batch']) if it['batch'] else ''} }}, // {marker}"
    )
lines.append("];")
lines.append("")
open(os.path.join(ROOT, "packages", "shared", "src", "roadmap-data.ts"), "w", encoding="utf8", newline="\n").write(
    "\n".join(lines)
)

# ------------------------------------------------------------------ docs/todo-inventory.md
S = [i for i in items if i["tier"] == "S"]
D = [i for i in items if i["tier"] == "D"]
md = [
    "# TODO inventory (M14)",
    "",
    "Generated by `_work/gen_roadmap.py` from `docs/RTM.csv`; the same data drives the in-app **Roadmap** page "
    "(`/app/roadmap`) and the coming-soon panels. Every tier S requirement carries a `TODO(<id>)` marker in "
    "`packages/shared/src/roadmap-data.ts` and every tier D requirement a `DEFERRED(<id>)` marker; a test "
    "(`packages/shared/src/roadmap.test.ts`) fails if any S or D requirement in the RTM is missing, is in the wrong "
    "tier, or has no area.",
    "",
    "| | Count |",
    "|---|---|",
    f"| Tier S (stubbed, shows \"coming soon\") | {len(S)} |",
    f"| of which built in a roadmap batch (each cited by an automated test) | {sum(1 for i in S if i['status'] == 'BUILT')} |",
    f"| of which referenced by earlier built work (partly or fully delivered, see the milestone evidence) | {sum(1 for i in S if i['status'] == 'PARTIAL')} |",
    f"| of which not built yet | {sum(1 for i in S if i['status'] == 'PLANNED')} |",
    f"| Tier D (deferred, not in the proof of concept) | {len(D)} |",
    "",
    "Status caveat: \"referenced by built work\" means the requirement id appears in code, tests or a milestone "
    "evidence document. Some requirements shown as not built may have been delivered under a neighbouring story "
    "without citing their id; the owner can reclassify these at the M15 gate.",
    "",
    "## Tier S by area",
    "",
]
by_area = {}
for i in S:
    by_area.setdefault(i["area"], []).append(i)
for area in sorted(by_area):
    md += [f"### `{area}`", "", "| ID | Category | Status | What it will do |", "|---|---|---|---|"]
    for i in by_area[area]:
        md.append(f"| {i['id']} | {i['category']} | { {'BUILT': 'Built', 'PARTIAL': 'Partly built', 'PLANNED': 'Coming soon'}[i['status']] } | {i['title'].replace('|', '/')} |")
    md.append("")
md += ["## Tier D by category (not in the proof of concept)", ""]
by_cat = {}
for i in D:
    by_cat.setdefault(i["category"], []).append(i)
for cat in sorted(by_cat):
    md += [f"### {cat}", "", "| ID | Priority | Requirement |", "|---|---|---|"]
    for i in by_cat[cat]:
        md.append(f"| {i['id']} | {i['priority']} | {i['title'].replace('|', '/')} |")
    md.append("")
open(os.path.join(ROOT, "docs", "todo-inventory.md"), "w", encoding="utf8", newline="\n").write("\n".join(md))
print(len(S), "S;", sum(1 for i in S if i["status"] == "PARTIAL"), "partial;", len(D), "D")
