/**
 * What each importable entity looks like (CP-07): the fields, which are required, their type and allowed values, and the
 * header synonyms the mapping suggestion uses. Pure data; one place to extend.
 */
import type { HistEntity } from '../../db/schema-cpd.js';

export type FieldType = 'text' | 'date' | 'amount' | 'abn' | 'int' | 'enum' | 'email';

export interface FieldDef {
  key: string;
  label: string;
  required: boolean;
  type: FieldType;
  synonyms: string[];
  allowed?: string[];
  hint?: string;
}

export const CONTRACT_STATUSES = [
  'ACTIVE',
  'CURRENT',
  'EXECUTED',
  'IN FORCE',
  'EXPIRED',
  'ENDED',
  'TERMINATED',
  'CANCELLED',
] as const;
export const CURRENCIES = ['AUD', 'NZD', 'USD', 'EUR', 'GBP'] as const;
export const UNITS = [
  'each',
  'hour',
  'day',
  'month',
  'year',
  'box',
  'kg',
  'litre',
  'licence',
  'user',
  'metre',
];

export const FIELDS: Record<HistEntity, FieldDef[]> = {
  CONTRACTS: [
    {
      key: 'contract_number',
      label: 'Contract number',
      required: true,
      type: 'text',
      synonyms: [
        'contract number',
        'contract no',
        'contract ref',
        'contract id',
        'agreement number',
        'agreement no',
        'agreement ref',
        'agreement id',
        'reference',
        'ref no',
        'ref',
        'contract code',
        'cn',
        'po number',
      ],
    },
    {
      key: 'title',
      label: 'Title',
      required: true,
      type: 'text',
      synonyms: [
        'title',
        'contract title',
        'contract name',
        'agreement title',
        'agreement name',
        'description',
        'subject',
        'project',
        'name',
        'scope',
      ],
    },
    {
      key: 'supplier',
      label: 'Supplier',
      required: true,
      type: 'text',
      synonyms: [
        'supplier',
        'supplier name',
        'vendor',
        'vendor name',
        'contractor',
        'counterparty',
        'party',
        'provider',
        'company',
        'organisation',
        'seller',
      ],
    },
    {
      key: 'start_date',
      label: 'Start date',
      required: true,
      type: 'date',
      synonyms: [
        'start date',
        'start',
        'commencement date',
        'commencement',
        'commence',
        'effective date',
        'effective from',
        'valid from',
        'from date',
        'begins',
        'contract start',
        'date from',
      ],
    },
    {
      key: 'end_date',
      label: 'End date',
      required: true,
      type: 'date',
      synonyms: [
        'end date',
        'end',
        'expiry date',
        'expiry',
        'expires',
        'expiration date',
        'expiration',
        'termination date',
        'valid to',
        'valid until',
        'to date',
        'finish date',
        'contract end',
        'date to',
        'completion date',
      ],
    },
    {
      key: 'value',
      label: 'Contract value',
      required: true,
      type: 'amount',
      synonyms: [
        'value',
        'contract value',
        'total value',
        'tcv',
        'total contract value',
        'amount',
        'price',
        'contract amount',
        'value aud',
        'tcv aud',
        'total',
        'commitment',
        'contract sum',
        'estimated value',
        'ecv',
      ],
    },
    {
      key: 'supplier_abn',
      label: 'Supplier ABN',
      required: false,
      type: 'abn',
      synonyms: [
        'abn',
        'supplier abn',
        'vendor abn',
        'australian business number',
        'tax id',
        'business number',
        'abn number',
        'abn no',
      ],
    },
    {
      key: 'owner',
      label: 'Contract owner',
      required: false,
      type: 'text',
      synonyms: [
        'owner',
        'contract owner',
        'manager',
        'contract manager',
        'responsible officer',
        'relationship manager',
        'administrator',
        'owner name',
        'business owner',
        'responsible person',
      ],
    },
    {
      key: 'notice_months',
      label: 'Notice period (months)',
      required: false,
      type: 'int',
      synonyms: [
        'notice months',
        'notice period months',
        'notice period',
        'notice',
        'termination notice',
        'notice (months)',
        'months notice',
      ],
    },
    {
      key: 'status',
      label: 'Status',
      required: false,
      type: 'enum',
      allowed: [...CONTRACT_STATUSES],
      synonyms: ['status', 'contract status', 'state', 'stage', 'lifecycle status'],
    },
    {
      key: 'currency',
      label: 'Currency',
      required: false,
      type: 'enum',
      allowed: [...CURRENCIES],
      synonyms: ['currency', 'ccy', 'currency code', 'cur'],
    },
    {
      key: 'text',
      label: 'Contract wording',
      required: false,
      type: 'text',
      hint: 'Obligations, KPIs, service levels, the notice period and extension options are read from this text.',
      synonyms: [
        'text',
        'contract text',
        'terms',
        'key terms',
        'clauses',
        'notes',
        'comments',
        'summary',
        'terms and conditions',
        'wording',
        'special conditions',
      ],
    },
  ],
  SUPPLIERS: [
    {
      key: 'company',
      label: 'Supplier name',
      required: true,
      type: 'text',
      synonyms: [
        'company',
        'supplier',
        'supplier name',
        'vendor',
        'vendor name',
        'name',
        'name 1',
        'legal name',
        'business name',
        'trading name',
        'organisation',
        'company name',
        'name1',
        'account name',
      ],
    },
    {
      key: 'abn',
      label: 'ABN',
      required: false,
      type: 'abn',
      synonyms: [
        'abn',
        'australian business number',
        'tax number',
        'tax id',
        'tax no',
        'business number',
        'abn number',
        'vat reg no',
        'abn no',
        'stceg',
      ],
    },
    {
      key: 'city',
      label: 'City',
      required: false,
      type: 'text',
      synonyms: ['city', 'suburb', 'town', 'locality', 'ort01'],
    },
    {
      key: 'state',
      label: 'State',
      required: false,
      type: 'text',
      synonyms: ['state', 'province', 'region', 'state code', 'regio'],
    },
    {
      key: 'category',
      label: 'Category',
      required: false,
      type: 'text',
      synonyms: [
        'category',
        'commodity',
        'spend category',
        'type',
        'industry',
        'service category',
        'vendor type',
        'classification',
      ],
    },
    {
      key: 'email',
      label: 'Contact email',
      required: false,
      type: 'email',
      synonyms: ['email', 'e-mail', 'contact email', 'email address', 'smtp_addr', 'contact'],
    },
  ],
  SPEND: [
    {
      key: 'supplier',
      label: 'Supplier',
      required: true,
      type: 'text',
      synonyms: [
        'supplier',
        'supplier name',
        'vendor',
        'vendor name',
        'payee',
        'creditor',
        'seller',
        'company',
        'paid to',
      ],
    },
    {
      key: 'amount',
      label: 'Amount',
      required: true,
      type: 'amount',
      synonyms: [
        'amount',
        'invoice amount',
        'spend',
        'total',
        'value',
        'net amount',
        'amount aud',
        'cost',
        'paid',
        'payment amount',
        'dmbtr',
        'line total',
        'price',
      ],
    },
    {
      key: 'date',
      label: 'Date',
      required: true,
      type: 'date',
      synonyms: [
        'date',
        'invoice date',
        'transaction date',
        'payment date',
        'posting date',
        'paid date',
        'spend date',
        'document date',
        'budat',
        'order date',
        'po date',
      ],
    },
    {
      key: 'category',
      label: 'Category',
      required: false,
      type: 'text',
      synonyms: [
        'category',
        'spend category',
        'commodity',
        'gl category',
        'account category',
        'unspsc',
        'expense type',
        'type',
        'cost type',
      ],
    },
    {
      key: 'business_unit',
      label: 'Business unit',
      required: false,
      type: 'text',
      synonyms: [
        'business unit',
        'department',
        'division',
        'unit',
        'bu',
        'org unit',
        'directorate',
        'branch',
      ],
    },
    {
      key: 'cost_centre',
      label: 'Cost centre',
      required: false,
      type: 'text',
      synonyms: ['cost centre', 'cost center', 'cc', 'costcentre', 'kostl', 'cost code'],
    },
    {
      key: 'reference',
      label: 'Reference',
      required: false,
      type: 'text',
      synonyms: [
        'reference',
        'invoice number',
        'invoice no',
        'invoice',
        'po number',
        'po',
        'purchase order',
        'document number',
        'doc no',
        'belnr',
        'ref',
        'ref no',
      ],
    },
    {
      key: 'description',
      label: 'Description',
      required: false,
      type: 'text',
      synonyms: ['description', 'details', 'narrative', 'line description', 'memo', 'notes', 'item'],
    },
    {
      key: 'currency',
      label: 'Currency',
      required: false,
      type: 'enum',
      allowed: [...CURRENCIES],
      synonyms: ['currency', 'ccy', 'currency code', 'waers'],
    },
  ],
  CATALOGUE: [
    {
      key: 'supplier',
      label: 'Supplier',
      required: true,
      type: 'text',
      synonyms: ['supplier', 'supplier name', 'vendor', 'vendor name', 'seller', 'manufacturer'],
    },
    {
      key: 'sku',
      label: 'SKU',
      required: true,
      type: 'text',
      synonyms: [
        'sku',
        'item code',
        'part number',
        'product code',
        'item number',
        'catalogue number',
        'stock code',
        'code',
        'material',
        'matnr',
        'item id',
        'part no',
      ],
    },
    {
      key: 'name',
      label: 'Item name',
      required: true,
      type: 'text',
      synonyms: [
        'name',
        'item name',
        'item',
        'product',
        'product name',
        'description',
        'item description',
        'title',
      ],
    },
    {
      key: 'unit_price',
      label: 'Unit price',
      required: true,
      type: 'amount',
      synonyms: [
        'unit price',
        'price',
        'price each',
        'contract price',
        'rate',
        'unit cost',
        'cost',
        'list price',
        'price ex gst',
        'unit rate',
        'net price',
        'netpr',
      ],
    },
    {
      key: 'category',
      label: 'Category',
      required: false,
      type: 'text',
      synonyms: ['category', 'product category', 'commodity', 'group', 'product group', 'class', 'family'],
    },
    {
      key: 'unit',
      label: 'Unit',
      required: false,
      type: 'text',
      synonyms: ['unit', 'uom', 'unit of measure', 'unit of issue', 'pack', 'meins'],
    },
    {
      key: 'lead_days',
      label: 'Lead time (days)',
      required: false,
      type: 'int',
      synonyms: [
        'lead days',
        'lead time',
        'lead time days',
        'delivery days',
        'days to deliver',
        'delivery time',
        'lead',
      ],
    },
    {
      key: 'contract_number',
      label: 'Contract number',
      required: false,
      type: 'text',
      synonyms: [
        'contract number',
        'contract',
        'contract no',
        'agreement',
        'agreement number',
        'contract ref',
        'panel',
      ],
    },
  ],
};

export const ENTITY_LABEL: Record<HistEntity, string> = {
  CONTRACTS: 'Contracts',
  SUPPLIERS: 'Suppliers',
  SPEND: 'Historical spend',
  CATALOGUE: 'Catalogue prices',
};

export const requiredFields = (e: HistEntity) => FIELDS[e].filter((f) => f.required).map((f) => f.key);
export const fieldDef = (e: HistEntity, key: string) => FIELDS[e].find((f) => f.key === key);
