DROP TABLE IF EXISTS disclosure_task;
DROP TABLE IF EXISTS envelope_commitment;
DROP TABLE IF EXISTS funding_envelope;
DROP TABLE IF EXISTS contract_activity;
DROP TABLE IF EXISTS contract_plan;
DROP TABLE IF EXISTS spend_alert;
DROP TABLE IF EXISTS contract_hold;
DROP TABLE IF EXISTS invoice;
DROP TABLE IF EXISTS purchase_order;
DROP TABLE IF EXISTS work_order;
DROP TABLE IF EXISTS contract_rebate;
DROP TABLE IF EXISTS contract_escalation;
DROP TABLE IF EXISTS contract_rate;
DROP TABLE IF EXISTS alert_preference;
ALTER TABLE request DROP COLUMN IF EXISTS link_kind, DROP COLUMN IF EXISTS linked_contract_id;
ALTER TABLE contract_extension DROP COLUMN IF EXISTS exercised_request_id, DROP COLUMN IF EXISTS exercised_at;
ALTER TABLE contract DROP COLUMN IF EXISTS linked_request_id, DROP COLUMN IF EXISTS variance_model, DROP COLUMN IF EXISTS variance_pct, DROP COLUMN IF EXISTS business_case;
DELETE FROM alert_delivery WHERE channel IN ('SMS', 'SLACK');
ALTER TABLE alert_delivery DROP CONSTRAINT IF EXISTS alert_delivery_channel_check;
ALTER TABLE alert_delivery ADD CONSTRAINT alert_delivery_channel_check CHECK (channel IN ('IN_APP', 'EMAIL'));
ALTER TABLE alert DROP COLUMN IF EXISTS owner_id, DROP COLUMN IF EXISTS channels;
