/**
 * Drizzle schema = single source for TypeScript types. DDL is generated by drizzle-kit into ./migrations,
 * then hand-written migrations add what Drizzle cannot express (roles, grants, RLS, append-only audit).
 * Every business table is tenant-scoped (`tenant_id`). See Technical Specification section 3.2.
 */
import { sql } from 'drizzle-orm';
import {
  bigint,
  bigserial,
  boolean,
  index,
  integer,
  jsonb,
  numeric,
  pgTable,
  text,
  timestamp,
  uniqueIndex,
  uuid,
  date,
} from 'drizzle-orm/pg-core';

export const ROLES = [
  'REQUESTER',
  'PROCUREMENT',
  'DELEGATE',
  'EVALUATOR',
  'CHAIR',
  'LEGAL',
  'CONTRACT_MGR',
  'PROBITY',
  'FINANCE',
  'ADMIN',
  'EXEC',
  'SUPPLIER',
] as const;
export type Role = (typeof ROLES)[number];

export const PHASES = [
  'INTAKE',
  'PLAN',
  'TENDER',
  'EVALUATION',
  'CONTRACT_AWARD',
  'CONTRACT_MGMT',
  'CLOSED',
] as const;

const id = () =>
  uuid('id')
    .primaryKey()
    .default(sql`gen_random_uuid()`);
const tenantId = () => uuid('tenant_id').notNull();
const created = () => timestamp('created_at', { withTimezone: true }).notNull().defaultNow();
const updated = () => timestamp('updated_at', { withTimezone: true }).notNull().defaultNow();
const version = () => integer('version').notNull().default(1);

export const tenant = pgTable('tenant', {
  id: id(),
  slug: text('slug').notNull().unique(),
  name: text('name').notNull(),
  region: text('region').notNull().default('ap-southeast-2'),
  sector: text('sector', { enum: ['PUBLIC', 'PRIVATE'] }).notNull(),
  config: jsonb('config').notNull().default({}),
  createdAt: created(),
});

export const orgUnit = pgTable('org_unit', {
  id: id(),
  tenantId: tenantId(),
  name: text('name').notNull(),
  parentId: uuid('parent_id'),
  createdAt: created(),
});

export const appUser = pgTable(
  'app_user',
  {
    id: id(),
    tenantId: tenantId(),
    email: text('email').notNull(),
    name: text('name').notNull(),
    orgUnitId: uuid('org_unit_id'),
    passwordHash: text('password_hash').notNull(),
    active: boolean('active').notNull().default(true),
    failedAttempts: integer('failed_attempts').notNull().default(0),
    lockedUntil: timestamp('locked_until', { withTimezone: true }),
    supplierId: uuid('supplier_id'),
    /** An external person (for example a probity advisor) who sees only what they are allocated (FR-0310). */
    external: boolean('external').notNull().default(false),
    createdAt: created(),
    updatedAt: updated(),
  },
  (t) => [uniqueIndex('app_user_email_uq').on(t.tenantId, t.email)],
);

export const roleAssignment = pgTable(
  'role_assignment',
  {
    id: id(),
    tenantId: tenantId(),
    userId: uuid('user_id').notNull(),
    role: text('role', { enum: ROLES }).notNull(),
    division: text('division'),
    /** A time-bound grant ends here; the role then stops applying (SEC-A05). Null means it does not expire. */
    expiresAt: timestamp('expires_at', { withTimezone: true }),
    grantedBy: uuid('granted_by'),
  },
  (t) => [uniqueIndex('role_assignment_uq').on(t.userId, t.role)],
);

export const delegation = pgTable('delegation', {
  id: id(),
  tenantId: tenantId(),
  scope: text('scope', { enum: ['SOURCING_APPROVAL', 'CONTRACT_SIGNING', 'PUBLISH_PERMISSION'] }).notNull(),
  role: text('role', { enum: ROLES }).notNull(),
  userId: uuid('user_id'),
  maxValue: numeric('max_value', { precision: 14, scale: 2 }).notNull(),
  division: text('division'),
  /** A grant for spend in a foreign currency; the other grants apply to spend in the base currency only (FR-0810). */
  international: boolean('international').notNull().default(false),
  active: boolean('active').notNull().default(true),
  createdAt: created(),
  updatedAt: updated(),
});

export const supplier = pgTable('supplier', {
  id: id(),
  tenantId: tenantId(),
  company: text('company').notNull(),
  abn: text('abn').notNull(),
  sanctionsStatus: text('sanctions_status', { enum: ['PENDING', 'CLEAR', 'MATCH'] })
    .notNull()
    .default('PENDING'),
  insuranceStatus: text('insurance_status', { enum: ['UNKNOWN', 'CURRENT', 'EXPIRING', 'EXPIRED'] })
    .notNull()
    .default('UNKNOWN'),
  lastCheckedAt: timestamp('last_checked_at', { withTimezone: true }),
  categories: jsonb('categories').notNull().default([]),
  onboarding: jsonb('onboarding').notNull().default({}),
  privacy: jsonb('privacy').notNull().default({ shareProfile: true, productUpdates: false }),
  insurance: jsonb('insurance'),
  insuranceExpiresOn: date('insurance_expires_on'),
  sanctionsNote: text('sanctions_note'),
  /** Bank details the supplier gave, checked before signature options unlock (FR-0415). */
  bank: jsonb('bank'),
  /** Where the supplier operates from, for the supplier risk map (FR-0610). */
  location: jsonb('location'),
  /** The insurance certificate a supplier uploaded and what was read from it (FR-0185). */
  insuranceCertificate: jsonb('insurance_certificate'),
  createdAt: created(),
});

export const request = pgTable(
  'request',
  {
    id: id(),
    tenantId: tenantId(),
    number: text('number').notNull(),
    title: text('title').notNull(),
    category: text('category'),
    unspsc: text('unspsc'),
    estimatedValue: numeric('estimated_value', { precision: 14, scale: 2 }),
    currency: text('currency').notNull().default('AUD'),
    termMonths: integer('term_months'),
    businessUnit: text('business_unit'),
    requesterId: uuid('requester_id').notNull(),
    phase: text('phase', { enum: PHASES }).notNull().default('INTAKE'),
    status: text('status', { enum: ['DRAFT', 'SUBMITTED', 'IN_PROGRESS', 'BLOCKED', 'COMPLETE'] })
      .notNull()
      .default('DRAFT'),
    intakeMode: text('intake_mode', { enum: ['SELF_SERVICE', 'TEAM_LED'] })
      .notNull()
      .default('TEAM_LED'),
    complexity: text('complexity', { enum: ['LOW', 'MEDIUM', 'HIGH', 'CRITICAL'] }),
    budgetCheck: text('budget_check', { enum: ['NOT_RUN', 'CLEARED', 'EXCEEDED', 'UNAVAILABLE'] })
      .notNull()
      .default('NOT_RUN'),
    taxonomyScheme: text('taxonomy_scheme'),
    taxonomyCode: text('taxonomy_code'),
    taxonomyConfirmed: boolean('taxonomy_confirmed').notNull().default(false),
    workflowId: text('workflow_id'),
    subWorkflow: text('sub_workflow'),
    processSteps: jsonb('process_steps').notNull().default([]),
    processVariations: jsonb('process_variations').notNull().default([]),
    engagements: jsonb('engagements').notNull().default([]),
    nominatedDelegates: jsonb('nominated_delegates').notNull().default({}),
    ecv: jsonb('ecv'),
    sourceSystem: text('source_system'),
    /** A procurement linked to an existing contract to renew it, vary it or take up an extension (FR-0570). */
    linkedContractId: uuid('linked_contract_id'),
    linkKind: text('link_kind', { enum: ['RENEW', 'VARY', 'EXTEND'] }),
    /** The procurement manager the work is assigned to, for workload and capacity (FR-0620). */
    managerId: uuid('manager_id'),
    /** When the amount was entered in a foreign currency: what was typed and the rate used. `estimated_value` is always in the base currency (FR-0810). */
    originalAmount: numeric('original_amount', { precision: 14, scale: 2 }),
    fxRate: numeric('fx_rate', { precision: 18, scale: 8 }),
    createdAt: created(),
    updatedAt: updated(),
    version: version(),
  },
  (t) => [
    uniqueIndex('request_number_uq').on(t.tenantId, t.number),
    index('request_requester_idx').on(t.requesterId),
  ],
);

export const conversation = pgTable('conversation', {
  id: id(),
  tenantId: tenantId(),
  userId: uuid('user_id').notNull(),
  purpose: text('purpose').notNull(),
  contextId: uuid('context_id'),
  simulated: boolean('simulated').notNull().default(true),
  createdAt: created(),
});

export const chatMessage = pgTable('chat_message', {
  id: id(),
  tenantId: tenantId(),
  conversationId: uuid('conversation_id').notNull(),
  role: text('role', { enum: ['USER', 'ASSISTANT', 'SYSTEM'] }).notNull(),
  text: text('text').notNull(),
  proposedChanges: jsonb('proposed_changes'),
  createdAt: created(),
});

export const plan = pgTable('plan', {
  id: id(),
  tenantId: tenantId(),
  requestId: uuid('request_id').notNull().unique(),
  status: text('status', {
    enum: ['DRAFT', 'AWAITING_SIGNOFF', 'AWAITING_APPROVAL', 'APPROVED_LOCKED', 'REOPENED', 'REJECTED'],
  })
    .notNull()
    .default('DRAFT'),
  summary: text('summary'),
  locked: boolean('locked').notNull().default(false),
  createdAt: created(),
  updatedAt: updated(),
  version: version(),
});

export const fieldValue = pgTable(
  'field_value',
  {
    id: id(),
    tenantId: tenantId(),
    ownerType: text('owner_type', {
      enum: ['REQUEST', 'PLAN', 'TENDER', 'EVAL_REPORT', 'CONTRACT'],
    }).notNull(),
    ownerId: uuid('owner_id').notNull(),
    key: text('key').notNull(),
    label: text('label').notNull(),
    value: text('value'),
    source: text('source', { enum: ['USER', 'AI', 'SYSTEM', 'MIGRATED'] })
      .notNull()
      .default('USER'),
    aiDrafted: boolean('ai_drafted').notNull().default(false),
    missing: boolean('missing').notNull().default(false),
    /** Counts changes to the value, so a concurrent edit of the same field is noticed (FR-0735). */
    rev: integer('rev').notNull().default(1),
    previousValue: text('previous_value'),
    updatedBy: uuid('updated_by'),
    updatedAt: updated(),
  },
  (t) => [uniqueIndex('field_value_uq').on(t.ownerType, t.ownerId, t.key)],
);

export const approval = pgTable('approval', {
  id: id(),
  tenantId: tenantId(),
  subjectType: text('subject_type').notNull(),
  subjectId: uuid('subject_id').notNull(),
  userId: uuid('user_id').notNull(),
  role: text('role').notNull(),
  decision: text('decision', { enum: ['APPROVED', 'REJECTED', 'SUPERSEDED'] }).notNull(),
  comment: text('comment'),
  stamp: text('stamp'),
  decidedAt: timestamp('decided_at', { withTimezone: true }).notNull().defaultNow(),
});

export const coiDeclaration = pgTable('coi_declaration', {
  id: id(),
  tenantId: tenantId(),
  userId: uuid('user_id').notNull(),
  scope: text('scope', { enum: ['PLAN', 'EVALUATION', 'REPORT'] }).notNull(),
  scopeId: uuid('scope_id').notNull(),
  none: boolean('none').notNull(),
  nature: text('nature'),
  subjectOrg: text('subject_org'),
  disposition: text('disposition', { enum: ['PENDING', 'IMMATERIAL', 'MANAGEABLE', 'MATERIAL'] })
    .notNull()
    .default('PENDING'),
  routedTo: uuid('routed_to'),
  decidedAt: timestamp('decided_at', { withTimezone: true }),
  /** A minor conflict lets the person stay but not assess this supplier (FR-0330). */
  excludedSupplierId: uuid('excluded_supplier_id'),
  decidedBy: uuid('decided_by'),
  decidedByRole: text('decided_by_role'),
  decisionNote: text('decision_note'),
  createdAt: created(),
});

export const tender = pgTable('tender', {
  id: id(),
  tenantId: tenantId(),
  requestId: uuid('request_id').notNull(),
  type: text('type', { enum: ['RFT', 'RFP', 'RFQ', 'RFI', 'EOI'] }).notNull(),
  access: text('access', { enum: ['OPEN', 'CLOSED'] })
    .notNull()
    .default('CLOSED'),
  status: text('status', { enum: ['DRAFT', 'STAGED', 'PUBLISHED', 'CLOSED', 'EVALUATING', 'AWARDED'] })
    .notNull()
    .default('DRAFT'),
  opensAt: timestamp('opens_at', { withTimezone: true }),
  closesAt: timestamp('closes_at', { withTimezone: true }),
  publishPermissionId: uuid('publish_permission_id'),
  /** Stage 1 is the first round; a later stage is a separate pack and round for shortlisted suppliers (FR-0220). */
  stage: integer('stage').notNull().default(1),
  parentTenderId: uuid('parent_tender_id'),
  shortlist: jsonb('shortlist'),
  shortlistedAt: timestamp('shortlisted_at', { withTimezone: true }),
  /** High-value or high-risk: the sealed bids stay shut after close until two independent witnesses release them (FR-0175). */
  dualWitness: boolean('dual_witness').notNull().default(false),
  openedAt: timestamp('opened_at', { withTimezone: true }),
  /** Least insurance cover a supplier must hold to submit (FR-0185). */
  requiredCover: numeric('required_cover', { precision: 14, scale: 2 }),
  createdAt: created(),
  updatedAt: updated(),
  version: version(),
});

export const invitation = pgTable('invitation', {
  id: id(),
  tenantId: tenantId(),
  tenderId: uuid('tender_id').notNull(),
  email: text('email').notNull(),
  company: text('company').notNull(),
  tokenHash: text('token_hash').notNull(),
  expiresAt: timestamp('expires_at', { withTimezone: true }).notNull(),
  usedAt: timestamp('used_at', { withTimezone: true }),
  supplierId: uuid('supplier_id'),
});

export const question = pgTable('question', {
  id: id(),
  tenantId: tenantId(),
  tenderId: uuid('tender_id').notNull(),
  text: text('text').notNull(),
  answer: text('answer'),
  status: text('status', { enum: ['OPEN', 'ANSWERED', 'PUBLISHED'] })
    .notNull()
    .default('OPEN'),
  // Restricted column: never selected by any API serialiser (anonymity, FR-0135).
  askedBySupplierId: uuid('asked_by_supplier_id'),
  /** ALL: the answer is published to every supplier. SINGLE: only to the supplier who asked (FR-0195). */
  audience: text('audience', { enum: ['ALL', 'SINGLE'] })
    .notNull()
    .default('ALL'),
  targetSupplierId: uuid('target_supplier_id'),
  askedAt: timestamp('asked_at', { withTimezone: true }).notNull().defaultNow(),
});

export const addendum = pgTable('addendum', {
  id: id(),
  tenantId: tenantId(),
  tenderId: uuid('tender_id').notNull(),
  number: integer('number').notNull(),
  summary: text('summary').notNull(),
  questionIds: jsonb('question_ids').notNull().default([]),
  newClosesAt: timestamp('new_closes_at', { withTimezone: true }),
  issuedAt: timestamp('issued_at', { withTimezone: true }).notNull().defaultNow(),
});

export const submission = pgTable(
  'submission',
  {
    id: id(),
    tenantId: tenantId(),
    tenderId: uuid('tender_id').notNull(),
    supplierId: uuid('supplier_id').notNull(),
    status: text('status', { enum: ['DRAFT', 'SUBMITTED', 'REJECTED_LATE'] })
      .notNull()
      .default('DRAFT'),
    receipt: text('receipt'),
    submittedAt: timestamp('submitted_at', { withTimezone: true }),
    createdAt: created(),
  },
  (t) => [uniqueIndex('submission_uq').on(t.tenderId, t.supplierId)],
);

export const fileObject = pgTable('file_object', {
  id: id(),
  tenantId: tenantId(),
  submissionId: uuid('submission_id').notNull(),
  name: text('name').notNull(),
  sizeBytes: integer('size_bytes').notNull(),
  contentType: text('content_type').notNull(),
  storageKey: text('storage_key').notNull(),
  sha256: text('sha256'),
  scan: text('scan', { enum: ['PENDING', 'CLEAN', 'INFECTED'] })
    .notNull()
    .default('PENDING'),
  section: text('section', { enum: ['TECHNICAL', 'COMMERCIAL', 'OTHER'] })
    .notNull()
    .default('OTHER'),
  /** Set when this file was carried forward from an earlier stage (FR-0230). */
  carriedFrom: uuid('carried_from'),
  createdAt: created(),
});

export const evaluation = pgTable('evaluation', {
  id: id(),
  tenantId: tenantId(),
  tenderId: uuid('tender_id').notNull().unique(),
  status: text('status', { enum: ['COI_PENDING', 'SCORING', 'CONSENSUS', 'LOCKED', 'REPORTED', 'APPROVED'] })
    .notNull()
    .default('COI_PENDING'),
  varianceLimitPct: integer('variance_limit_pct').notNull().default(30),
  /** SCORING: numeric scores per criterion. RANKING: evaluators order the suppliers (FR-0280). */
  mode: text('mode', { enum: ['SCORING', 'RANKING'] })
    .notNull()
    .default('SCORING'),
  /** In ranking mode, the share of the final ranking that comes from normalised total cost of ownership. */
  priceWeightPct: integer('price_weight_pct').notNull().default(30),
  /** A probity advisor's system hold freezes the evaluation workspace (FR-0310). */
  held: boolean('held').notNull().default(false),
  holdReason: text('hold_reason'),
  heldBy: uuid('held_by'),
  heldAt: timestamp('held_at', { withTimezone: true }),
  createdAt: created(),
  updatedAt: updated(),
  version: version(),
});

export const criterion = pgTable('criterion', {
  id: id(),
  tenantId: tenantId(),
  evaluationId: uuid('evaluation_id').notNull(),
  name: text('name').notNull(),
  weight: numeric('weight', { precision: 5, scale: 2 }).notNull(),
  stream: text('stream', { enum: ['TECHNICAL', 'COMMERCIAL', 'OTHER'] }).notNull(),
  passFail: boolean('pass_fail').notNull().default(false),
});

export const panelMember = pgTable(
  'panel_member',
  {
    id: id(),
    tenantId: tenantId(),
    evaluationId: uuid('evaluation_id').notNull(),
    userId: uuid('user_id').notNull(),
    stream: text('stream', { enum: ['TECHNICAL', 'COMMERCIAL', 'OTHER'] }).notNull(),
    coiState: text('coi_state', { enum: ['NOT_DECLARED', 'DECLARED_NONE', 'DECLARED_CONFLICT', 'REMOVED'] })
      .notNull()
      .default('NOT_DECLARED'),
    /** When the member marked their scoring complete (the chair needs all of them before opening consensus). */
    scoredAt: timestamp('scored_at', { withTimezone: true }),
    /** The second declaration, once supplier identities are known (FR-0325). */
    redeclaredAt: timestamp('redeclared_at', { withTimezone: true }),
    redeclaration: text('redeclaration', { enum: ['NONE', 'CONFLICT'] }),
    remindedAt: timestamp('reminded_at', { withTimezone: true }),
  },
  (t) => [uniqueIndex('panel_member_uq').on(t.evaluationId, t.userId)],
);

export const score = pgTable(
  'score',
  {
    id: id(),
    tenantId: tenantId(),
    evaluationId: uuid('evaluation_id').notNull(),
    supplierId: uuid('supplier_id').notNull(),
    criterionId: uuid('criterion_id').notNull(),
    evaluatorId: uuid('evaluator_id').notNull(),
    score: numeric('score', { precision: 4, scale: 2 }).notNull(),
    comment: text('comment'),
    createdAt: created(),
  },
  (t) => [uniqueIndex('score_uq').on(t.evaluationId, t.supplierId, t.criterionId, t.evaluatorId)],
);

export const consensusItem = pgTable(
  'consensus_item',
  {
    id: id(),
    tenantId: tenantId(),
    evaluationId: uuid('evaluation_id').notNull(),
    supplierId: uuid('supplier_id').notNull(),
    criterionId: uuid('criterion_id').notNull(),
    variancePct: numeric('variance_pct', { precision: 6, scale: 2 }),
    flagged: boolean('flagged').notNull().default(false),
    consensusScore: numeric('consensus_score', { precision: 4, scale: 2 }),
    rationale: text('rationale'),
  },
  (t) => [uniqueIndex('consensus_uq').on(t.evaluationId, t.supplierId, t.criterionId)],
);

export const evalReport = pgTable('eval_report', {
  id: id(),
  tenantId: tenantId(),
  evaluationId: uuid('evaluation_id').notNull().unique(),
  status: text('status', { enum: ['DRAFT', 'AWAITING_APPROVAL', 'APPROVED'] })
    .notNull()
    .default('DRAFT'),
  generatedAt: timestamp('generated_at', { withTimezone: true }).notNull().defaultNow(),
  /** The delegate whose authority covers the value, to whom approval is routed (FR-0375). */
  routedTo: uuid('routed_to'),
  requiredAuthority: numeric('required_authority', { precision: 14, scale: 2 }),
});

export const contract = pgTable('contract', {
  id: id(),
  tenantId: tenantId(),
  number: text('number').notNull(),
  tenderId: uuid('tender_id'),
  supplierId: uuid('supplier_id').notNull(),
  parentId: uuid('parent_id'),
  templateId: text('template_id'),
  status: text('status', {
    enum: ['DRAFT', 'LEGAL_REVIEW', 'AWAITING_SIGNATURE', 'PARTIALLY_SIGNED', 'EXECUTED'],
  })
    .notNull()
    .default('DRAFT'),
  value: numeric('value', { precision: 14, scale: 2 }).notNull(),
  startDate: date('start_date'),
  endDate: date('end_date'),
  noticeDays: integer('notice_days').notNull().default(90),
  locked: boolean('locked').notNull().default(false),
  ownerId: uuid('owner_id'),
  sourceSystem: text('source_system'),
  /** The contract itself, or another document that is signed the same way (FR-0430). */
  docType: text('doc_type', { enum: ['CONTRACT', 'NDA', 'CONFIDENTIALITY', 'MASTER'] })
    .notNull()
    .default('CONTRACT'),
  /** STANDARD, BLIND (signatories see no one else's signature) or STAGED (signed in sequence) (FR-0425). */
  signingMode: text('signing_mode', { enum: ['STANDARD', 'BLIND', 'STAGED'] })
    .notNull()
    .default('STANDARD'),
  title: text('title'),
  releasedAt: timestamp('released_at', { withTimezone: true }),
  /** A variation's logged business case, its variance and the model it was measured by (FR-0535, FR-0540). */
  businessCase: text('business_case'),
  variancePct: numeric('variance_pct', { precision: 9, scale: 2 }),
  varianceModel: text('variance_model', { enum: ['CUMULATIVE', 'INCREMENTAL'] }),
  linkedRequestId: uuid('linked_request_id'),
  deletedAt: timestamp('deleted_at', { withTimezone: true }), // logical delete only (NFR-CA02)
  createdAt: created(),
  updatedAt: updated(),
  version: version(),
});

export const clause = pgTable('clause', {
  id: id(),
  tenantId: tenantId(),
  contractId: uuid('contract_id').notNull(),
  clauseId: text('clause_id').notNull(),
  title: text('title').notNull(),
  text: text('text').notNull(),
  mandatory: boolean('mandatory').notNull().default(false),
  changedFromTemplate: boolean('changed_from_template').notNull().default(false),
  risk: text('risk', { enum: ['LOW', 'MEDIUM', 'HIGH'] }),
  editedBy: uuid('edited_by'),
  editedAt: timestamp('edited_at', { withTimezone: true }),
  /** Redacted wording is withheld from exports and from anyone who is not Legal (FR-0830). */
  redacted: boolean('redacted').notNull().default(false),
  /** A clause Legal inserted sits after this one; null for template clauses (FR-0830). */
  afterClauseId: text('after_clause_id'),
});

export const alert = pgTable('alert', {
  id: id(),
  tenantId: tenantId(),
  contractId: uuid('contract_id').notNull(),
  kind: text('kind', {
    enum: ['EXPIRY', 'NOTICE', 'MILESTONE', 'EXTENSION', 'CUSTOM', 'COUNTDOWN', 'INSURANCE', 'CLAUSE'],
  }).notNull(),
  triggerDate: date('trigger_date').notNull(),
  recipientRule: text('recipient_rule').notNull().default('CONTRACT_OWNER'),
  status: text('status', { enum: ['SCHEDULED', 'SENT', 'CANCELLED'] })
    .notNull()
    .default('SCHEDULED'),
  origin: text('origin', { enum: ['SYSTEM', 'USER', 'AI'] })
    .notNull()
    .default('SYSTEM'),
  sentAt: timestamp('sent_at', { withTimezone: true }),
  note: text('note'),
  createdBy: uuid('created_by'),
  /** Where a custom alert is delivered, and who it is assigned to besides its author (FR-0515). */
  channels: jsonb('channels').notNull().default(['IN_APP', 'EMAIL']),
  ownerId: uuid('owner_id'),
});

export const contractMilestone = pgTable('contract_milestone', {
  id: id(),
  tenantId: tenantId(),
  contractId: uuid('contract_id').notNull(),
  title: text('title').notNull(),
  dueDate: date('due_date').notNull(),
});

export const contractExtension = pgTable('contract_extension', {
  id: id(),
  tenantId: tenantId(),
  contractId: uuid('contract_id').notNull(),
  months: integer('months').notNull(),
  position: integer('position').notNull().default(1),
  exercisedAt: timestamp('exercised_at', { withTimezone: true }),
  exercisedRequestId: uuid('exercised_request_id'),
});

export const alertDelivery = pgTable('alert_delivery', {
  id: id(),
  tenantId: tenantId(),
  alertId: uuid('alert_id').notNull(),
  userId: uuid('user_id').notNull(),
  channel: text('channel', { enum: ['IN_APP', 'EMAIL', 'SMS', 'SLACK'] }).notNull(),
  status: text('status', { enum: ['DELIVERED', 'SIMULATED'] }).notNull(),
  deliveredAt: timestamp('delivered_at', { withTimezone: true }).notNull().defaultNow(),
});

export const supplierActivation = pgTable('supplier_activation', {
  id: id(),
  tenantId: tenantId(),
  userId: uuid('user_id').notNull(),
  tokenHash: text('token_hash').notNull().unique(),
  expiresAt: timestamp('expires_at', { withTimezone: true }).notNull(),
  usedAt: timestamp('used_at', { withTimezone: true }),
  createdBy: uuid('created_by').notNull(),
  createdAt: created(),
});

export const notification = pgTable('notification', {
  id: id(),
  tenantId: tenantId(),
  userId: uuid('user_id').notNull(),
  title: text('title').notNull(),
  body: text('body'),
  link: text('link'),
  event: text('event'),
  read: boolean('read').notNull().default(false),
  createdAt: created(),
});

export const notificationDelivery = pgTable('notification_delivery', {
  id: id(),
  tenantId: tenantId(),
  notificationId: uuid('notification_id').notNull(),
  channel: text('channel').notNull(),
  status: text('status').notNull().default('SENT'),
  detail: text('detail'),
  createdAt: created(),
});

export const escalation = pgTable(
  'escalation',
  {
    id: id(),
    tenantId: tenantId(),
    entityType: text('entity_type').notNull(),
    entityId: uuid('entity_id').notNull(),
    level: integer('level').notNull().default(1),
    notifiedUserId: uuid('notified_user_id').notNull(),
    createdAt: created(),
  },
  (t) => [uniqueIndex('escalation_once').on(t.entityType, t.entityId, t.level)],
);

export const template = pgTable('template', {
  id: text('id').primaryKey(),
  tenantId: tenantId(),
  type: text('type').notNull(),
  name: text('name').notNull(),
  version: text('version').notNull(),
  status: text('status').notNull().default('ACTIVE'),
  body: jsonb('body').notNull().default({}),
});

export const workflow = pgTable('workflow', {
  id: text('id').primaryKey(),
  tenantId: tenantId(),
  name: text('name').notNull(),
  tier: text('tier', { enum: ['SIMPLE', 'INTERMEDIATE', 'COMPLEX'] }).notNull(),
  steps: jsonb('steps').notNull().default([]),
  subWorkflows: jsonb('sub_workflows').notNull().default([]),
  editable: boolean('editable').notNull().default(false),
});

export const idempotencyKey = pgTable(
  'idempotency_key',
  {
    id: id(),
    tenantId: tenantId(),
    key: text('key').notNull(),
    userId: uuid('user_id').notNull(),
    method: text('method').notNull(),
    path: text('path').notNull(),
    requestHash: text('request_hash').notNull(),
    status: integer('status'),
    response: jsonb('response'),
    createdAt: created(),
  },
  (t) => [uniqueIndex('idempotency_uq').on(t.tenantId, t.userId, t.key)],
);

export const auditEvent = pgTable(
  'audit_event',
  {
    seq: bigserial('seq', { mode: 'number' }).primaryKey(),
    tenantId: tenantId(),
    at: timestamp('at', { withTimezone: true }).notNull().defaultNow(),
    actorId: uuid('actor_id'),
    actorRole: text('actor_role'),
    action: text('action').notNull(),
    entityType: text('entity_type').notNull(),
    entityId: uuid('entity_id'),
    before: jsonb('before'),
    after: jsonb('after'),
    correlationId: text('correlation_id'),
    result: text('result', { enum: ['SUCCESS', 'DENIED', 'FAILED'] })
      .notNull()
      .default('SUCCESS'),
    prevHash: text('prev_hash').notNull(),
    hash: text('hash').notNull(),
    /** ADMIN for administrative actions, else GENERAL; generated by the database from the action and the actor's role (SEC-L02). */
    category: text('category').generatedAlwaysAs(sql`'GENERAL'`),
  },
  (t) => [
    index('audit_entity_idx').on(t.entityType, t.entityId),
    index('audit_tenant_seq_idx').on(t.tenantId, t.seq),
  ],
);

/** Server-side sessions: enables idle timeout, absolute timeout and immediate revocation (SEC-A07). */
export const session = pgTable(
  'session',
  {
    id: uuid('id').primaryKey(),
    tenantId: tenantId(),
    userId: uuid('user_id').notNull(),
    pool: text('pool', { enum: ['STAFF', 'SUPPLIER'] }).notNull(), // separate identity pools (SEC-A03)
    createdAt: created(),
    lastSeenAt: timestamp('last_seen_at', { withTimezone: true }).notNull().defaultNow(),
    expiresAt: timestamp('expires_at', { withTimezone: true }).notNull(),
    revokedAt: timestamp('revoked_at', { withTimezone: true }),
    ip: text('ip'),
    userAgent: text('user_agent'),
    mfaState: text('mfa_state', { enum: ['NOT_REQUIRED', 'VERIFIED', 'ENROLMENT_REQUIRED'] })
      .notNull()
      .default('NOT_REQUIRED'),
    authMethod: text('auth_method', { enum: ['PASSWORD', 'SSO'] })
      .notNull()
      .default('PASSWORD'),
  },
  (t) => [index('session_user_idx').on(t.userId)],
);

export const migrationBatch = pgTable('migration_batch', {
  id: id(),
  tenantId: tenantId(),
  filename: text('filename').notNull(),
  sourceSystem: text('source_system').notNull(),
  status: text('status', { enum: ['VALIDATED', 'CUTOVER', 'CANCELLED'] })
    .notNull()
    .default('VALIDATED'),
  total: integer('total').notNull().default(0),
  uploadedBy: uuid('uploaded_by').notNull(),
  createdAt: created(),
  cutoverAt: timestamp('cutover_at', { withTimezone: true }),
  cutoverBy: uuid('cutover_by'),
});

export const migrationRecord = pgTable(
  'migration_record',
  {
    id: id(),
    tenantId: tenantId(),
    batchId: uuid('batch_id').notNull(),
    rowNo: integer('row_no').notNull(),
    raw: jsonb('raw').notNull(),
    status: text('status', { enum: ['VALID', 'EXCEPTION', 'SKIPPED', 'LOADED'] })
      .notNull()
      .default('VALID'),
    issues: jsonb('issues').notNull().default([]),
    warnings: jsonb('warnings').notNull().default([]),
    reviewedBy: uuid('reviewed_by'),
    reviewedAt: timestamp('reviewed_at', { withTimezone: true }),
    reviewNote: text('review_note'),
    requestId: uuid('request_id'),
    contractId: uuid('contract_id'),
  },
  (t) => [uniqueIndex('migration_row_uq').on(t.batchId, t.rowNo)],
);

export const userMfa = pgTable('user_mfa', {
  userId: uuid('user_id').primaryKey(),
  tenantId: tenantId(),
  secret: text('secret').notNull(),
  confirmed: boolean('confirmed').notNull().default(false),
  lastStep: bigint('last_step', { mode: 'number' }).notNull().default(0),
  createdAt: created(),
});

export const outboundEmail = pgTable('outbound_email', {
  id: id(),
  tenantId: tenantId(),
  toEmail: text('to_email').notNull(),
  subject: text('subject').notNull(),
  body: text('body').notNull(),
  kind: text('kind').notNull(),
  refType: text('ref_type'),
  refId: uuid('ref_id'),
  status: text('status').notNull().default('SIMULATED'),
  createdAt: created(),
});

export const latePermission = pgTable('late_permission', {
  id: id(),
  tenantId: tenantId(),
  tenderId: uuid('tender_id').notNull(),
  supplierId: uuid('supplier_id').notNull(),
  reason: text('reason').notNull(),
  expiresAt: timestamp('expires_at', { withTimezone: true }).notNull(),
  grantedBy: uuid('granted_by').notNull(),
  createdAt: created(),
  revokedAt: timestamp('revoked_at', { withTimezone: true }),
});

export const publicNotice = pgTable(
  'public_notice',
  {
    id: id(),
    tenantId: tenantId(),
    tenderId: uuid('tender_id').notNull(),
    register: text('register').notNull(),
    reference: text('reference').notNull(),
    status: text('status').notNull().default('SIMULATED'),
    createdAt: created(),
  },
  (t) => [uniqueIndex('public_notice_once').on(t.tenderId, t.register)],
);

export const tenderDeviation = pgTable('tender_deviation', {
  id: id(),
  tenantId: tenantId(),
  tenderId: uuid('tender_id').notNull(),
  supplierId: uuid('supplier_id').notNull(),
  clauseRef: text('clause_ref').notNull(),
  proposal: text('proposal').notNull(),
  reason: text('reason'),
  risk: text('risk', { enum: ['LOW', 'MEDIUM', 'HIGH'] }),
  legalComment: text('legal_comment'),
  status: text('status', { enum: ['PROPOSED', 'ACCEPTABLE', 'NEGOTIATE', 'REJECTED'] })
    .notNull()
    .default('PROPOSED'),
  decidedBy: uuid('decided_by'),
  decidedAt: timestamp('decided_at', { withTimezone: true }),
  createdAt: created(),
});

// ---------------------------------------------------------------- B3: evaluation and report
export const complianceCheck = pgTable(
  'compliance_check',
  {
    id: id(),
    tenantId: tenantId(),
    evaluationId: uuid('evaluation_id').notNull(),
    supplierId: uuid('supplier_id').notNull(),
    checkKey: text('check_key').notNull(),
    result: text('result', { enum: ['PASS', 'FAIL', 'WAIVED'] }).notNull(),
    detail: text('detail').notNull(),
    decidedBy: uuid('decided_by'),
    decidedNote: text('decided_note'),
    decidedAt: timestamp('decided_at', { withTimezone: true }),
    createdAt: created(),
  },
  (t) => [uniqueIndex('compliance_check_uq').on(t.evaluationId, t.supplierId, t.checkKey)],
);

export const clarification = pgTable('clarification', {
  id: id(),
  tenantId: tenantId(),
  evaluationId: uuid('evaluation_id').notNull(),
  supplierId: uuid('supplier_id').notNull(),
  kind: text('kind', { enum: ['COMPLIANCE', 'CLARIFICATION', 'NEGOTIATION'] }).notNull(),
  subject: text('subject').notNull(),
  question: text('question').notNull(),
  checkKey: text('check_key'),
  dueAt: timestamp('due_at', { withTimezone: true }).notNull(),
  status: text('status', { enum: ['OPEN', 'ANSWERED', 'CLOSED'] })
    .notNull()
    .default('OPEN'),
  response: text('response'),
  respondedBy: uuid('responded_by'),
  respondedAt: timestamp('responded_at', { withTimezone: true }),
  createdBy: uuid('created_by'),
  createdAt: created(),
});

export const bidPricing = pgTable(
  'bid_pricing',
  {
    id: id(),
    tenantId: tenantId(),
    submissionId: uuid('submission_id').notNull(),
    basePrice: numeric('base_price', { precision: 14, scale: 2 }).notNull(),
    implementation: numeric('implementation', { precision: 14, scale: 2 }).notNull().default('0'),
    annualRunning: numeric('annual_running', { precision: 14, scale: 2 }).notNull().default('0'),
    years: integer('years').notNull().default(1),
    tco: numeric('tco', { precision: 14, scale: 2 }).notNull(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [uniqueIndex('bid_pricing_uq').on(t.submissionId)],
);

export const bafoRound = pgTable(
  'bafo_round',
  {
    id: id(),
    tenantId: tenantId(),
    evaluationId: uuid('evaluation_id').notNull(),
    round: integer('round').notNull(),
    status: text('status', { enum: ['OPEN', 'CLOSED'] })
      .notNull()
      .default('OPEN'),
    note: text('note').notNull(),
    closesAt: timestamp('closes_at', { withTimezone: true }).notNull(),
    invited: jsonb('invited').notNull().default([]),
    createdBy: uuid('created_by'),
    createdAt: created(),
    closedAt: timestamp('closed_at', { withTimezone: true }),
  },
  (t) => [uniqueIndex('bafo_round_uq').on(t.evaluationId, t.round)],
);

export const bafoOffer = pgTable(
  'bafo_offer',
  {
    id: id(),
    tenantId: tenantId(),
    roundId: uuid('round_id').notNull(),
    supplierId: uuid('supplier_id').notNull(),
    revision: integer('revision').notNull(),
    basePrice: numeric('base_price', { precision: 14, scale: 2 }).notNull(),
    implementation: numeric('implementation', { precision: 14, scale: 2 }).notNull().default('0'),
    annualRunning: numeric('annual_running', { precision: 14, scale: 2 }).notNull().default('0'),
    years: integer('years').notNull().default(1),
    tco: numeric('tco', { precision: 14, scale: 2 }).notNull(),
    note: text('note'),
    submittedAt: timestamp('submitted_at', { withTimezone: true }).notNull(),
    accepted: boolean('accepted').notNull().default(false),
    acceptedBy: uuid('accepted_by'),
    acceptedAt: timestamp('accepted_at', { withTimezone: true }),
  },
  (t) => [uniqueIndex('bafo_offer_uq').on(t.roundId, t.supplierId, t.revision)],
);

export const panelSubstitution = pgTable('panel_substitution', {
  id: id(),
  tenantId: tenantId(),
  evaluationId: uuid('evaluation_id').notNull(),
  departingUserId: uuid('departing_user_id').notNull(),
  incomingUserId: uuid('incoming_user_id').notNull(),
  stream: text('stream').notNull(),
  reason: text('reason', { enum: ['CONFLICT', 'OTHER'] }).notNull(),
  note: text('note'),
  byUserId: uuid('by_user_id').notNull(),
  createdAt: created(),
});

export const probityAllocation = pgTable(
  'probity_allocation',
  {
    id: id(),
    tenantId: tenantId(),
    userId: uuid('user_id').notNull(),
    tenderId: uuid('tender_id').notNull(),
    createdBy: uuid('created_by'),
    createdAt: created(),
  },
  (t) => [uniqueIndex('probity_allocation_uq').on(t.userId, t.tenderId)],
);

export const probityDocument = pgTable(
  'probity_document',
  {
    id: id(),
    tenantId: tenantId(),
    evaluationId: uuid('evaluation_id').notNull(),
    kind: text('kind', { enum: ['PLAN', 'OUTCOMES'] }).notNull(),
    title: text('title').notNull(),
    body: text('body').notNull().default(''),
    fileName: text('file_name'),
    fileKey: text('file_key'),
    fileSha256: text('file_sha256'),
    contentType: text('content_type'),
    status: text('status', { enum: ['DRAFT', 'SIGNED'] })
      .notNull()
      .default('DRAFT'),
    version: integer('version').notNull().default(1),
    signedBy: uuid('signed_by'),
    signedAt: timestamp('signed_at', { withTimezone: true }),
    stamp: text('stamp'),
    createdBy: uuid('created_by'),
    updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [uniqueIndex('probity_document_uq').on(t.evaluationId, t.kind)],
);

// ---------------------------------------------------------------- B4: contract award and legal
export const contractCheck = pgTable(
  'contract_check',
  {
    id: id(),
    tenantId: tenantId(),
    contractId: uuid('contract_id').notNull(),
    kind: text('kind', { enum: ['TENDER_CONSISTENCY', 'VENDOR_PREFLIGHT', 'RECHECK'] }).notNull(),
    checkKey: text('check_key').notNull(),
    result: text('result', { enum: ['PASS', 'WARN', 'FAIL', 'REVIEWED'] }).notNull(),
    detail: text('detail').notNull(),
    reviewedBy: uuid('reviewed_by'),
    reviewNote: text('review_note'),
    reviewedAt: timestamp('reviewed_at', { withTimezone: true }),
    createdAt: created(),
  },
  (t) => [uniqueIndex('contract_check_uq').on(t.contractId, t.kind, t.checkKey)],
);

export const contractEndorsement = pgTable(
  'contract_endorsement',
  {
    id: id(),
    tenantId: tenantId(),
    contractId: uuid('contract_id').notNull(),
    role: text('role').notNull(),
    userId: uuid('user_id').notNull(),
    comment: text('comment'),
    decidedAt: timestamp('decided_at', { withTimezone: true }).notNull(),
  },
  (t) => [uniqueIndex('contract_endorsement_uq').on(t.contractId, t.role)],
);

export const signingInvitation = pgTable('signing_invitation', {
  id: id(),
  tenantId: tenantId(),
  contractId: uuid('contract_id').notNull(),
  userId: uuid('user_id'),
  supplierId: uuid('supplier_id'),
  email: text('email').notNull(),
  name: text('name').notNull(),
  roleLabel: text('role_label').notNull(),
  invitedAt: timestamp('invited_at', { withTimezone: true }).notNull(),
  remindedAt: timestamp('reminded_at', { withTimezone: true }),
  reminderCount: integer('reminder_count').notNull().default(0),
  viewedAt: timestamp('viewed_at', { withTimezone: true }),
});

export const contractQuestion = pgTable('contract_question', {
  id: id(),
  tenantId: tenantId(),
  contractId: uuid('contract_id').notNull(),
  askedBy: uuid('asked_by').notNull(),
  side: text('side', { enum: ['INTERNAL', 'SUPPLIER'] }).notNull(),
  clauseId: text('clause_id'),
  question: text('question').notNull(),
  answer: text('answer'),
  answeredBy: uuid('answered_by'),
  answeredAt: timestamp('answered_at', { withTimezone: true }),
  createdAt: created(),
});

export const contractComment = pgTable('contract_comment', {
  id: id(),
  tenantId: tenantId(),
  contractId: uuid('contract_id').notNull(),
  clauseId: text('clause_id'),
  userId: uuid('user_id').notNull(),
  body: text('body').notNull(),
  createdAt: created(),
});

export const contractFile = pgTable('contract_file', {
  id: id(),
  tenantId: tenantId(),
  contractId: uuid('contract_id').notNull(),
  kind: text('kind', { enum: ['AMENDED_DRAFT'] }).notNull(),
  name: text('name').notNull(),
  sizeBytes: integer('size_bytes').notNull(),
  contentType: text('content_type').notNull(),
  storageKey: text('storage_key').notNull(),
  sha256: text('sha256').notNull(),
  version: integer('version').notNull(),
  note: text('note'),
  uploadedBy: uuid('uploaded_by').notNull(),
  createdAt: created(),
});

export const legalKnowledge = pgTable('legal_knowledge', {
  id: id(),
  tenantId: tenantId(),
  kind: text('kind', { enum: ['POLICY', 'ADVICE', 'FALLBACK', 'BOILERPLATE'] }).notNull(),
  title: text('title').notNull(),
  body: text('body').notNull(),
  clauseId: text('clause_id'),
  tags: text('tags').notNull().default(''),
  createdBy: uuid('created_by').notNull(),
  createdAt: created(),
});

export const legalMatter = pgTable('legal_matter', {
  id: id(),
  tenantId: tenantId(),
  title: text('title').notNull(),
  contractId: uuid('contract_id'),
  lane: text('lane', { enum: ['NEW', 'IN_REVIEW', 'WAITING', 'DONE'] })
    .notNull()
    .default('NEW'),
  priority: text('priority', { enum: ['LOW', 'NORMAL', 'HIGH'] })
    .notNull()
    .default('NORMAL'),
  assigneeId: uuid('assignee_id'),
  dueOn: date('due_on'),
  /** The matter's reference in the customer's own legal platform, and the stage that platform last reported (FR-0390). */
  externalRef: text('external_ref'),
  externalStage: text('external_stage'),
  createdBy: uuid('created_by').notNull(),
  createdAt: created(),
  updatedAt: updated(),
});

export const legalTimeEntry = pgTable('legal_time_entry', {
  id: id(),
  tenantId: tenantId(),
  matterId: uuid('matter_id').notNull(),
  userId: uuid('user_id').notNull(),
  hours: numeric('hours', { precision: 5, scale: 2 }).notNull(),
  workDate: date('work_date').notNull(),
  note: text('note'),
  createdAt: created(),
});

export const contractRiskSummary = pgTable(
  'contract_risk_summary',
  {
    id: id(),
    tenantId: tenantId(),
    contractId: uuid('contract_id').notNull(),
    generated: jsonb('generated').notNull(),
    edited: text('edited'),
    generatedAt: timestamp('generated_at', { withTimezone: true }).notNull(),
    reviewedBy: uuid('reviewed_by'),
    reviewedAt: timestamp('reviewed_at', { withTimezone: true }),
  },
  (t) => [uniqueIndex('contract_risk_summary_uq').on(t.contractId)],
);

export const accessGrant = pgTable('access_grant', {
  id: id(),
  tenantId: tenantId(),
  userId: uuid('user_id').notNull(),
  tenderId: uuid('tender_id').notNull(),
  label: text('label', { enum: ['COMMITTEE', 'AUDITOR', 'ADVISOR'] }).notNull(),
  expiresOn: date('expires_on'),
  event: text('event', { enum: ['CONTRACT_SIGNED', 'REPORT_APPROVED'] }),
  eventDays: integer('event_days').notNull().default(0),
  createdBy: uuid('created_by').notNull(),
  createdAt: created(),
  revokedAt: timestamp('revoked_at', { withTimezone: true }),
  revokedReason: text('revoked_reason'),
});

// ---------------------------------------------------------------- B5: contract management
export const alertPreference = pgTable('alert_preference', {
  userId: uuid('user_id').primaryKey(),
  tenantId: tenantId(),
  muted: jsonb('muted').notNull().default([]),
  updatedAt: updated(),
});

export const contractRate = pgTable(
  'contract_rate',
  {
    id: id(),
    tenantId: tenantId(),
    contractId: uuid('contract_id').notNull(),
    item: text('item').notNull(),
    unit: text('unit').notNull().default('each'),
    unitPrice: numeric('unit_price', { precision: 14, scale: 4 }).notNull(),
  },
  (t) => [uniqueIndex('contract_rate_uq').on(t.contractId, t.item)],
);

export const contractEscalation = pgTable('contract_escalation', {
  id: id(),
  tenantId: tenantId(),
  contractId: uuid('contract_id').notNull(),
  kind: text('kind', { enum: ['CPI', 'SCHEDULED'] }).notNull(),
  effectiveOn: date('effective_on').notNull(),
  pct: numeric('pct', { precision: 7, scale: 3 }).notNull(),
  capPct: numeric('cap_pct', { precision: 7, scale: 3 }),
  note: text('note'),
  createdBy: uuid('created_by').notNull(),
  createdAt: created(),
});

export const contractRebate = pgTable('contract_rebate', {
  id: id(),
  tenantId: tenantId(),
  contractId: uuid('contract_id').notNull(),
  title: text('title').notNull(),
  threshold: numeric('threshold', { precision: 14, scale: 2 }).notNull(),
  ratePct: numeric('rate_pct', { precision: 7, scale: 3 }).notNull(),
  periodStart: date('period_start').notNull(),
  periodEnd: date('period_end').notNull(),
  claimed: numeric('claimed', { precision: 14, scale: 2 }).notNull().default('0'),
  claimedOn: date('claimed_on'),
  followedUpAt: timestamp('followed_up_at', { withTimezone: true }),
  createdBy: uuid('created_by').notNull(),
  createdAt: created(),
});

export const workOrder = pgTable(
  'work_order',
  {
    id: id(),
    tenantId: tenantId(),
    masterId: uuid('master_id').notNull(),
    number: text('number').notNull(),
    title: text('title').notNull(),
    value: numeric('value', { precision: 14, scale: 2 }).notNull(),
    startDate: date('start_date').notNull(),
    endDate: date('end_date').notNull(),
    status: text('status', { enum: ['OPEN', 'COMPLETE', 'CANCELLED'] })
      .notNull()
      .default('OPEN'),
    createdBy: uuid('created_by').notNull(),
    createdAt: created(),
  },
  (t) => [uniqueIndex('work_order_uq').on(t.tenantId, t.number)],
);

export const purchaseOrder = pgTable(
  'purchase_order',
  {
    id: id(),
    tenantId: tenantId(),
    contractId: uuid('contract_id').notNull(),
    workOrderId: uuid('work_order_id'),
    number: text('number').notNull(),
    description: text('description').notNull(),
    amount: numeric('amount', { precision: 14, scale: 2 }).notNull(),
    lines: jsonb('lines').notNull().default([]),
    status: text('status', { enum: ['APPROVED', 'BLOCKED'] }).notNull(),
    blockedReason: text('blocked_reason'),
    createdBy: uuid('created_by').notNull(),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull(),
  },
  (t) => [uniqueIndex('purchase_order_uq').on(t.tenantId, t.number)],
);

export const invoice = pgTable(
  'invoice',
  {
    id: id(),
    tenantId: tenantId(),
    contractId: uuid('contract_id').notNull(),
    workOrderId: uuid('work_order_id'),
    poId: uuid('po_id'),
    number: text('number').notNull(),
    invoiceDate: date('invoice_date').notNull(),
    amount: numeric('amount', { precision: 14, scale: 2 }).notNull(),
    lines: jsonb('lines').notNull().default([]),
    status: text('status', { enum: ['MATCHED', 'BLOCKED', 'EXCEPTION', 'PAID'] }).notNull(),
    findings: jsonb('findings').notNull().default([]),
    overrideBy: uuid('override_by'),
    overrideReason: text('override_reason'),
    paidAmount: numeric('paid_amount', { precision: 14, scale: 2 }).notNull().default('0'),
    paidOn: date('paid_on'),
    createdBy: uuid('created_by').notNull(),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull(),
  },
  (t) => [uniqueIndex('invoice_uq').on(t.tenantId, t.number)],
);

export const contractHold = pgTable('contract_hold', {
  id: id(),
  tenantId: tenantId(),
  contractId: uuid('contract_id').notNull(),
  kind: text('kind', { enum: ['INSURANCE'] }).notNull(),
  reason: text('reason').notNull(),
  placedAt: timestamp('placed_at', { withTimezone: true }).notNull(),
  releasedAt: timestamp('released_at', { withTimezone: true }),
  releaseNote: text('release_note'),
});

export const spendAlert = pgTable(
  'spend_alert',
  {
    id: id(),
    tenantId: tenantId(),
    contractId: uuid('contract_id').notNull(),
    kind: text('kind', { enum: ['MANDATORY', 'CONFIGURED'] }).notNull(),
    threshold: integer('threshold').notNull(),
    spentPct: numeric('spent_pct', { precision: 9, scale: 2 }).notNull(),
    raisedAt: timestamp('raised_at', { withTimezone: true }).notNull(),
  },
  (t) => [uniqueIndex('spend_alert_uq').on(t.contractId, t.kind, t.threshold)],
);

export const contractPlan = pgTable(
  'contract_plan',
  {
    id: id(),
    tenantId: tenantId(),
    contractId: uuid('contract_id').notNull(),
    kind: text('kind', { enum: ['CMP', 'RMP'] }).notNull(),
    tier: text('tier', { enum: ['STANDARD', 'ELEVATED', 'HIGH'] }).notNull(),
    template: text('template').notNull(),
    sections: jsonb('sections').notNull(),
    reasons: jsonb('reasons').notNull().default([]),
    generatedAt: timestamp('generated_at', { withTimezone: true }).notNull(),
    generatedBy: uuid('generated_by'),
  },
  (t) => [uniqueIndex('contract_plan_uq').on(t.contractId, t.kind)],
);

export const contractActivity = pgTable('contract_activity', {
  id: id(),
  tenantId: tenantId(),
  contractId: uuid('contract_id').notNull(),
  planKind: text('plan_kind', { enum: ['CMP', 'RMP'] }).notNull(),
  title: text('title').notNull(),
  dueDate: date('due_date').notNull(),
  ownerId: uuid('owner_id'),
  status: text('status', { enum: ['OPEN', 'DONE'] })
    .notNull()
    .default('OPEN'),
  doneAt: timestamp('done_at', { withTimezone: true }),
  doneBy: uuid('done_by'),
  note: text('note'),
});

export const fundingEnvelope = pgTable('funding_envelope', {
  id: id(),
  tenantId: tenantId(),
  name: text('name').notNull(),
  amount: numeric('amount', { precision: 14, scale: 2 }).notNull(),
  holderId: uuid('holder_id').notNull(),
  nominees: jsonb('nominees').notNull().default([]),
  warnPct: integer('warn_pct').notNull().default(80),
  warnedAt: timestamp('warned_at', { withTimezone: true }),
  status: text('status', { enum: ['ACTIVE', 'CLOSED'] })
    .notNull()
    .default('ACTIVE'),
  approvedBy: uuid('approved_by').notNull(),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull(),
});

export const envelopeCommitment = pgTable('envelope_commitment', {
  id: id(),
  tenantId: tenantId(),
  envelopeId: uuid('envelope_id').notNull(),
  contractId: uuid('contract_id'),
  description: text('description').notNull(),
  amount: numeric('amount', { precision: 14, scale: 2 }).notNull(),
  approvedBy: uuid('approved_by').notNull(),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull(),
});

export const disclosureTask = pgTable(
  'disclosure_task',
  {
    id: id(),
    tenantId: tenantId(),
    contractId: uuid('contract_id').notNull(),
    register: text('register').notNull(),
    variancePct: numeric('variance_pct', { precision: 9, scale: 2 }).notNull(),
    dueOn: date('due_on').notNull(),
    status: text('status', { enum: ['OPEN', 'DONE'] })
      .notNull()
      .default('OPEN'),
    reference: text('reference'),
    doneBy: uuid('done_by'),
    doneAt: timestamp('done_at', { withTimezone: true }),
    /** Set once when the task is overdue and has been escalated to the executive (NFR-L02). */
    escalatedAt: timestamp('escalated_at', { withTimezone: true }),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull(),
  },
  (t) => [uniqueIndex('disclosure_task_uq').on(t.contractId)],
);

// ---------------------------------------------------------------- B6: reporting and collaboration
export const layoutTemplate = pgTable(
  'layout_template',
  {
    id: id(),
    tenantId: tenantId(),
    kind: text('kind', { enum: ['PLAN', 'RFX', 'REPORT', 'INTAKE', 'CONTRACT'] }).notNull(),
    name: text('name').notNull(),
    sections: jsonb('sections').notNull(),
    updatedBy: uuid('updated_by').notNull(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).notNull(),
  },
  (t) => [uniqueIndex('layout_template_uq').on(t.tenantId, t.kind)],
);

export const scheduleItem = pgTable(
  'schedule_item',
  {
    id: id(),
    tenantId: tenantId(),
    requestId: uuid('request_id').notNull(),
    phase: text('phase', { enum: ['INTAKE', 'PLAN', 'TENDER', 'EVALUATION', 'CONTRACT_AWARD'] }).notNull(),
    startDate: date('start_date').notNull(),
    endDate: date('end_date').notNull(),
  },
  (t) => [uniqueIndex('schedule_item_uq').on(t.requestId, t.phase)],
);

export const savedView = pgTable('saved_view', {
  id: id(),
  tenantId: tenantId(),
  userId: uuid('user_id').notNull(),
  name: text('name').notNull(),
  report: text('report').notNull(),
  filters: jsonb('filters').notNull().default({}),
  shared: boolean('shared').notNull().default(false),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull(),
});

export const riskAssessment = pgTable(
  'risk_assessment',
  {
    id: id(),
    tenantId: tenantId(),
    requestId: uuid('request_id').notNull(),
    basis: text('basis').notNull(),
    generatedAt: timestamp('generated_at', { withTimezone: true }).notNull(),
    generatedBy: uuid('generated_by').notNull(),
    completedAt: timestamp('completed_at', { withTimezone: true }),
  },
  (t) => [uniqueIndex('risk_assessment_uq').on(t.requestId)],
);

export const riskItem = pgTable(
  'risk_item',
  {
    id: id(),
    tenantId: tenantId(),
    assessmentId: uuid('assessment_id').notNull(),
    key: text('key').notNull(),
    title: text('title').notNull(),
    description: text('description').notNull(),
    applicable: boolean('applicable'),
    likelihood: integer('likelihood'),
    impact: integer('impact'),
    options: jsonb('options').notNull().default([]),
    mitigation: text('mitigation'),
  },
  (t) => [uniqueIndex('risk_item_uq').on(t.assessmentId, t.key)],
);

export const fieldHistory = pgTable(
  'field_history',
  {
    id: id(),
    tenantId: tenantId(),
    ownerType: text('owner_type').notNull(),
    ownerId: uuid('owner_id').notNull(),
    key: text('key').notNull(),
    value: text('value'),
    changedBy: uuid('changed_by'),
    source: text('source'),
    rev: integer('rev').notNull(),
    at: timestamp('at', { withTimezone: true }).notNull(),
  },
  (t) => [index('field_history_doc_idx').on(t.ownerType, t.ownerId, t.at)],
);

export const documentVersion = pgTable(
  'document_version',
  {
    id: id(),
    tenantId: tenantId(),
    ownerType: text('owner_type').notNull(),
    ownerId: uuid('owner_id').notNull(),
    number: integer('number').notNull(),
    label: text('label').notNull(),
    snapshot: jsonb('snapshot').notNull(),
    createdBy: uuid('created_by').notNull(),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull(),
  },
  (t) => [uniqueIndex('document_version_uq').on(t.ownerType, t.ownerId, t.number)],
);

export const documentView = pgTable(
  'document_view',
  {
    id: id(),
    tenantId: tenantId(),
    userId: uuid('user_id').notNull(),
    ownerType: text('owner_type').notNull(),
    ownerId: uuid('owner_id').notNull(),
    viewedAt: timestamp('viewed_at', { withTimezone: true }).notNull(),
  },
  (t) => [uniqueIndex('document_view_uq').on(t.userId, t.ownerType, t.ownerId)],
);

export const editPresence = pgTable(
  'edit_presence',
  {
    id: id(),
    tenantId: tenantId(),
    userId: uuid('user_id').notNull(),
    ownerType: text('owner_type').notNull(),
    ownerId: uuid('owner_id').notNull(),
    fieldKey: text('field_key'),
    at: timestamp('at', { withTimezone: true }).notNull(),
  },
  (t) => [uniqueIndex('edit_presence_uq').on(t.userId, t.ownerType, t.ownerId)],
);

export const referenceContent = pgTable('reference_content', {
  id: id(),
  tenantId: tenantId(),
  kind: text('kind').notNull(),
  title: text('title').notNull(),
  category: text('category').notNull(),
  sector: text('sector').notNull(),
  level: text('level').notNull(),
  body: text('body').notNull(),
  generation: integer('generation').notNull(),
  generatedAt: timestamp('generated_at', { withTimezone: true }).notNull(),
});

// ------------------------------------------------------------------ B8: tender, contract and supplier intelligence

export const responseItem = pgTable(
  'response_item',
  {
    id: id(),
    tenantId: tenantId(),
    tenderId: uuid('tender_id').notNull(),
    key: text('key').notNull(),
    label: text('label').notNull(),
    section: text('section', { enum: ['TECHNICAL', 'COMMERCIAL'] }).notNull(),
    kind: text('kind', { enum: ['TEXT', 'NUMBER', 'CHOICE', 'YESNO', 'DATE'] }).notNull(),
    required: boolean('required').notNull().default(true),
    options: jsonb('options').notNull().default([]),
    unit: text('unit'),
    maxLength: integer('max_length'),
    position: integer('position').notNull().default(0),
    createdAt: created(),
  },
  (t) => [uniqueIndex('response_item_uq').on(t.tenderId, t.key)],
);

export const responseAnswer = pgTable(
  'response_answer',
  {
    id: id(),
    tenantId: tenantId(),
    submissionId: uuid('submission_id').notNull(),
    itemKey: text('item_key').notNull(),
    value: text('value').notNull(),
    updatedAt: updated(),
  },
  (t) => [uniqueIndex('response_answer_uq').on(t.submissionId, t.itemKey)],
);

export const bidWitness = pgTable(
  'bid_witness',
  {
    id: id(),
    tenantId: tenantId(),
    tenderId: uuid('tender_id').notNull(),
    userId: uuid('user_id').notNull(),
    witnessedAt: timestamp('witnessed_at', { withTimezone: true }).notNull(),
  },
  (t) => [uniqueIndex('bid_witness_uq').on(t.tenderId, t.userId)],
);

/** Everything that leaves the platform for another system, kept so a failed delivery can be retried (FR-0390, NFR-AV03). */
export const integrationEvent = pgTable(
  'integration_event',
  {
    id: id(),
    tenantId: tenantId(),
    kind: text('kind').notNull(),
    target: text('target').notNull(),
    idempotencyKey: text('idempotency_key').notNull(),
    payload: jsonb('payload').notNull().default({}),
    status: text('status', { enum: ['PENDING', 'DELIVERED', 'FAILED', 'DEAD_LETTER'] })
      .notNull()
      .default('PENDING'),
    attempts: integer('attempts').notNull().default(0),
    lastError: text('last_error'),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull(),
    deliveredAt: timestamp('delivered_at', { withTimezone: true }),
    /** Which connector it belongs to, which way it travels, when to try again and when the other side acknowledged it (NFR-AV03). */
    connectorKind: text('connector_kind'),
    direction: text('direction', { enum: ['OUT', 'IN'] })
      .notNull()
      .default('OUT'),
    nextAttemptAt: timestamp('next_attempt_at', { withTimezone: true }),
    remoteAckAt: timestamp('remote_ack_at', { withTimezone: true }),
  },
  (t) => [uniqueIndex('integration_event_uq').on(t.tenantId, t.idempotencyKey)],
);

export const legalRedline = pgTable('legal_redline', {
  id: id(),
  tenantId: tenantId(),
  contractId: uuid('contract_id').notNull(),
  clauseId: text('clause_id').notNull(),
  proposedText: text('proposed_text').notNull(),
  source: text('source', { enum: ['INTERNAL', 'LEGAL_PLATFORM', 'EXTERNAL_COUNSEL', 'SUPPLIER'] }).notNull(),
  author: text('author').notNull(),
  status: text('status', { enum: ['PROPOSED', 'ACCEPTED', 'REJECTED'] })
    .notNull()
    .default('PROPOSED'),
  decidedBy: uuid('decided_by'),
  decidedAt: timestamp('decided_at', { withTimezone: true }),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull(),
});

export const supplierRating = pgTable(
  'supplier_rating',
  {
    id: id(),
    tenantId: tenantId(),
    supplierId: uuid('supplier_id').notNull(),
    contractId: uuid('contract_id').notNull(),
    direction: text('direction', {
      enum: ['ENTERPRISE_RATES_SUPPLIER', 'SUPPLIER_RATES_ENTERPRISE'],
    }).notNull(),
    raterId: uuid('rater_id').notNull(),
    scores: jsonb('scores').notNull(),
    overall: numeric('overall', { precision: 3, scale: 2 }).notNull(),
    comment: text('comment'),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull(),
  },
  (t) => [uniqueIndex('supplier_rating_uq').on(t.contractId, t.direction, t.raterId)],
);

export const duplicateDismissal = pgTable(
  'duplicate_dismissal',
  {
    id: id(),
    tenantId: tenantId(),
    supplierA: uuid('supplier_a').notNull(),
    supplierB: uuid('supplier_b').notNull(),
    userId: uuid('user_id').notNull(),
    reason: text('reason').notNull(),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull(),
  },
  (t) => [uniqueIndex('duplicate_dismissal_uq').on(t.supplierA, t.supplierB)],
);

export const lesson = pgTable('lesson', {
  id: id(),
  tenantId: tenantId(),
  requestId: uuid('request_id').notNull(),
  authorId: uuid('author_id').notNull(),
  phase: text('phase').notNull(),
  kind: text('kind', { enum: ['WENT_WELL', 'TO_IMPROVE', 'RISK', 'TIP'] }).notNull(),
  text: text('text').notNull(),
  category: text('category'),
  value: numeric('value', { precision: 14, scale: 2 }),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull(),
});

/** A one-time link that lets an approver decide one thing without a full sign-in (NFR-U05). Only the hash is kept. */
export const approvalLink = pgTable('approval_link', {
  id: id(),
  tenantId: tenantId(),
  tokenHash: text('token_hash').notNull().unique(),
  userId: uuid('user_id').notNull(),
  subjectType: text('subject_type', { enum: ['PLAN', 'EVAL_REPORT'] }).notNull(),
  subjectId: uuid('subject_id').notNull(),
  expiresAt: timestamp('expires_at', { withTimezone: true }).notNull(),
  usedAt: timestamp('used_at', { withTimezone: true }),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull(),
});

/** A one-time link that lets an outside law firm or a supplier's legal team mark up one contract (FR-0830). Only the hash is kept. */
export const counselLink = pgTable('counsel_link', {
  id: id(),
  tenantId: tenantId(),
  contractId: uuid('contract_id').notNull(),
  tokenHash: text('token_hash').notNull().unique(),
  name: text('name').notNull(),
  email: text('email').notNull(),
  party: text('party', { enum: ['EXTERNAL_COUNSEL', 'SUPPLIER'] }).notNull(),
  expiresAt: timestamp('expires_at', { withTimezone: true }).notNull(),
  revokedAt: timestamp('revoked_at', { withTimezone: true }),
  createdBy: uuid('created_by').notNull(),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull(),
});

// ------------------------------------------------------------------ B9: planning, spend and experience

export const fxRate = pgTable(
  'fx_rate',
  {
    id: id(),
    tenantId: tenantId(),
    currency: text('currency').notNull(),
    rate: numeric('rate', { precision: 18, scale: 8 }).notNull(),
    asOf: date('as_of').notNull(),
    source: text('source', { enum: ['ANNUAL', 'LIVE', 'MANUAL'] }).notNull(),
    createdBy: uuid('created_by'),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull(),
  },
  (t) => [uniqueIndex('fx_rate_uq').on(t.tenantId, t.currency, t.asOf)],
);

export const catalogueItem = pgTable(
  'catalogue_item',
  {
    id: id(),
    tenantId: tenantId(),
    supplierId: uuid('supplier_id').notNull(),
    contractId: uuid('contract_id'),
    sku: text('sku').notNull(),
    name: text('name').notNull(),
    category: text('category').notNull(),
    unit: text('unit').notNull().default('each'),
    unitPrice: numeric('unit_price', { precision: 14, scale: 4 }).notNull(),
    leadDays: integer('lead_days').notNull().default(0),
    active: boolean('active').notNull().default(true),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull(),
  },
  (t) => [uniqueIndex('catalogue_item_uq').on(t.tenantId, t.supplierId, t.sku)],
);

export const sourcingProposal = pgTable('sourcing_proposal', {
  id: id(),
  tenantId: tenantId(),
  requesterId: uuid('requester_id').notNull(),
  need: text('need').notNull(),
  category: text('category'),
  quantity: numeric('quantity', { precision: 14, scale: 2 }).notNull(),
  status: text('status', { enum: ['PROPOSED', 'APPROVED', 'REJECTED', 'ORDERED', 'NO_MATCH'] })
    .notNull()
    .default('PROPOSED'),
  shortlist: jsonb('shortlist').notNull().default([]),
  recommendedItemId: uuid('recommended_item_id'),
  total: numeric('total', { precision: 14, scale: 2 }),
  requestId: uuid('request_id'),
  decidedBy: uuid('decided_by'),
  decidedAt: timestamp('decided_at', { withTimezone: true }),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull(),
});

export const reviewNote = pgTable('review_note', {
  id: id(),
  tenantId: tenantId(),
  authorId: uuid('author_id').notNull(),
  supplierId: uuid('supplier_id').notNull(),
  tenderId: uuid('tender_id'),
  text: text('text').notNull(),
  visibility: text('visibility', { enum: ['PRIVATE', 'TEAM'] })
    .notNull()
    .default('PRIVATE'),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull(),
});

export const userDashboard = pgTable('user_dashboard', {
  userId: uuid('user_id').primaryKey(),
  tenantId: tenantId(),
  widgets: jsonb('widgets').notNull(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull(),
});

export const grcItem = pgTable(
  'grc_item',
  {
    id: id(),
    tenantId: tenantId(),
    kind: text('kind', { enum: ['RISK', 'AUDIT_FINDING', 'OBLIGATION'] }).notNull(),
    title: text('title').notNull(),
    description: text('description'),
    ownerId: uuid('owner_id'),
    likelihood: integer('likelihood'),
    impact: integer('impact'),
    rating: integer('rating'),
    status: text('status', { enum: ['OPEN', 'IN_PROGRESS', 'MITIGATED', 'ACCEPTED', 'CLOSED'] })
      .notNull()
      .default('OPEN'),
    dueOn: date('due_on'),
    reviewOn: date('review_on'),
    source: text('source', { enum: ['MANUAL', 'PLATFORM'] })
      .notNull()
      .default('MANUAL'),
    sourceKey: text('source_key'),
    linkedType: text('linked_type'),
    linkedId: uuid('linked_id'),
    treatment: text('treatment'),
    actions: jsonb('actions').notNull().default([]),
    createdBy: uuid('created_by'),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).notNull(),
    closedAt: timestamp('closed_at', { withTimezone: true }),
  },
  (t) => [
    uniqueIndex('grc_item_source_uq')
      .on(t.tenantId, t.sourceKey)
      .where(sql`source_key IS NOT NULL`),
  ],
);

export const artefactState = pgTable(
  'artefact_state',
  {
    id: id(),
    tenantId: tenantId(),
    kind: text('kind', { enum: ['EVAL_REPORT', 'CONTRACT_PLANS'] }).notNull(),
    subjectId: uuid('subject_id').notNull(),
    stale: boolean('stale').notNull().default(true),
    reason: text('reason'),
    changedAt: timestamp('changed_at', { withTimezone: true }).notNull(),
    refreshedAt: timestamp('refreshed_at', { withTimezone: true }),
    refreshCount: integer('refresh_count').notNull().default(0),
  },
  (t) => [uniqueIndex('artefact_state_uq').on(t.kind, t.subjectId)],
);

export const externalSearchLog = pgTable('external_search_log', {
  id: id(),
  tenantId: tenantId(),
  userId: uuid('user_id').notNull(),
  querySent: text('query_sent').notNull(),
  provider: text('provider').notNull(),
  withheld: jsonb('withheld').notNull().default([]),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull(),
});
export * from './schema-b10d.js';
export * from './schema-b10a.js';
export * from './schema-b10c.js';
export * from './schema-b10b.js';
export * from './schema-b11a.js';
export * from './schema-b11d.js';
export * from './schema-b11b.js';
export * from './schema-b11c.js';
export * from './schema-cpd.js';
export * from './schema-cpb.js';
export * from './schema-cpa.js';
export * from './schema-cpc.js';
