/**
 * Drizzle schema = single source for TypeScript types. DDL is generated by drizzle-kit into ./migrations,
 * then hand-written migrations add what Drizzle cannot express (roles, grants, RLS, append-only audit).
 * Every business table is tenant-scoped (`tenant_id`). See Technical Specification section 3.2.
 */
import { sql } from 'drizzle-orm';
import {
  bigint,
  bigserial,
  boolean,
  index,
  integer,
  jsonb,
  numeric,
  pgTable,
  text,
  timestamp,
  uniqueIndex,
  uuid,
  date,
} from 'drizzle-orm/pg-core';

export const ROLES = [
  'REQUESTER',
  'PROCUREMENT',
  'DELEGATE',
  'EVALUATOR',
  'CHAIR',
  'LEGAL',
  'CONTRACT_MGR',
  'PROBITY',
  'FINANCE',
  'ADMIN',
  'EXEC',
  'SUPPLIER',
] as const;
export type Role = (typeof ROLES)[number];

export const PHASES = [
  'INTAKE',
  'PLAN',
  'TENDER',
  'EVALUATION',
  'CONTRACT_AWARD',
  'CONTRACT_MGMT',
  'CLOSED',
] as const;

const id = () =>
  uuid('id')
    .primaryKey()
    .default(sql`gen_random_uuid()`);
const tenantId = () => uuid('tenant_id').notNull();
const created = () => timestamp('created_at', { withTimezone: true }).notNull().defaultNow();
const updated = () => timestamp('updated_at', { withTimezone: true }).notNull().defaultNow();
const version = () => integer('version').notNull().default(1);

export const tenant = pgTable('tenant', {
  id: id(),
  slug: text('slug').notNull().unique(),
  name: text('name').notNull(),
  region: text('region').notNull().default('ap-southeast-2'),
  sector: text('sector', { enum: ['PUBLIC', 'PRIVATE'] }).notNull(),
  config: jsonb('config').notNull().default({}),
  createdAt: created(),
});

export const orgUnit = pgTable('org_unit', {
  id: id(),
  tenantId: tenantId(),
  name: text('name').notNull(),
  parentId: uuid('parent_id'),
  createdAt: created(),
});

export const appUser = pgTable(
  'app_user',
  {
    id: id(),
    tenantId: tenantId(),
    email: text('email').notNull(),
    name: text('name').notNull(),
    orgUnitId: uuid('org_unit_id'),
    passwordHash: text('password_hash').notNull(),
    active: boolean('active').notNull().default(true),
    failedAttempts: integer('failed_attempts').notNull().default(0),
    lockedUntil: timestamp('locked_until', { withTimezone: true }),
    supplierId: uuid('supplier_id'),
    createdAt: created(),
    updatedAt: updated(),
  },
  (t) => [uniqueIndex('app_user_email_uq').on(t.tenantId, t.email)],
);

export const roleAssignment = pgTable(
  'role_assignment',
  {
    id: id(),
    tenantId: tenantId(),
    userId: uuid('user_id').notNull(),
    role: text('role', { enum: ROLES }).notNull(),
    division: text('division'),
    /** A time-bound grant ends here; the role then stops applying (SEC-A05). Null means it does not expire. */
    expiresAt: timestamp('expires_at', { withTimezone: true }),
    grantedBy: uuid('granted_by'),
  },
  (t) => [uniqueIndex('role_assignment_uq').on(t.userId, t.role)],
);

export const delegation = pgTable('delegation', {
  id: id(),
  tenantId: tenantId(),
  scope: text('scope', { enum: ['SOURCING_APPROVAL', 'CONTRACT_SIGNING', 'PUBLISH_PERMISSION'] }).notNull(),
  role: text('role', { enum: ROLES }).notNull(),
  userId: uuid('user_id'),
  maxValue: numeric('max_value', { precision: 14, scale: 2 }).notNull(),
  division: text('division'),
  active: boolean('active').notNull().default(true),
  createdAt: created(),
  updatedAt: updated(),
});

export const supplier = pgTable('supplier', {
  id: id(),
  tenantId: tenantId(),
  company: text('company').notNull(),
  abn: text('abn').notNull(),
  sanctionsStatus: text('sanctions_status', { enum: ['PENDING', 'CLEAR', 'MATCH'] })
    .notNull()
    .default('PENDING'),
  insuranceStatus: text('insurance_status', { enum: ['UNKNOWN', 'CURRENT', 'EXPIRING', 'EXPIRED'] })
    .notNull()
    .default('UNKNOWN'),
  lastCheckedAt: timestamp('last_checked_at', { withTimezone: true }),
  categories: jsonb('categories').notNull().default([]),
  createdAt: created(),
});

export const request = pgTable(
  'request',
  {
    id: id(),
    tenantId: tenantId(),
    number: text('number').notNull(),
    title: text('title').notNull(),
    category: text('category'),
    unspsc: text('unspsc'),
    estimatedValue: numeric('estimated_value', { precision: 14, scale: 2 }),
    currency: text('currency').notNull().default('AUD'),
    termMonths: integer('term_months'),
    businessUnit: text('business_unit'),
    requesterId: uuid('requester_id').notNull(),
    phase: text('phase', { enum: PHASES }).notNull().default('INTAKE'),
    status: text('status', { enum: ['DRAFT', 'SUBMITTED', 'IN_PROGRESS', 'BLOCKED', 'COMPLETE'] })
      .notNull()
      .default('DRAFT'),
    intakeMode: text('intake_mode', { enum: ['SELF_SERVICE', 'TEAM_LED'] })
      .notNull()
      .default('TEAM_LED'),
    complexity: text('complexity', { enum: ['LOW', 'MEDIUM', 'HIGH', 'CRITICAL'] }),
    budgetCheck: text('budget_check', { enum: ['NOT_RUN', 'CLEARED', 'EXCEEDED', 'UNAVAILABLE'] })
      .notNull()
      .default('NOT_RUN'),
    taxonomyScheme: text('taxonomy_scheme'),
    taxonomyCode: text('taxonomy_code'),
    taxonomyConfirmed: boolean('taxonomy_confirmed').notNull().default(false),
    workflowId: text('workflow_id'),
    subWorkflow: text('sub_workflow'),
    processSteps: jsonb('process_steps').notNull().default([]),
    processVariations: jsonb('process_variations').notNull().default([]),
    engagements: jsonb('engagements').notNull().default([]),
    nominatedDelegates: jsonb('nominated_delegates').notNull().default({}),
    ecv: jsonb('ecv'),
    sourceSystem: text('source_system'),
    createdAt: created(),
    updatedAt: updated(),
    version: version(),
  },
  (t) => [
    uniqueIndex('request_number_uq').on(t.tenantId, t.number),
    index('request_requester_idx').on(t.requesterId),
  ],
);

export const conversation = pgTable('conversation', {
  id: id(),
  tenantId: tenantId(),
  userId: uuid('user_id').notNull(),
  purpose: text('purpose').notNull(),
  contextId: uuid('context_id'),
  simulated: boolean('simulated').notNull().default(true),
  createdAt: created(),
});

export const chatMessage = pgTable('chat_message', {
  id: id(),
  tenantId: tenantId(),
  conversationId: uuid('conversation_id').notNull(),
  role: text('role', { enum: ['USER', 'ASSISTANT', 'SYSTEM'] }).notNull(),
  text: text('text').notNull(),
  proposedChanges: jsonb('proposed_changes'),
  createdAt: created(),
});

export const plan = pgTable('plan', {
  id: id(),
  tenantId: tenantId(),
  requestId: uuid('request_id').notNull().unique(),
  status: text('status', {
    enum: ['DRAFT', 'AWAITING_SIGNOFF', 'AWAITING_APPROVAL', 'APPROVED_LOCKED', 'REOPENED', 'REJECTED'],
  })
    .notNull()
    .default('DRAFT'),
  summary: text('summary'),
  locked: boolean('locked').notNull().default(false),
  createdAt: created(),
  updatedAt: updated(),
  version: version(),
});

export const fieldValue = pgTable(
  'field_value',
  {
    id: id(),
    tenantId: tenantId(),
    ownerType: text('owner_type', {
      enum: ['REQUEST', 'PLAN', 'TENDER', 'EVAL_REPORT', 'CONTRACT'],
    }).notNull(),
    ownerId: uuid('owner_id').notNull(),
    key: text('key').notNull(),
    label: text('label').notNull(),
    value: text('value'),
    source: text('source', { enum: ['USER', 'AI', 'SYSTEM', 'MIGRATED'] })
      .notNull()
      .default('USER'),
    aiDrafted: boolean('ai_drafted').notNull().default(false),
    missing: boolean('missing').notNull().default(false),
    previousValue: text('previous_value'),
    updatedBy: uuid('updated_by'),
    updatedAt: updated(),
  },
  (t) => [uniqueIndex('field_value_uq').on(t.ownerType, t.ownerId, t.key)],
);

export const approval = pgTable('approval', {
  id: id(),
  tenantId: tenantId(),
  subjectType: text('subject_type').notNull(),
  subjectId: uuid('subject_id').notNull(),
  userId: uuid('user_id').notNull(),
  role: text('role').notNull(),
  decision: text('decision', { enum: ['APPROVED', 'REJECTED', 'SUPERSEDED'] }).notNull(),
  comment: text('comment'),
  stamp: text('stamp'),
  decidedAt: timestamp('decided_at', { withTimezone: true }).notNull().defaultNow(),
});

export const coiDeclaration = pgTable('coi_declaration', {
  id: id(),
  tenantId: tenantId(),
  userId: uuid('user_id').notNull(),
  scope: text('scope', { enum: ['PLAN', 'EVALUATION'] }).notNull(),
  scopeId: uuid('scope_id').notNull(),
  none: boolean('none').notNull(),
  nature: text('nature'),
  subjectOrg: text('subject_org'),
  disposition: text('disposition', { enum: ['PENDING', 'IMMATERIAL', 'MANAGEABLE', 'MATERIAL'] })
    .notNull()
    .default('PENDING'),
  routedTo: uuid('routed_to'),
  decidedAt: timestamp('decided_at', { withTimezone: true }),
  createdAt: created(),
});

export const tender = pgTable('tender', {
  id: id(),
  tenantId: tenantId(),
  requestId: uuid('request_id').notNull(),
  type: text('type', { enum: ['RFT', 'RFP', 'RFQ', 'RFI', 'EOI'] }).notNull(),
  access: text('access', { enum: ['OPEN', 'CLOSED'] })
    .notNull()
    .default('CLOSED'),
  status: text('status', { enum: ['DRAFT', 'STAGED', 'PUBLISHED', 'CLOSED', 'EVALUATING', 'AWARDED'] })
    .notNull()
    .default('DRAFT'),
  opensAt: timestamp('opens_at', { withTimezone: true }),
  closesAt: timestamp('closes_at', { withTimezone: true }),
  publishPermissionId: uuid('publish_permission_id'),
  createdAt: created(),
  updatedAt: updated(),
  version: version(),
});

export const invitation = pgTable('invitation', {
  id: id(),
  tenantId: tenantId(),
  tenderId: uuid('tender_id').notNull(),
  email: text('email').notNull(),
  company: text('company').notNull(),
  tokenHash: text('token_hash').notNull(),
  expiresAt: timestamp('expires_at', { withTimezone: true }).notNull(),
  usedAt: timestamp('used_at', { withTimezone: true }),
  supplierId: uuid('supplier_id'),
});

export const question = pgTable('question', {
  id: id(),
  tenantId: tenantId(),
  tenderId: uuid('tender_id').notNull(),
  text: text('text').notNull(),
  answer: text('answer'),
  status: text('status', { enum: ['OPEN', 'ANSWERED', 'PUBLISHED'] })
    .notNull()
    .default('OPEN'),
  // Restricted column: never selected by any API serialiser (anonymity, FR-0135).
  askedBySupplierId: uuid('asked_by_supplier_id'),
  askedAt: timestamp('asked_at', { withTimezone: true }).notNull().defaultNow(),
});

export const addendum = pgTable('addendum', {
  id: id(),
  tenantId: tenantId(),
  tenderId: uuid('tender_id').notNull(),
  number: integer('number').notNull(),
  summary: text('summary').notNull(),
  questionIds: jsonb('question_ids').notNull().default([]),
  newClosesAt: timestamp('new_closes_at', { withTimezone: true }),
  issuedAt: timestamp('issued_at', { withTimezone: true }).notNull().defaultNow(),
});

export const submission = pgTable(
  'submission',
  {
    id: id(),
    tenantId: tenantId(),
    tenderId: uuid('tender_id').notNull(),
    supplierId: uuid('supplier_id').notNull(),
    status: text('status', { enum: ['DRAFT', 'SUBMITTED', 'REJECTED_LATE'] })
      .notNull()
      .default('DRAFT'),
    receipt: text('receipt'),
    submittedAt: timestamp('submitted_at', { withTimezone: true }),
    createdAt: created(),
  },
  (t) => [uniqueIndex('submission_uq').on(t.tenderId, t.supplierId)],
);

export const fileObject = pgTable('file_object', {
  id: id(),
  tenantId: tenantId(),
  submissionId: uuid('submission_id').notNull(),
  name: text('name').notNull(),
  sizeBytes: integer('size_bytes').notNull(),
  contentType: text('content_type').notNull(),
  storageKey: text('storage_key').notNull(),
  sha256: text('sha256'),
  scan: text('scan', { enum: ['PENDING', 'CLEAN', 'INFECTED'] })
    .notNull()
    .default('PENDING'),
  section: text('section', { enum: ['TECHNICAL', 'COMMERCIAL', 'OTHER'] })
    .notNull()
    .default('OTHER'),
  createdAt: created(),
});

export const evaluation = pgTable('evaluation', {
  id: id(),
  tenantId: tenantId(),
  tenderId: uuid('tender_id').notNull().unique(),
  status: text('status', { enum: ['COI_PENDING', 'SCORING', 'CONSENSUS', 'LOCKED', 'REPORTED', 'APPROVED'] })
    .notNull()
    .default('COI_PENDING'),
  varianceLimitPct: integer('variance_limit_pct').notNull().default(30),
  createdAt: created(),
  updatedAt: updated(),
  version: version(),
});

export const criterion = pgTable('criterion', {
  id: id(),
  tenantId: tenantId(),
  evaluationId: uuid('evaluation_id').notNull(),
  name: text('name').notNull(),
  weight: numeric('weight', { precision: 5, scale: 2 }).notNull(),
  stream: text('stream', { enum: ['TECHNICAL', 'COMMERCIAL', 'OTHER'] }).notNull(),
  passFail: boolean('pass_fail').notNull().default(false),
});

export const panelMember = pgTable(
  'panel_member',
  {
    id: id(),
    tenantId: tenantId(),
    evaluationId: uuid('evaluation_id').notNull(),
    userId: uuid('user_id').notNull(),
    stream: text('stream', { enum: ['TECHNICAL', 'COMMERCIAL', 'OTHER'] }).notNull(),
    coiState: text('coi_state', { enum: ['NOT_DECLARED', 'DECLARED_NONE', 'DECLARED_CONFLICT', 'REMOVED'] })
      .notNull()
      .default('NOT_DECLARED'),
    /** When the member marked their scoring complete (the chair needs all of them before opening consensus). */
    scoredAt: timestamp('scored_at', { withTimezone: true }),
  },
  (t) => [uniqueIndex('panel_member_uq').on(t.evaluationId, t.userId)],
);

export const score = pgTable(
  'score',
  {
    id: id(),
    tenantId: tenantId(),
    evaluationId: uuid('evaluation_id').notNull(),
    supplierId: uuid('supplier_id').notNull(),
    criterionId: uuid('criterion_id').notNull(),
    evaluatorId: uuid('evaluator_id').notNull(),
    score: numeric('score', { precision: 4, scale: 2 }).notNull(),
    comment: text('comment'),
    createdAt: created(),
  },
  (t) => [uniqueIndex('score_uq').on(t.evaluationId, t.supplierId, t.criterionId, t.evaluatorId)],
);

export const consensusItem = pgTable(
  'consensus_item',
  {
    id: id(),
    tenantId: tenantId(),
    evaluationId: uuid('evaluation_id').notNull(),
    supplierId: uuid('supplier_id').notNull(),
    criterionId: uuid('criterion_id').notNull(),
    variancePct: numeric('variance_pct', { precision: 6, scale: 2 }),
    flagged: boolean('flagged').notNull().default(false),
    consensusScore: numeric('consensus_score', { precision: 4, scale: 2 }),
    rationale: text('rationale'),
  },
  (t) => [uniqueIndex('consensus_uq').on(t.evaluationId, t.supplierId, t.criterionId)],
);

export const evalReport = pgTable('eval_report', {
  id: id(),
  tenantId: tenantId(),
  evaluationId: uuid('evaluation_id').notNull().unique(),
  status: text('status', { enum: ['DRAFT', 'AWAITING_APPROVAL', 'APPROVED'] })
    .notNull()
    .default('DRAFT'),
  generatedAt: timestamp('generated_at', { withTimezone: true }).notNull().defaultNow(),
});

export const contract = pgTable('contract', {
  id: id(),
  tenantId: tenantId(),
  number: text('number').notNull(),
  tenderId: uuid('tender_id'),
  supplierId: uuid('supplier_id').notNull(),
  parentId: uuid('parent_id'),
  templateId: text('template_id'),
  status: text('status', {
    enum: ['DRAFT', 'LEGAL_REVIEW', 'AWAITING_SIGNATURE', 'PARTIALLY_SIGNED', 'EXECUTED'],
  })
    .notNull()
    .default('DRAFT'),
  value: numeric('value', { precision: 14, scale: 2 }).notNull(),
  startDate: date('start_date'),
  endDate: date('end_date'),
  noticeDays: integer('notice_days').notNull().default(90),
  locked: boolean('locked').notNull().default(false),
  ownerId: uuid('owner_id'),
  sourceSystem: text('source_system'),
  deletedAt: timestamp('deleted_at', { withTimezone: true }), // logical delete only (NFR-CA02)
  createdAt: created(),
  updatedAt: updated(),
  version: version(),
});

export const clause = pgTable('clause', {
  id: id(),
  tenantId: tenantId(),
  contractId: uuid('contract_id').notNull(),
  clauseId: text('clause_id').notNull(),
  title: text('title').notNull(),
  text: text('text').notNull(),
  mandatory: boolean('mandatory').notNull().default(false),
  changedFromTemplate: boolean('changed_from_template').notNull().default(false),
  risk: text('risk', { enum: ['LOW', 'MEDIUM', 'HIGH'] }),
});

export const alert = pgTable('alert', {
  id: id(),
  tenantId: tenantId(),
  contractId: uuid('contract_id').notNull(),
  kind: text('kind', { enum: ['EXPIRY', 'NOTICE', 'MILESTONE', 'EXTENSION', 'CUSTOM'] }).notNull(),
  triggerDate: date('trigger_date').notNull(),
  recipientRule: text('recipient_rule').notNull().default('CONTRACT_OWNER'),
  status: text('status', { enum: ['SCHEDULED', 'SENT', 'CANCELLED'] })
    .notNull()
    .default('SCHEDULED'),
  origin: text('origin', { enum: ['SYSTEM', 'USER'] })
    .notNull()
    .default('SYSTEM'),
  sentAt: timestamp('sent_at', { withTimezone: true }),
  note: text('note'),
  createdBy: uuid('created_by'),
});

export const contractMilestone = pgTable('contract_milestone', {
  id: id(),
  tenantId: tenantId(),
  contractId: uuid('contract_id').notNull(),
  title: text('title').notNull(),
  dueDate: date('due_date').notNull(),
});

export const contractExtension = pgTable('contract_extension', {
  id: id(),
  tenantId: tenantId(),
  contractId: uuid('contract_id').notNull(),
  months: integer('months').notNull(),
  position: integer('position').notNull().default(1),
});

export const alertDelivery = pgTable('alert_delivery', {
  id: id(),
  tenantId: tenantId(),
  alertId: uuid('alert_id').notNull(),
  userId: uuid('user_id').notNull(),
  channel: text('channel', { enum: ['IN_APP', 'EMAIL'] }).notNull(),
  status: text('status', { enum: ['DELIVERED', 'SIMULATED'] }).notNull(),
  deliveredAt: timestamp('delivered_at', { withTimezone: true }).notNull().defaultNow(),
});

export const supplierActivation = pgTable('supplier_activation', {
  id: id(),
  tenantId: tenantId(),
  userId: uuid('user_id').notNull(),
  tokenHash: text('token_hash').notNull().unique(),
  expiresAt: timestamp('expires_at', { withTimezone: true }).notNull(),
  usedAt: timestamp('used_at', { withTimezone: true }),
  createdBy: uuid('created_by').notNull(),
  createdAt: created(),
});

export const notification = pgTable('notification', {
  id: id(),
  tenantId: tenantId(),
  userId: uuid('user_id').notNull(),
  title: text('title').notNull(),
  body: text('body'),
  link: text('link'),
  event: text('event'),
  read: boolean('read').notNull().default(false),
  createdAt: created(),
});

export const notificationDelivery = pgTable('notification_delivery', {
  id: id(),
  tenantId: tenantId(),
  notificationId: uuid('notification_id').notNull(),
  channel: text('channel').notNull(),
  status: text('status').notNull().default('SENT'),
  detail: text('detail'),
  createdAt: created(),
});

export const escalation = pgTable(
  'escalation',
  {
    id: id(),
    tenantId: tenantId(),
    entityType: text('entity_type').notNull(),
    entityId: uuid('entity_id').notNull(),
    level: integer('level').notNull().default(1),
    notifiedUserId: uuid('notified_user_id').notNull(),
    createdAt: created(),
  },
  (t) => [uniqueIndex('escalation_once').on(t.entityType, t.entityId, t.level)],
);

export const template = pgTable('template', {
  id: text('id').primaryKey(),
  tenantId: tenantId(),
  type: text('type').notNull(),
  name: text('name').notNull(),
  version: text('version').notNull(),
  status: text('status').notNull().default('ACTIVE'),
  body: jsonb('body').notNull().default({}),
});

export const workflow = pgTable('workflow', {
  id: text('id').primaryKey(),
  tenantId: tenantId(),
  name: text('name').notNull(),
  tier: text('tier', { enum: ['SIMPLE', 'INTERMEDIATE', 'COMPLEX'] }).notNull(),
  steps: jsonb('steps').notNull().default([]),
  subWorkflows: jsonb('sub_workflows').notNull().default([]),
  editable: boolean('editable').notNull().default(false),
});

export const idempotencyKey = pgTable(
  'idempotency_key',
  {
    id: id(),
    tenantId: tenantId(),
    key: text('key').notNull(),
    userId: uuid('user_id').notNull(),
    method: text('method').notNull(),
    path: text('path').notNull(),
    requestHash: text('request_hash').notNull(),
    status: integer('status'),
    response: jsonb('response'),
    createdAt: created(),
  },
  (t) => [uniqueIndex('idempotency_uq').on(t.tenantId, t.userId, t.key)],
);

export const auditEvent = pgTable(
  'audit_event',
  {
    seq: bigserial('seq', { mode: 'number' }).primaryKey(),
    tenantId: tenantId(),
    at: timestamp('at', { withTimezone: true }).notNull().defaultNow(),
    actorId: uuid('actor_id'),
    actorRole: text('actor_role'),
    action: text('action').notNull(),
    entityType: text('entity_type').notNull(),
    entityId: uuid('entity_id'),
    before: jsonb('before'),
    after: jsonb('after'),
    correlationId: text('correlation_id'),
    result: text('result', { enum: ['SUCCESS', 'DENIED', 'FAILED'] })
      .notNull()
      .default('SUCCESS'),
    prevHash: text('prev_hash').notNull(),
    hash: text('hash').notNull(),
  },
  (t) => [
    index('audit_entity_idx').on(t.entityType, t.entityId),
    index('audit_tenant_seq_idx').on(t.tenantId, t.seq),
  ],
);

/** Server-side sessions: enables idle timeout, absolute timeout and immediate revocation (SEC-A07). */
export const session = pgTable(
  'session',
  {
    id: uuid('id').primaryKey(),
    tenantId: tenantId(),
    userId: uuid('user_id').notNull(),
    pool: text('pool', { enum: ['STAFF', 'SUPPLIER'] }).notNull(), // separate identity pools (SEC-A03)
    createdAt: created(),
    lastSeenAt: timestamp('last_seen_at', { withTimezone: true }).notNull().defaultNow(),
    expiresAt: timestamp('expires_at', { withTimezone: true }).notNull(),
    revokedAt: timestamp('revoked_at', { withTimezone: true }),
    ip: text('ip'),
    userAgent: text('user_agent'),
    mfaState: text('mfa_state', { enum: ['NOT_REQUIRED', 'VERIFIED', 'ENROLMENT_REQUIRED'] })
      .notNull()
      .default('NOT_REQUIRED'),
    authMethod: text('auth_method', { enum: ['PASSWORD', 'SSO'] })
      .notNull()
      .default('PASSWORD'),
  },
  (t) => [index('session_user_idx').on(t.userId)],
);

export const migrationBatch = pgTable('migration_batch', {
  id: id(),
  tenantId: tenantId(),
  filename: text('filename').notNull(),
  sourceSystem: text('source_system').notNull(),
  status: text('status', { enum: ['VALIDATED', 'CUTOVER', 'CANCELLED'] })
    .notNull()
    .default('VALIDATED'),
  total: integer('total').notNull().default(0),
  uploadedBy: uuid('uploaded_by').notNull(),
  createdAt: created(),
  cutoverAt: timestamp('cutover_at', { withTimezone: true }),
  cutoverBy: uuid('cutover_by'),
});

export const migrationRecord = pgTable(
  'migration_record',
  {
    id: id(),
    tenantId: tenantId(),
    batchId: uuid('batch_id').notNull(),
    rowNo: integer('row_no').notNull(),
    raw: jsonb('raw').notNull(),
    status: text('status', { enum: ['VALID', 'EXCEPTION', 'SKIPPED', 'LOADED'] })
      .notNull()
      .default('VALID'),
    issues: jsonb('issues').notNull().default([]),
    warnings: jsonb('warnings').notNull().default([]),
    reviewedBy: uuid('reviewed_by'),
    reviewedAt: timestamp('reviewed_at', { withTimezone: true }),
    reviewNote: text('review_note'),
    requestId: uuid('request_id'),
    contractId: uuid('contract_id'),
  },
  (t) => [uniqueIndex('migration_row_uq').on(t.batchId, t.rowNo)],
);

export const userMfa = pgTable('user_mfa', {
  userId: uuid('user_id').primaryKey(),
  tenantId: tenantId(),
  secret: text('secret').notNull(),
  confirmed: boolean('confirmed').notNull().default(false),
  lastStep: bigint('last_step', { mode: 'number' }).notNull().default(0),
  createdAt: created(),
});
