// GENERATED by _work/gen_roadmap.py from docs/RTM.csv - do not edit by hand.
// One line per stubbed (S) or deferred (D) requirement; the marker comment is what todo-inventory.md is built from.
import type { RoadmapItem } from './roadmap.js';

export const ROADMAP_DATA: readonly RoadmapItem[] = [
  {
    id: 'FR-X01',
    tier: 'D',
    status: 'DEFERRED',
    category: 'Request Intake & AI',
    area: null,
    priority: 'Could',
    title:
      'Provide a conversational AI capability in which the user can request information and provide instructions',
  }, // DEFERRED(FR-X01)
  {
    id: 'FR-0010',
    tier: 'S',
    status: 'BUILT',
    category: 'Request Intake & AI',
    area: '/app/requests',
    priority: 'Should',
    title:
      'A single intake conversation shall be capable of auto-populating multiple downstream artefacts, including the procurement plan, RFx/tender documents, evaluation...',
    batch: 'B1',
  }, // TODO(FR-0010)
  {
    id: 'FR-0015',
    tier: 'S',
    status: 'BUILT',
    category: 'Request Intake & AI',
    area: '/app/requests',
    priority: 'Must',
    title:
      'Cross-reference request details against a system defined configurable industry classification taxonomies (UNSPSC, CPV or NAICS) and entity specific classifications...',
    batch: 'B1',
  }, // TODO(FR-0015)
  {
    id: 'FR-0020',
    tier: 'S',
    status: 'BUILT',
    category: 'Request Intake & AI',
    area: '/app/requests',
    priority: 'Should',
    title:
      'Infer likely suppliers / quote sets for a request based on category of spend, using existing in-house supplier data including known market suppliers and their contact...',
    batch: 'B1',
  }, // TODO(FR-0020)
  {
    id: 'FR-X02',
    tier: 'S',
    status: 'BUILT',
    category: 'Request Intake & AI',
    area: '/app/requests',
    priority: 'Unprioritised',
    title: 'Have the ability to configure muiltiple procurement workflows based on their procurement policy',
    batch: 'B1',
  }, // TODO(FR-X02)
  {
    id: 'FR-0030',
    tier: 'S',
    status: 'BUILT',
    category: 'Request Intake & AI',
    area: '/app/requests',
    priority: 'Must',
    title:
      'Automatically identify and flag any approvals or engagements required (for example IT approval, legal review, cyber assessment, finance, risk & compliance) based on...',
    batch: 'B1',
  }, // TODO(FR-0030)
  {
    id: 'FR-0040',
    tier: 'S',
    status: 'BUILT',
    category: 'Request Intake & AI',
    area: '/app/requests',
    priority: 'Must',
    title:
      'Support a configurable choice between procurement-team-led intake (higher value/risk) and self-service intake (lower value/risk), per organisational policy',
    batch: 'B1',
  }, // TODO(FR-0040)
  {
    id: 'FR-0045',
    tier: 'S',
    status: 'BUILT',
    category: 'Request Intake & AI',
    area: '/app/requests',
    priority: 'Should',
    title:
      'Offer configurable Dashboard layouts — a dense analytical workspace for high-volume category managers — selectable by user role',
    batch: 'B1',
  }, // TODO(FR-0045)
  {
    id: 'FR-X03',
    tier: 'S',
    status: 'BUILT',
    category: 'Request Intake & AI',
    area: '/app/requests',
    priority: 'Should',
    title: 'Offer users the ability to select from mulitple layouts',
    batch: 'B1',
  }, // TODO(FR-X03)
  {
    id: 'FR-X04',
    tier: 'S',
    status: 'BUILT',
    category: 'Request Intake & AI',
    area: '/app/requests',
    priority: 'Should',
    title: 'Offer configurable forms',
    batch: 'B1',
  }, // TODO(FR-X04)
  {
    id: 'FR-0050',
    tier: 'S',
    status: 'BUILT',
    category: 'Request Intake & AI',
    area: '/app/requests',
    priority: 'Must',
    title:
      "Where a customer's ERP is integrated, the system shall perform a real-time pre-commitment budget check (active budget lines, available funds) before a request can be...",
    batch: 'B1',
  }, // TODO(FR-0050)
  {
    id: 'FR-0055',
    tier: 'S',
    status: 'BUILT',
    category: 'Request Intake & AI',
    area: '/app/requests',
    priority: 'Must',
    title: 'If budget is flagged as exceeded - what is next step??',
    batch: 'B1',
  }, // TODO(FR-0055)
  {
    id: 'FR-X05',
    tier: 'S',
    status: 'BUILT',
    category: 'Request Intake & AI',
    area: '/app/requests',
    priority: 'Unprioritised',
    title:
      "CLIENT QUERY: This row (private-sector 'soft cap' model) has no Requirement ID — recommend assigning one (for example FR-0056) for traceability",
    batch: 'B1',
  }, // TODO(FR-X05)
  {
    id: 'FR-0065',
    tier: 'S',
    status: 'BUILT',
    category: 'Request Intake & AI',
    area: '/app/requests',
    priority: 'Must',
    title: 'Dispatch predefined automated notifications (in-platform, email, Slack, MS Teams)',
    batch: 'B1',
  }, // TODO(FR-0065)
  {
    id: 'FR-0066',
    tier: 'S',
    status: 'BUILT',
    category: 'Request Intake & AI',
    area: '/app/requests',
    priority: 'Must',
    title:
      "Allow the customer to define notifications rules such as budget breaches, delegate action requests, and approval-timeout escalation, escalating to the delegate's...",
    batch: 'B1',
  }, // TODO(FR-0066)
  {
    id: 'FR-0085',
    tier: 'S',
    status: 'PARTIAL',
    category: 'Procurement Plan',
    area: '/app/plans',
    priority: 'Should',
    title:
      'The procurement plan layout shall support configurable, drag-and-drop design, or a system-provided default template where the customer has none of its own',
  }, // TODO(FR-0085)
  {
    id: 'FR-0090',
    tier: 'S',
    status: 'BUILT',
    category: 'Procurement Plan',
    area: '/app/plans',
    priority: 'Must',
    title: 'No description in the requirements register',
    batch: 'B1',
  }, // TODO(FR-0090)
  {
    id: 'FR-0095',
    tier: 'S',
    status: 'BUILT',
    category: 'Procurement Plan',
    area: '/app/plans',
    priority: 'Should',
    title:
      'Provide capabilities to tag and categorise records for example ESG / socio-economic planning capability, carbon offset ceilings, domestic/regional labour content...',
    batch: 'B1',
  }, // TODO(FR-0095)
  {
    id: 'FR-X06',
    tier: 'S',
    status: 'BUILT',
    category: 'Request Intake & AI',
    area: '/app/requests',
    priority: 'Unprioritised',
    title: 'Delegated approval setup and actioned. This is a customer configurable parameter',
    batch: 'B1',
  }, // TODO(FR-X06)
  {
    id: 'FR-0115',
    tier: 'S',
    status: 'PARTIAL',
    category: 'RFx / Tender Collaboration',
    area: '/app/collaboration',
    priority: 'Should',
    title:
      'Users shall be able to drag-and-drop to design the RFx/tender template layout, or use a system-provided default template',
  }, // TODO(FR-0115)
  {
    id: 'FR-0125',
    tier: 'S',
    status: 'BUILT',
    category: 'RFx / Tender Collaboration',
    area: '/app/collaboration',
    priority: 'Should',
    title:
      'Support a structured legal deviation register, capturing supplier-proposed contract deviations as discrete fields, exportable to Word/Excel, with legal commentary...',
    batch: 'B2',
  }, // TODO(FR-0125)
  {
    id: 'FR-0130',
    tier: 'D',
    status: 'DEFERRED',
    category: 'RFx / Tender Collaboration',
    area: null,
    priority: "Won't",
    title:
      'Support structured Interactive Response Schedules — digital bid-entry forms for vendor pricing and technical submissions replacing unstructured document attachments',
  }, // DEFERRED(FR-0130)
  {
    id: 'FR-0140',
    tier: 'S',
    status: 'BUILT',
    category: 'RFx / Tender Collaboration',
    area: '/app/collaboration',
    priority: 'Must',
    title:
      'Route the finalised tender notice automatically to mandatory public registers (for example AusTender, SAM.gov, TED) for public-sector tenders based on jurisdiction,...',
    batch: 'B2',
  }, // TODO(FR-0140)
  {
    id: 'FR-0145',
    tier: 'S',
    status: 'BUILT',
    category: 'RFx / Tender Collaboration',
    area: '/app/collaboration',
    priority: 'Must',
    title:
      'For public-sector tenders, the system shall validate that the gap between publication and closing dates meets applicable statutory minimums (for example a 25-day...',
    batch: 'B2',
  }, // TODO(FR-0145)
  {
    id: 'FR-0175',
    tier: 'D',
    status: 'DEFERRED',
    category: 'Tender Portal',
    area: null,
    priority: 'Could',
    title:
      'For high-value or high-risk tenders, the platform shall support an optional dual-witness requirement, under which encrypted submissions cannot be opened after closing...',
  }, // DEFERRED(FR-0175)
  {
    id: 'FR-0180',
    tier: 'S',
    status: 'BUILT',
    category: 'Tender Portal',
    area: '/app/tenders',
    priority: 'Must',
    title:
      'Perform automated sanctions/watchlist screening (for example OFAC, EU Sanctions, INTERPOL) during supplier onboarding, and shall quarantine document access and alert...',
    batch: 'B2',
  }, // TODO(FR-0180)
  {
    id: 'FR-0185',
    tier: 'D',
    status: 'DEFERRED',
    category: 'Tender Portal',
    area: null,
    priority: 'Could',
    title:
      'Validate supplier-uploaded insurance certificates via OCR-based extraction of policy limits and expiry, and shall block final submission where cover falls below the...',
  }, // DEFERRED(FR-0185)
  {
    id: 'FR-0190',
    tier: 'S',
    status: 'BUILT',
    category: 'Tender Portal',
    area: '/app/tenders',
    priority: 'Must',
    title:
      'Enforce segregation of duties, blocking users holding Tender Administrator or Probity Officer roles from also holding Evaluator access on the same project',
    batch: 'B2',
  }, // TODO(FR-0190)
  {
    id: 'FR-0195',
    tier: 'S',
    status: 'BUILT',
    category: 'Tender Portal',
    area: '/app/tenders',
    priority: 'Must',
    title:
      'Questions and answers raised through the portal shall be captured and publishable either to a single supplier or broadcast to all suppliers on the tender',
    batch: 'B2',
  }, // TODO(FR-0195)
  {
    id: 'FR-0200',
    tier: 'S',
    status: 'BUILT',
    category: 'Tender Portal',
    area: '/app/tenders',
    priority: 'Must',
    title:
      'Automatically send email invitations to suppliers invited to a specific tender, and shall automatically generate and release the tender pack from the completed RFx...',
    batch: 'B2',
  }, // TODO(FR-0200)
  {
    id: 'FR-0205',
    tier: 'S',
    status: 'BUILT',
    category: 'Tender Portal',
    area: '/app/tenders',
    priority: 'Should',
    title:
      'Procurement or administrator roles shall be able to grant permission for a nominated supplier to submit after the closing time where there is a justified reason,...',
    batch: 'B2',
  }, // TODO(FR-0205)
  {
    id: 'FR-0210',
    tier: 'S',
    status: 'BUILT',
    category: 'Tender Portal',
    area: '/app/tenders',
    priority: 'Must',
    title:
      'Procurement or administrator roles shall be able to issue addenda and change tender dates and times, with automatic notification to all registered bidders',
    batch: 'B2',
  }, // TODO(FR-0210)
  {
    id: 'FR-0215',
    tier: 'S',
    status: 'BUILT',
    category: 'Tender Portal',
    area: '/app/tenders',
    priority: 'Should',
    title:
      'Enterprises shall be able to configure additional supplier onboarding questions (for example modern slavery and sustainability questions) and, where a question set is...',
    batch: 'B2',
  }, // TODO(FR-0215)
  {
    id: 'FR-0220',
    tier: 'S',
    status: 'BUILT',
    category: 'Tender Portal',
    area: '/app/tenders',
    priority: 'Should',
    title:
      'Multi-stage tendering shall support a separate document set, submission round and report per stage, including second and third stage submissions from shortlisted...',
    batch: 'B2',
  }, // TODO(FR-0220)
  {
    id: 'FR-0225',
    tier: 'S',
    status: 'BUILT',
    category: 'Tender Portal',
    area: '/app/tenders',
    priority: 'Must',
    title:
      'Suppliers who are not shortlisted shall be sent an automated unsuccessful notification once the procurement team or administrator confirms the shortlist outcome',
    batch: 'B2',
  }, // TODO(FR-0225)
  {
    id: 'FR-0230',
    tier: 'S',
    status: 'BUILT',
    category: 'Tender Portal',
    area: '/app/tenders',
    priority: 'Must',
    title:
      'Where a supplier submits across multiple stages, the AI shall treat the latest submission version as authoritative while capturing content from earlier versions that...',
    batch: 'B2',
  }, // TODO(FR-0230)
  {
    id: 'FR-0240',
    tier: 'S',
    status: 'BUILT',
    category: 'Supplier Portal',
    area: '/supplier',
    priority: 'Must',
    title:
      "Send an invitation email to prospective suppliers containing a unique link for the supplier's contact to set up their own portal instance, including privacy settings...",
    batch: 'B2',
  }, // TODO(FR-0240)
  {
    id: 'FR-0245',
    tier: 'S',
    status: 'BUILT',
    category: 'Supplier Portal',
    area: '/supplier',
    priority: 'Must',
    title:
      'Suppliers shall be able to manage and change their registered contacts, including reassigning access when a contact leaves the organisation, with a notification email...',
    batch: 'B2',
  }, // TODO(FR-0245)
  {
    id: 'FR-0250',
    tier: 'S',
    status: 'BUILT',
    category: 'Supplier Portal',
    area: '/supplier',
    priority: 'Must',
    title:
      'The supplier profile shall carry current insurance certificate and sanctions-screening status, shared with the Tender Portal onboarding checks',
    batch: 'B2',
  }, // TODO(FR-0250)
  {
    id: 'FR-0265',
    tier: 'S',
    status: 'BUILT',
    category: 'Evaluation',
    area: '/app/evaluations',
    priority: 'Must',
    title:
      'The evaluation workflow shall include a mandatory pass/fail compliance gate covering matters such as entity registration, mandatory declarations and insurance limits,...',
    batch: 'B3',
  }, // TODO(FR-0265)
  {
    id: 'FR-0280',
    tier: 'S',
    status: 'BUILT',
    category: 'Evaluation',
    area: '/app/evaluations',
    priority: 'Must',
    title:
      'Support both numeric scoring and simple ranking, with ranking available as a configurable option for low-value/low-risk arrangements',
    batch: 'B3',
  }, // TODO(FR-0280)
  {
    id: 'FR-0285',
    tier: 'S',
    status: 'BUILT',
    category: 'Evaluation',
    area: '/app/evaluations',
    priority: 'Must',
    title:
      'Support multi-stage evaluations, with each stage able to shortlist one or more suppliers before the next stage is run, and scores retained for all rounds',
    batch: 'B3',
  }, // TODO(FR-0285)
  {
    id: 'FR-0290',
    tier: 'S',
    status: 'BUILT',
    category: 'Evaluation',
    area: '/app/evaluations',
    priority: 'Must',
    title:
      'Provide a negotiation and Best and Final Offer workspace supporting audited clarification requests with response deadlines, and a controlled mini-tendering cycle for...',
    batch: 'B3',
  }, // TODO(FR-0290)
  {
    id: 'FR-0295',
    tier: 'S',
    status: 'BUILT',
    category: 'Evaluation',
    area: '/app/evaluations',
    priority: 'Should',
    title:
      'Generate AI-assisted negotiation recommendations (for example a suggested discount percentage, or specific clauses/indemnities to negotiate) based on submitted...',
    batch: 'B3',
  }, // TODO(FR-0295)
  {
    id: 'FR-0305',
    tier: 'S',
    status: 'BUILT',
    category: 'Evaluation',
    area: '/app/evaluations',
    priority: 'Must',
    title: 'Support an evaluator substitution workflow',
    batch: 'B3',
  }, // TODO(FR-0305)
  {
    id: 'FR-0310',
    tier: 'S',
    status: 'BUILT',
    category: 'Evaluation',
    area: '/app/evaluations',
    priority: 'Must',
    title:
      'Provide a read-only Probity Advisor oversight portal for external auditors, scoped to only the procurements the advisor is allocated to, including a system-hold...',
    batch: 'B3',
  }, // TODO(FR-0310)
  {
    id: 'FR-0315',
    tier: 'S',
    status: 'BUILT',
    category: 'Evaluation',
    area: '/app/evaluations',
    priority: 'Must',
    title:
      'Scoring, ranking and evaluation commentary shall be capable of being entered in plain language, in addition to structured score entry',
    batch: 'B3',
  }, // TODO(FR-0315)
  {
    id: 'FR-0320',
    tier: 'S',
    status: 'BUILT',
    category: 'Evaluation',
    area: '/app/evaluations',
    priority: 'Must',
    title:
      'Evaluation criteria shall be selectable from a pre-populated criteria library, easily amendable, and configurable to be the same or different across evaluation stages',
    batch: 'B3',
  }, // TODO(FR-0320)
  {
    id: 'FR-0325',
    tier: 'S',
    status: 'BUILT',
    category: 'Evaluation',
    area: '/app/evaluations',
    priority: 'Must',
    title:
      'Automatically issue conflict-of-interest re-declaration reminders after the tender closes, once supplier identities are known, and shall report which users have not...',
    batch: 'B3',
  }, // TODO(FR-0325)
  {
    id: 'FR-0330',
    tier: 'S',
    status: 'BUILT',
    category: 'Evaluation',
    area: '/app/evaluations',
    priority: 'Must',
    title:
      'Conflict-of-interest outcomes shall be recorded against a defined set of dispositions — immaterial (remain in role), minor (remain but excluded from assessing the...',
    batch: 'B3',
  }, // TODO(FR-0330)
  {
    id: 'FR-0335',
    tier: 'S',
    status: 'BUILT',
    category: 'Evaluation',
    area: '/app/evaluations',
    priority: 'Must',
    title:
      'Where a person is removed from a procurement for a material conflict, the platform shall support nominating a replacement and shall automatically issue the...',
    batch: 'B3',
  }, // TODO(FR-0335)
  {
    id: 'FR-0340',
    tier: 'S',
    status: 'BUILT',
    category: 'Evaluation',
    area: '/app/evaluations',
    priority: 'Should',
    title:
      'A probity advisor shall be able to upload, or author in-platform, a probity plan and probity outcomes report, generated to Word or PDF with a profile-based sign-off...',
    batch: 'B3',
  }, // TODO(FR-0340)
  {
    id: 'FR-0350',
    tier: 'S',
    status: 'BUILT',
    category: 'Evaluation Report',
    area: '/app/evaluations',
    priority: 'Must',
    title:
      'On consensus lock, the system shall automatically compile a Sourcing Recommendation Report combining pass/fail compliance logs, scoring distributions, panel...',
    batch: 'B3',
  }, // TODO(FR-0350)
  {
    id: 'FR-0355',
    tier: 'S',
    status: 'BUILT',
    category: 'Evaluation Report',
    area: '/app/evaluations',
    priority: 'Must',
    title:
      'The evaluation report shall be printable, shall carry a timestamp containing all required audit information, and shall be viewable and actionable for review and...',
    batch: 'B3',
  }, // TODO(FR-0355)
  {
    id: 'FR-0360',
    tier: 'S',
    status: 'BUILT',
    category: 'Evaluation Report',
    area: '/app/evaluations',
    priority: 'Must',
    title:
      'For multi-stage evaluations, the evaluation report shall document the outcomes of each individual stage',
    batch: 'B3',
  }, // TODO(FR-0360)
  {
    id: 'FR-0365',
    tier: 'S',
    status: 'PARTIAL',
    category: 'Evaluation Report',
    area: '/app/evaluations',
    priority: 'Should',
    title:
      'The evaluation report layout shall support drag-and-drop configuration, or a system-provided default template where the customer has none',
  }, // TODO(FR-0365)
  {
    id: 'FR-0370',
    tier: 'S',
    status: 'BUILT',
    category: 'Evaluation Report',
    area: '/app/evaluations',
    priority: 'Must',
    title:
      'Conflict-of-interest declarations shall be capable of being captured and recorded at the evaluation report stage in the same manner as at the procurement plan stage',
    batch: 'B3',
  }, // TODO(FR-0370)
  {
    id: 'FR-0375',
    tier: 'S',
    status: 'BUILT',
    category: 'Evaluation Report',
    area: '/app/evaluations',
    priority: 'Must',
    title:
      "The evaluation report shall include an explicit sign-off/approval step, routed to the delegate holding the appropriate authority for the procurement's value tier,...",
    batch: 'B3',
  }, // TODO(FR-0375)
  {
    id: 'FR-0385',
    tier: 'S',
    status: 'BUILT',
    category: 'Contract Award & Legal',
    area: '/app/contracts',
    priority: 'Must',
    title:
      'Where a customer has no external legal system, the platform shall provide native legal matter management, comprising a legal kanban board, review-hour logging, and a...',
    batch: 'B4',
  }, // TODO(FR-0385)
  {
    id: 'FR-0390',
    tier: 'D',
    status: 'DEFERRED',
    category: 'Contract Award & Legal',
    area: null,
    priority: 'Could',
    title:
      'Where a customer operates an enterprise legal platform (for example HighQ, Icertis), the system shall raise an outbound matter-initiation event through an integration...',
  }, // DEFERRED(FR-0390)
  {
    id: 'FR-0400',
    tier: 'S',
    status: 'BUILT',
    category: 'Contract Award & Legal',
    area: '/app/contracts',
    priority: 'Must',
    title:
      'Monitor the negotiation room for material deviations to non-negotiable mandatory clauses (for example indemnity limits, liability caps, IP governance)',
    batch: 'B4',
  }, // TODO(FR-0400)
  {
    id: 'FR-0405',
    tier: 'S',
    status: 'BUILT',
    category: 'Contract Award & Legal',
    area: '/app/contracts',
    priority: 'Must',
    title:
      "During contract drafting, the system shall cross-check the winning supplier's tender submission against the original RFx and flag any inconsistencies (for example...",
    batch: 'B4',
  }, // TODO(FR-0405)
  {
    id: 'FR-0415',
    tier: 'S',
    status: 'BUILT',
    category: 'Contract Award & Legal',
    area: '/app/contracts',
    priority: 'Must',
    title:
      "Run a pre-flight verification of the vendor's legal name, tax registration and banking details against ERP/vetted records before signature options unlock",
    batch: 'B4',
  }, // TODO(FR-0415)
  {
    id: 'FR-0425',
    tier: 'S',
    status: 'BUILT',
    category: 'Contract Award & Legal',
    area: '/app/contracts',
    priority: 'Should',
    title:
      "Support advanced signing workflows, including blind signing (a signatory signs without other parties' signatures or identities visible) and staged endorsement...",
    batch: 'B4',
  }, // TODO(FR-0425)
  {
    id: 'FR-0430',
    tier: 'S',
    status: 'BUILT',
    category: 'Contract Award & Legal',
    area: '/app/contracts',
    priority: 'Should',
    title:
      'The signing capability shall extend to document types beyond the primary contract, including NDAs, confidentiality agreements and master agreements',
    batch: 'B4',
  }, // TODO(FR-0430)
  {
    id: 'FR-0435',
    tier: 'S',
    status: 'BUILT',
    category: 'Contract Award & Legal',
    area: '/app/contracts',
    priority: 'Should',
    title:
      "Support time-bound access grants for evaluation committee members, auditors and advisors, automatically revoking access to a project's documents at a configured...",
    batch: 'B4',
  }, // TODO(FR-0435)
  {
    id: 'FR-0440',
    tier: 'S',
    status: 'BUILT',
    category: 'Contract Award & Legal',
    area: '/app/contracts',
    priority: 'Should',
    title:
      'Where contract negotiations extend beyond 30 days, the platform shall automatically lock signature blocks and force a re-run of sanctions and financial risk checks on...',
    batch: 'B4',
  }, // TODO(FR-0440)
  {
    id: 'FR-0445',
    tier: 'S',
    status: 'BUILT',
    category: 'Contract Award & Legal',
    area: '/app/contracts',
    priority: 'Should',
    title:
      'Send email invitations to internal and external signing delegates, with automated reminders where action has not been taken, shall allow signatories to view the full...',
    batch: 'B4',
  }, // TODO(FR-0445)
  {
    id: 'FR-0450',
    tier: 'S',
    status: 'BUILT',
    category: 'Contract Award & Legal',
    area: '/app/contracts',
    priority: 'Should',
    title:
      'Present an AI-generated, auto-populated summary of contract risks to the delegate ahead of signing, with legal retaining final review and edit before release',
    batch: 'B4',
  }, // TODO(FR-0450)
  {
    id: 'FR-0460',
    tier: 'S',
    status: 'BUILT',
    category: 'Contract Award & Legal',
    area: '/app/contracts',
    priority: 'Must',
    title: 'Contract variations shall be linked back to their originating (parent) contract record',
    batch: 'B4',
  }, // TODO(FR-0460)
  {
    id: 'FR-0465',
    tier: 'S',
    status: 'BUILT',
    category: 'Contract Award & Legal',
    area: '/app/contracts',
    priority: 'Must',
    title:
      'Legal shall be able to collaborate in-platform and make live changes to the contract without a generate-edit-regenerate cycle, and shall be able to download final...',
    batch: 'B4',
  }, // TODO(FR-0465)
  {
    id: 'FR-0470',
    tier: 'S',
    status: 'BUILT',
    category: 'Contract Award & Legal',
    area: '/app/contracts',
    priority: 'Should',
    title:
      'Legal shall be able to upload policies and historical legal advice for the AI to draw on when advising on deviations and negotiation positions',
    batch: 'B4',
  }, // TODO(FR-0470)
  {
    id: 'FR-0475',
    tier: 'S',
    status: 'BUILT',
    category: 'Contract Award & Legal',
    area: '/app/contracts',
    priority: 'Must',
    title:
      'The deviation register shall auto-populate a risk rating for each deviation, amendable by legal in plain language',
    batch: 'B4',
  }, // TODO(FR-0475)
  {
    id: 'FR-0480',
    tier: 'S',
    status: 'BUILT',
    category: 'Contract Award & Legal',
    area: '/app/contracts',
    priority: 'Must',
    title:
      'Support an optional legal endorsement gate and optional endorsement by other business units (for example finance) before a contract is released for signing',
    batch: 'B4',
  }, // TODO(FR-0480)
  {
    id: 'FR-0485',
    tier: 'S',
    status: 'BUILT',
    category: 'Contract Award & Legal',
    area: '/app/contracts',
    priority: 'Should',
    title:
      'The AI shall generate a negotiation strategy for the category, sector and procurement type, covering how to frame the negotiation, likely techniques, and a graduated...',
    batch: 'B4',
  }, // TODO(FR-0485)
  {
    id: 'FR-0495',
    tier: 'S',
    status: 'PLANNED',
    category: 'Contract Management',
    area: '/app/contracts',
    priority: 'Should',
    title:
      "Where a customer's ERP is integrated, the system shall enforce spend-ceiling guards that block purchase requisitions exceeding the contract limit",
  }, // TODO(FR-0495)
  {
    id: 'FR-0500',
    tier: 'S',
    status: 'PLANNED',
    category: 'Contract Management',
    area: '/app/contracts',
    priority: 'Should',
    title:
      'Perform automated line-item rate-card matching (3-way match) between purchase orders, contracts and invoices to block unapproved price increases',
  }, // TODO(FR-0500)
  {
    id: 'FR-0510',
    tier: 'S',
    status: 'PLANNED',
    category: 'Contract Management',
    area: '/app/contracts',
    priority: 'Must',
    title: 'Implement non-negotiable, hard-coded system alerts that cannot be muted by users',
  }, // TODO(FR-0510)
  {
    id: 'FR-0515',
    tier: 'S',
    status: 'PLANNED',
    category: 'Contract Management',
    area: '/app/contracts',
    priority: 'Must',
    title:
      'Provide user-configurable custom milestone alerts, addable in plain language, with selectable delivery channels (in-app, email, SMS or Slack) and assigned owners',
  }, // TODO(FR-0515)
  {
    id: 'FR-0520',
    tier: 'S',
    status: 'PLANNED',
    category: 'Contract Management',
    area: '/app/contracts',
    priority: 'Should',
    title:
      'Support rebate tracking against contracted rebate terms, automatically detecting and flagging missed or under-claimed rebates for follow-up',
  }, // TODO(FR-0520)
  {
    id: 'FR-0525',
    tier: 'S',
    status: 'PLANNED',
    category: 'Contract Management',
    area: '/app/contracts',
    priority: 'Should',
    title:
      'Monitor price-escalation clauses (for example CPI-linked or scheduled increases) and flag supplier invoices that apply an escalation outside the contracted formula or...',
  }, // TODO(FR-0525)
  {
    id: 'FR-0530',
    tier: 'S',
    status: 'PLANNED',
    category: 'Contract Management',
    area: '/app/contracts',
    priority: 'Must',
    title:
      'Derive additional alert triggers directly from contract clause language using AI extraction — for example automatically scheduling an alert ahead of a clause-stated...',
  }, // TODO(FR-0530)
  {
    id: 'FR-0535',
    tier: 'S',
    status: 'PLANNED',
    category: 'Contract Management',
    area: '/app/contracts',
    priority: 'Must',
    title:
      'Contract variations shall be processed through a dedicated variation workflow requiring a logged business case and cumulative-variance calculation, saved as a...',
  }, // TODO(FR-0535)
  {
    id: 'FR-0540',
    tier: 'S',
    status: 'PLANNED',
    category: 'Contract Management',
    area: '/app/contracts',
    priority: 'Must',
    title:
      'Support both cumulative-spend and incremental/additional-spend-only variation models, configurable per organisation, with the workflow and required delegate authority...',
  }, // TODO(FR-0540)
  {
    id: 'FR-0545',
    tier: 'S',
    status: 'PLANNED',
    category: 'Contract Management',
    area: '/app/contracts',
    priority: 'Should',
    title:
      'For public-sector customers, a contract modification exceeding a statutory value-change threshold (for example 10%) shall trigger a mandatory public register...',
  }, // TODO(FR-0545)
  {
    id: 'FR-0550',
    tier: 'S',
    status: 'PLANNED',
    category: 'Contract Management',
    area: '/app/contracts',
    priority: 'Must',
    title:
      'Run automated compliance monitoring on supplier insurance and compliance records and shall place a transactional hold blocking new purchase orders against a contract...',
  }, // TODO(FR-0550)
  {
    id: 'FR-0555',
    tier: 'S',
    status: 'PLANNED',
    category: 'Contract Management',
    area: '/app/contracts',
    priority: 'Must',
    title:
      'Contract management plan and risk management plan templates shall auto-populate for high-value/high-risk contracts, with support for customer-uploaded templates, and...',
  }, // TODO(FR-0555)
  {
    id: 'FR-0560',
    tier: 'S',
    status: 'PLANNED',
    category: 'Contract Management',
    area: '/app/contracts',
    priority: 'Must',
    title:
      'Users shall be able to search for and access only the contracts belonging to them or their team, per the configured access hierarchy, and shall receive AI-recommended...',
  }, // TODO(FR-0560)
  {
    id: 'FR-0565',
    tier: 'S',
    status: 'PLANNED',
    category: 'Contract Management',
    area: '/app/contracts',
    priority: 'Must',
    title:
      'A parent-child relationship shall be maintained between an original contract and each of its variations, including where each variation is treated as a new...',
  }, // TODO(FR-0565)
  {
    id: 'FR-0570',
    tier: 'S',
    status: 'PLANNED',
    category: 'Contract Management',
    area: '/app/contracts',
    priority: 'Must',
    title:
      'Users shall be able to create a new procurement linked to an existing contract in order to renew it, vary it, or exercise an optional extension, generating a new...',
  }, // TODO(FR-0570)
  {
    id: 'FR-0575',
    tier: 'S',
    status: 'PLANNED',
    category: 'Contract Management',
    area: '/app/contracts',
    priority: 'Must',
    title:
      'Support head/master agreement parent-child structures, with work orders linked to their master agreement and reportable at both master and work-order level',
  }, // TODO(FR-0575)
  {
    id: 'FR-0580',
    tier: 'S',
    status: 'PLANNED',
    category: 'Contract Management',
    area: '/app/contracts',
    priority: 'Must',
    title:
      'Track live spend against a contract using invoice and payment data, present visual progress bars for contract term and spend consumed, and raise automatic alerts when...',
  }, // TODO(FR-0580)
  {
    id: 'FR-0585',
    tier: 'S',
    status: 'PLANNED',
    category: 'Contract Management',
    area: '/app/contracts',
    priority: 'Should',
    title:
      'The delegation model shall support approval of an allocated funding envelope, against which nominated users may approve individual commitments, with an alert to seek...',
  }, // TODO(FR-0585)
  {
    id: 'FR-0595',
    tier: 'S',
    status: 'PLANNED',
    category: 'Reporting & Dashboards',
    area: '/app/reports',
    priority: 'Must',
    title:
      'Provide a Gantt-chart style view for procurement-team-wide visibility of phase and status across all active procurements, with drag-and-drop schedule adjustment that...',
  }, // TODO(FR-0595)
  {
    id: 'FR-0600',
    tier: 'S',
    status: 'PLANNED',
    category: 'Reporting & Dashboards',
    area: '/app/reports',
    priority: 'Must',
    title:
      'Provide role- and hierarchy-based dashboard views (procurement, legal, delegate, executive, finance, risk/compliance, division/business unit), with access scoped...',
  }, // TODO(FR-0600)
  {
    id: 'FR-0605',
    tier: 'S',
    status: 'PLANNED',
    category: 'Reporting & Dashboards',
    area: '/app/reports',
    priority: 'Must',
    title:
      'Provide category spend, maverick-spend (invoices paid outside approved contracts) and captured-savings dashboards, alongside a procurement-velocity view tracking...',
  }, // TODO(FR-0605)
  {
    id: 'FR-0610',
    tier: 'S',
    status: 'PLANNED',
    category: 'Reporting & Dashboards',
    area: '/app/reports',
    priority: 'Should',
    title:
      'Provide a geospatial supplier risk view plotting primary supplier locations, overlaid with external risk feeds (weather, financial-distress scores, geopolitical...',
  }, // TODO(FR-0610)
  {
    id: 'FR-0620',
    tier: 'S',
    status: 'PLANNED',
    category: 'Reporting & Dashboards',
    area: '/app/reports',
    priority: 'Must',
    title:
      'Provide a workload/capacity view mapping active procurement volume and dollar exposure against assigned manager, to support team-lead workload balancing',
  }, // TODO(FR-0620)
  {
    id: 'FR-0625',
    tier: 'S',
    status: 'PLANNED',
    category: 'Reporting & Dashboards',
    area: '/app/reports',
    priority: 'Must',
    title:
      'Charts shall support drill-down interactivity, users shall be able to configure and save their own custom views, and the platform shall support natural-language,...',
  }, // TODO(FR-0625)
  {
    id: 'FR-0645',
    tier: 'S',
    status: 'PLANNED',
    category: 'Reporting & Dashboards',
    area: '/app/reports',
    priority: 'Must',
    title:
      'Spend shall be reportable by supplier, by contract, by master agreement, by project, by business unit and by division',
  }, // TODO(FR-0645)
  {
    id: 'FR-0655',
    tier: 'S',
    status: 'BUILT',
    category: 'Data Migration',
    area: '/admin/migration',
    priority: 'Must',
    title:
      "Support ingestion of a customer's existing procurement and contract records from prior systems — structured exports, database extracts or document repositories — as...",
    batch: 'B1',
  }, // TODO(FR-0655)
  {
    id: 'FR-0660',
    tier: 'S',
    status: 'BUILT',
    category: 'Data Migration',
    area: '/admin/migration',
    priority: 'Must',
    title:
      "Migrated records shall be automatically linked into the platform's native record structures — for example a migrated contract linked to its migrated originating...",
    batch: 'B1',
  }, // TODO(FR-0660)
  {
    id: 'FR-0665',
    tier: 'S',
    status: 'BUILT',
    category: 'Data Migration',
    area: '/admin/migration',
    priority: 'Must',
    title:
      'Run a data validation and profiling pass on migrated records prior to cutover, producing an exceptions report covering missing mandatory fields, unparseable dates or...',
    batch: 'B1',
  }, // TODO(FR-0665)
  {
    id: 'FR-0670',
    tier: 'S',
    status: 'BUILT',
    category: 'Data Migration',
    area: '/admin/migration',
    priority: 'Must',
    title:
      'Migrated historical records shall be distinguishable from natively created records via a source-system flag, while remaining fully searchable, reportable and subject...',
    batch: 'B1',
  }, // TODO(FR-0670)
  {
    id: 'FR-0675',
    tier: 'S',
    status: 'BUILT',
    category: 'Data Migration',
    area: '/admin/migration',
    priority: 'Must',
    title:
      'Migration shall include AI extraction from legacy contracts of obligations, KPIs, deliverables, SLAs and optional extensions, with contract management records and...',
    batch: 'B1',
  }, // TODO(FR-0675)
  {
    id: 'FR-0690',
    tier: 'S',
    status: 'BUILT',
    category: 'Admin & Configuration',
    area: '/admin',
    priority: 'Must',
    title:
      "Changes made within the administrative configuration interface shall be captured in the platform's audit trail, recording the administrator, the setting changed, and...",
    batch: 'B1',
  }, // TODO(FR-0690)
  {
    id: 'FR-0695',
    tier: 'S',
    status: 'BUILT',
    category: 'Admin & Configuration',
    area: '/admin',
    priority: 'Must',
    title:
      'Auto-generate sequential procurement numbers in a format configurable by the customer, with the procurement number defaulting to the contract number unless the...',
    batch: 'B1',
  }, // TODO(FR-0695)
  {
    id: 'FR-0700',
    tier: 'S',
    status: 'BUILT',
    category: 'Admin & Configuration',
    area: '/admin',
    priority: 'Must',
    title:
      "Field labels shall be configurable so that platform fields can be aligned to each customer's existing system naming conventions for both push and pull, and inbound...",
    batch: 'B1',
  }, // TODO(FR-0700)
  {
    id: 'FR-0705',
    tier: 'S',
    status: 'BUILT',
    category: 'Admin & Configuration',
    area: '/admin',
    priority: 'Must',
    title:
      'Provide a library of end-to-end workflows (for example simple, intermediate, complex, and a high-risk/high-value workflow with added governance such as board...',
    batch: 'B1',
  }, // TODO(FR-0705)
  {
    id: 'FR-0710',
    tier: 'S',
    status: 'BUILT',
    category: 'Admin & Configuration',
    area: '/admin',
    priority: 'Must',
    title:
      'Offer two workflow design modes: a configurable out-of-the-box workflow set in which predefined fields can be included or excluded and administrators can define...',
    batch: 'B1',
  }, // TODO(FR-0710)
  {
    id: 'FR-0720',
    tier: 'S',
    status: 'BUILT',
    category: 'Admin & Configuration',
    area: '/admin',
    priority: 'Must',
    title:
      'Support configurable mandatory checkpoints that an enterprise may choose to enforce or relax — for example requiring all conflict-of-interest declarations to be...',
    batch: 'B1',
  }, // TODO(FR-0720)
  {
    id: 'FR-0725',
    tier: 'S',
    status: 'BUILT',
    category: 'Admin & Configuration',
    area: '/admin',
    priority: 'Must',
    title:
      "Delegates shall be auto-populated for every workflow and every stage, with automatic re-nomination where a stage's value exceeds the current delegate's authority and...",
    batch: 'B1',
  }, // TODO(FR-0725)
  {
    id: 'FR-0730',
    tier: 'S',
    status: 'BUILT',
    category: 'Admin & Configuration',
    area: '/admin',
    priority: 'Should',
    title:
      'Users shall be able to add or remove workflow steps for a specific procurement where the delegate has approved that variation to the standard process',
    batch: 'B1',
  }, // TODO(FR-0730)
  {
    id: 'FR-0735',
    tier: 'S',
    status: 'PLANNED',
    category: 'Collaboration & AI Authoring',
    area: '/app/collaboration',
    priority: 'Must',
    title:
      'Approved users shall be able to work on the same document concurrently, including editing different fields within the platform at the same time, without overwriting...',
  }, // TODO(FR-0735)
  {
    id: 'FR-0740',
    tier: 'S',
    status: 'PLANNED',
    category: 'Collaboration & AI Authoring',
    area: '/app/collaboration',
    priority: 'Must',
    title:
      "Provide tracked changes, version comparison highlighting what has changed, or an AI summary of changes since the user's last view, across all documents and fields,...",
  }, // TODO(FR-0740)
  {
    id: 'FR-0750',
    tier: 'S',
    status: 'PLANNED',
    category: 'Collaboration & AI Authoring',
    area: '/app/collaboration',
    priority: 'Must',
    title:
      'Where the AI has selected an incorrect template, the user shall be able to instruct a change of template in plain language and the AI shall re-populate the newly...',
  }, // TODO(FR-0750)
  {
    id: 'FR-0755',
    tier: 'S',
    status: 'PLANNED',
    category: 'Collaboration & AI Authoring',
    area: '/app/collaboration',
    priority: 'Should',
    title:
      'The AI shall generate a draft risk assessment appropriate to the workflow, proposing candidate risks for the user to mark as applicable or not, prompting the user to...',
  }, // TODO(FR-0755)
  {
    id: 'FR-0760',
    tier: 'S',
    status: 'PLANNED',
    category: 'Collaboration & AI Authoring',
    area: '/app/collaboration',
    priority: 'Must',
    title:
      'The AI shall summarise supplier responses, covering description of pricing, dates, variations from the tender document, and a summary of pros and cons',
  }, // TODO(FR-0760)
  {
    id: 'FR-0765',
    tier: 'S',
    status: 'PLANNED',
    category: 'Collaboration & AI Authoring',
    area: '/app/collaboration',
    priority: 'Should',
    title:
      'Periodically regenerate and refresh standardised best-practice content — for example multiple variants of common role descriptions across categories, sectors,...',
  }, // TODO(FR-0765)
  {
    id: 'FR-0770',
    tier: 'S',
    status: 'PLANNED',
    category: 'Collaboration & AI Authoring',
    area: '/app/collaboration',
    priority: 'Must',
    title:
      'Users shall be able to advance a procurement from one phase to the next using plain language, and the AI shall also advance the tracker automatically on detecting...',
  }, // TODO(FR-0770)
  {
    id: 'FR-0775',
    tier: 'S',
    status: 'PLANNED',
    category: 'Collaboration & AI Authoring',
    area: '/app/collaboration',
    priority: 'Should',
    title:
      'Adding or removing users from a procurement or evaluation committee shall be possible by instructing the AI or typing a name, with a disambiguating picker presented...',
  }, // TODO(FR-0775)
  {
    id: 'FR-0790',
    tier: 'D',
    status: 'DEFERRED',
    category: 'Future Scope',
    area: null,
    priority: "Won't",
    title:
      'Supplier ratings and performance scoring, including enterprise-rates-supplier and supplier-rates-enterprise, with configurable visibility of ratings',
  }, // DEFERRED(FR-0790)
  {
    id: 'FR-0795',
    tier: 'D',
    status: 'DEFERRED',
    category: 'Future Scope',
    area: null,
    priority: "Won't",
    title: 'Duplicate supplier detection across the supplier master',
  }, // DEFERRED(FR-0795)
  {
    id: 'FR-0800',
    tier: 'D',
    status: 'DEFERRED',
    category: 'Future Scope',
    area: null,
    priority: "Won't",
    title:
      'Supplier risk, resilience and ESG scoring — combining performance, financial health, geopolitical exposure, cyber and compliance checks and operational disruption...',
  }, // DEFERRED(FR-0800)
  {
    id: 'FR-0805',
    tier: 'D',
    status: 'DEFERRED',
    category: 'Future Scope',
    area: null,
    priority: "Won't",
    title:
      'Lessons-learned capture, with AI recall of relevant lessons on comparable future procurements by type, size or category',
  }, // DEFERRED(FR-0805)
  {
    id: 'FR-0810',
    tier: 'D',
    status: 'DEFERRED',
    category: 'Future Scope',
    area: null,
    priority: "Won't",
    title:
      'Foreign currency and FX management — handling multiple currencies, conversion between local and international currencies, annual or live forex rate feeds, and...',
  }, // DEFERRED(FR-0810)
  {
    id: 'FR-0815',
    tier: 'D',
    status: 'DEFERRED',
    category: 'Future Scope',
    area: null,
    priority: "Won't",
    title:
      'HR system integration for live delegate changes, position changes, resignations and new starters, with automatic addition and removal of staff by team and level',
  }, // DEFERRED(FR-0815)
  {
    id: 'FR-0820',
    tier: 'D',
    status: 'DEFERRED',
    category: 'Future Scope',
    area: null,
    priority: "Won't",
    title:
      'Guided buying from approved supplier lists, catalogues and contracts, and autonomous AI-initiated sourcing for commodity or low-value repetitive goods and services...',
  }, // DEFERRED(FR-0820)
  {
    id: 'FR-0825',
    tier: 'D',
    status: 'DEFERRED',
    category: 'Future Scope',
    area: null,
    priority: "Won't",
    title:
      'Native mobile application providing procurement request submission, supplier portal access, evaluator scoring, plain-language amendments, AI search, app-specific...',
  }, // DEFERRED(FR-0825)
  {
    id: 'FR-0830',
    tier: 'D',
    status: 'DEFERRED',
    category: 'Future Scope',
    area: null,
    priority: "Won't",
    title:
      'Advanced legal functions in plain language — redaction of nominated sections, redlining, clause insertion at a nominated section — plus collaboration portals for...',
  }, // DEFERRED(FR-0830)
  {
    id: 'FR-0835',
    tier: 'D',
    status: 'DEFERRED',
    category: 'Future Scope',
    area: null,
    priority: "Won't",
    title:
      'Gamification of the request and phase-progression experience, including themed progress characters, completion celebrations and progress-to-completion visualisations',
  }, // DEFERRED(FR-0835)
  {
    id: 'FR-0840',
    tier: 'D',
    status: 'DEFERRED',
    category: 'Future Scope',
    area: null,
    priority: "Won't",
    title:
      'Spend optimisation and benefits/cost analysis — contract consolidation opportunities, duplicate contract detection, rate-card optimisation, price variance analysis,...',
  }, // DEFERRED(FR-0840)
  {
    id: 'FR-0845',
    tier: 'D',
    status: 'DEFERRED',
    category: 'Future Scope',
    area: null,
    priority: "Won't",
    title:
      'Future commitment analysis reporting the value committed for future financial years, split by cost centre and business unit, with AI estimation and explicitly stated...',
  }, // DEFERRED(FR-0845)
  {
    id: 'FR-0850',
    tier: 'D',
    status: 'DEFERRED',
    category: 'Future Scope',
    area: null,
    priority: "Won't",
    title:
      'Extended dashboard personalisation — user-selected placement of charts and metrics (for example savings, spend tracker, ESG compliance) and selectable visual styles...',
  }, // DEFERRED(FR-0850)
  {
    id: 'FR-0855',
    tier: 'D',
    status: 'DEFERRED',
    category: 'Future Scope',
    area: null,
    priority: "Won't",
    title: 'Expansion into adjacent domains — audit, risk and compliance management',
  }, // DEFERRED(FR-0855)
  {
    id: 'FR-0860',
    tier: 'D',
    status: 'DEFERRED',
    category: 'Future Scope',
    area: null,
    priority: "Won't",
    title:
      'Business continuity features — SMS and email alerting with response trackers, and phone location tracking during business continuity events',
  }, // DEFERRED(FR-0860)
  {
    id: 'FR-0865',
    tier: 'D',
    status: 'DEFERRED',
    category: 'Future Scope',
    area: null,
    priority: "Won't",
    title:
      'Defence-sector-grade data isolation, providing project-level encryption that is invisible outside an assigned sourcing group',
  }, // DEFERRED(FR-0865)
  {
    id: 'FR-0870',
    tier: 'D',
    status: 'DEFERRED',
    category: 'Future Scope',
    area: null,
    priority: "Won't",
    title:
      'Real-time, rather than periodic or batched, AI updating of evaluation report and contract management artefacts',
  }, // DEFERRED(FR-0870)
  {
    id: 'FR-0875',
    tier: 'D',
    status: 'DEFERRED',
    category: 'Future Scope',
    area: null,
    priority: "Won't",
    title: 'Direct integration with third-party finance/ERP systems for payment execution',
  }, // DEFERRED(FR-0875)
  {
    id: 'FR-0880',
    tier: 'D',
    status: 'DEFERRED',
    category: 'Future Scope',
    area: null,
    priority: "Won't",
    title: 'Real-time web-scale searching of external AI models against live institutional data',
  }, // DEFERRED(FR-0880)
  {
    id: 'NFR-P01',
    tier: 'D',
    status: 'DEFERRED',
    category: 'Performance & Response Time',
    area: null,
    priority: 'Must',
    title:
      'Early-stage artefacts, in particular the procurement plan, shall update live or near-real-time from the AI conversation, at least for the section the user is...',
  }, // DEFERRED(NFR-P01)
  {
    id: 'NFR-P02',
    tier: 'D',
    status: 'DEFERRED',
    category: 'Performance & Response Time',
    area: null,
    priority: 'Should',
    title:
      'Later-stage artefacts such as evaluation reports and contract management records may update on a delayed or batched basis in order to manage AI processing cost',
  }, // DEFERRED(NFR-P02)
  {
    id: 'NFR-P04',
    tier: 'D',
    status: 'DEFERRED',
    category: 'Performance & Response Time',
    area: null,
    priority: 'Must',
    title:
      'ERP budget checks and inventory look-ups shall return a clearance status to the user within the intake conversation without a perceptible workflow interruption',
  }, // DEFERRED(NFR-P04)
  {
    id: 'NFR-P05',
    tier: 'D',
    status: 'DEFERRED',
    category: 'Performance & Response Time',
    area: null,
    priority: 'Must',
    title:
      'Reporting and analytics shall run on a data layer decoupled from the core transactional databases, so that complex analytical queries do not degrade transactional...',
  }, // DEFERRED(NFR-P05)
  {
    id: 'NFR-SC01',
    tier: 'D',
    status: 'DEFERRED',
    category: 'Scalability',
    area: null,
    priority: 'Must',
    title:
      'Support multiple enterprise tenants, with request throttling and usage plans applied per customer tenant',
  }, // DEFERRED(NFR-SC01)
  {
    id: 'NFR-SC02',
    tier: 'D',
    status: 'DEFERRED',
    category: 'Scalability',
    area: null,
    priority: 'Must',
    title:
      'Compute shall scale elastically for document generation, evaluation scoring and dynamic clause assembly workloads without manual capacity intervention',
  }, // DEFERRED(NFR-SC02)
  {
    id: 'NFR-SC03',
    tier: 'D',
    status: 'DEFERRED',
    category: 'Scalability',
    area: null,
    priority: 'Must',
    title: 'The analytics warehouse shall scale independently of the transactional databases',
  }, // DEFERRED(NFR-SC03)
  {
    id: 'NFR-SC04',
    tier: 'D',
    status: 'DEFERRED',
    category: 'Scalability',
    area: null,
    priority: 'Must',
    title:
      'The tender portal shall absorb peak submission load in the period immediately before tender close without rejecting or corrupting in-flight submissions',
  }, // DEFERRED(NFR-SC04)
  {
    id: 'NFR-AV01',
    tier: 'D',
    status: 'DEFERRED',
    category: 'Availability & Reliability',
    area: null,
    priority: 'Must',
    title: 'Target 99.9% availability.',
  }, // DEFERRED(NFR-AV01)
  {
    id: 'NFR-AV02',
    tier: 'D',
    status: 'DEFERRED',
    category: 'Availability & Reliability',
    area: null,
    priority: 'Must',
    title: 'Automated failover shall be provided for core services',
  }, // DEFERRED(NFR-AV02)
  {
    id: 'NFR-AV03',
    tier: 'D',
    status: 'DEFERRED',
    category: 'Availability & Reliability',
    area: null,
    priority: 'Must',
    title:
      'Integrations shall be resilient: webhook and event deliveries shall use idempotent retry handling, with reconciliation jobs to catch syncs missed while a target...',
  }, // DEFERRED(NFR-AV03)
  {
    id: 'NFR-AV04',
    tier: 'D',
    status: 'DEFERRED',
    category: 'Availability & Reliability',
    area: null,
    priority: 'Must',
    title:
      'Manual fallback workflows shall be available where ERP or legal-system integration is unavailable, delayed or unreliable, so that procurement can continue',
  }, // DEFERRED(NFR-AV04)
  {
    id: 'NFR-U04',
    tier: 'D',
    status: 'DEFERRED',
    category: 'Usability & Accessibility',
    area: null,
    priority: 'Should',
    title: 'Configurable drag-and-drop layout and design shall be available across every lifecycle phase',
  }, // DEFERRED(NFR-U04)
  {
    id: 'NFR-U05',
    tier: 'D',
    status: 'DEFERRED',
    category: 'Usability & Accessibility',
    area: null,
    priority: 'Should',
    title:
      'An approver shall be able to complete an approval action from an emailed link without a full platform sign-in, presented with a summary checklist view for that...',
  }, // DEFERRED(NFR-U05)
  {
    id: 'NFR-U08',
    tier: 'D',
    status: 'DEFERRED',
    category: 'Usability & Accessibility',
    area: null,
    priority: 'Should',
    title:
      'Where the AI cannot reliably action an in-field amendment, the user shall have a usable fallback path to achieve the change (for example copying content into the AI...',
  }, // DEFERRED(NFR-U08)
  {
    id: 'NFR-M01',
    tier: 'D',
    status: 'DEFERRED',
    category: 'Maintainability & Supportability',
    area: null,
    priority: 'Must',
    title:
      'All infrastructure shall be defined as code, enabling reproducible environments and configuration drift detection',
  }, // DEFERRED(NFR-M01)
  {
    id: 'NFR-M03',
    tier: 'D',
    status: 'DEFERRED',
    category: 'Maintainability & Supportability',
    area: null,
    priority: 'Must',
    title:
      'Centralised observability shall provide metrics, logs and alarms, including dashboards for AI response latency, ERP synchronisation failures and workflow error rates',
  }, // DEFERRED(NFR-M03)
  {
    id: 'NFR-M04',
    tier: 'D',
    status: 'DEFERRED',
    category: 'Maintainability & Supportability',
    area: null,
    priority: 'Should',
    title:
      'Distributed tracing shall be available end-to-end across microservices and serverless functions for latency bottleneck identification',
  }, // DEFERRED(NFR-M04)
  {
    id: 'NFR-M05',
    tier: 'D',
    status: 'DEFERRED',
    category: 'Maintainability & Supportability',
    area: null,
    priority: 'Must',
    title:
      'Tenant configuration — workflows, sub-workflows, templates, field labels, thresholds, alert settings and delegation mappings — shall be changeable by an authorised...',
  }, // DEFERRED(NFR-M05)
  {
    id: 'NFR-M06',
    tier: 'D',
    status: 'DEFERRED',
    category: 'Maintainability & Supportability',
    area: null,
    priority: 'Should',
    title:
      "The AI model layer shall be abstracted such that a tenant's approved model can be changed, or a new approved model added, through configuration rather than redevelopment",
  }, // DEFERRED(NFR-M06)
  {
    id: 'NFR-C01',
    tier: 'D',
    status: 'DEFERRED',
    category: 'Compatibility & Portability',
    area: null,
    priority: 'Must',
    title:
      'Support multiple, pluggable underlying AI models (for example enterprise-approved Amazon Bedrock models) so that each customer can meet its own AI governance policy',
  }, // DEFERRED(NFR-C01)
  {
    id: 'NFR-C02',
    tier: 'D',
    status: 'DEFERRED',
    category: 'Compatibility & Portability',
    area: null,
    priority: 'Must',
    title:
      'Synchronise budget, general ledger, cost-centre and organisational-unit data with connected ERP systems — SAP S/4HANA, Oracle Cloud Financials, Microsoft Dynamics 365...',
  }, // DEFERRED(NFR-C02)
  {
    id: 'NFR-C03',
    tier: 'D',
    status: 'DEFERRED',
    category: 'Compatibility & Portability',
    area: null,
    priority: 'Must',
    title:
      'Synchronise legal matter status, redlines and stage updates with connected enterprise legal systems (for example HighQ, Icertis) via event-driven, webhook-based...',
  }, // DEFERRED(NFR-C03)
  {
    id: 'NFR-C04',
    tier: 'D',
    status: 'DEFERRED',
    category: 'Compatibility & Portability',
    area: null,
    priority: 'Must',
    title:
      'Integrate with third-party e-signature providers, including DocuSign and Adobe Sign, including pre-population of signatory names and email addresses',
  }, // DEFERRED(NFR-C04)
  {
    id: 'NFR-C05',
    tier: 'D',
    status: 'DEFERRED',
    category: 'Compatibility & Portability',
    area: null,
    priority: 'Must',
    title:
      'Integrate with third-party sanctions-screening and insurance-verification providers via a resilient API layer',
  }, // DEFERRED(NFR-C05)
  {
    id: 'NFR-C06',
    tier: 'D',
    status: 'DEFERRED',
    category: 'Compatibility & Portability',
    area: null,
    priority: 'Should',
    title:
      'Where an enterprise requires documents to be held in its own repository (for example SharePoint), the platform shall be able to read from and write to that...',
  }, // DEFERRED(NFR-C06)
  {
    id: 'NFR-C07',
    tier: 'D',
    status: 'DEFERRED',
    category: 'Compatibility & Portability',
    area: null,
    priority: 'Should',
    title:
      'Support integration with major procurement/contract management, legal and ERP platforms and with multiple middleware products, with direct integration preferred over...',
  }, // DEFERRED(NFR-C07)
  {
    id: 'NFR-C08',
    tier: 'D',
    status: 'DEFERRED',
    category: 'Compatibility & Portability',
    area: null,
    priority: 'Should',
    title:
      'A supported browser and operating-system baseline shall be defined and published for internal users and for external suppliers',
  }, // DEFERRED(NFR-C08)
  {
    id: 'NFR-CA01',
    tier: 'D',
    status: 'DEFERRED',
    category: 'Capacity & Data Volume',
    area: null,
    priority: 'Must',
    title:
      "Support migration and ongoing storage of a customer's legacy estate, which the Detailed Design anticipates may comprise hundreds or thousands of contracts and...",
  }, // DEFERRED(NFR-CA01)
  {
    id: 'NFR-CA03',
    tier: 'D',
    status: 'DEFERRED',
    category: 'Capacity & Data Volume',
    area: null,
    priority: 'Must',
    title:
      'Audit event logs, AI conversation transcripts and document version history shall be retained for the full contract lifecycle plus the applicable statutory retention...',
  }, // DEFERRED(NFR-CA03)
  {
    id: 'NFR-CA04',
    tier: 'D',
    status: 'DEFERRED',
    category: 'Capacity & Data Volume',
    area: null,
    priority: 'Must',
    title:
      'Concurrent user volumes, tenant counts and document throughput shall be defined as sizing inputs for the platform',
  }, // DEFERRED(NFR-CA04)
  {
    id: 'NFR-DR01',
    tier: 'D',
    status: 'DEFERRED',
    category: 'Disaster Recovery & Business Continuity',
    area: null,
    priority: 'Must',
    title:
      'Regular, tested backups shall be taken of all procurement, evaluation, contract and analytics data, held in a secure store separate from the primary platform for...',
  }, // DEFERRED(NFR-DR01)
  {
    id: 'NFR-DR02',
    tier: 'D',
    status: 'DEFERRED',
    category: 'Disaster Recovery & Business Continuity',
    area: null,
    priority: 'Must',
    title:
      'Recovery Time Objective and Recovery Point Objective shall be defined and demonstrated by test for each service tier',
  }, // DEFERRED(NFR-DR02)
  {
    id: 'NFR-DR03',
    tier: 'D',
    status: 'DEFERRED',
    category: 'Disaster Recovery & Business Continuity',
    area: null,
    priority: 'Must',
    title:
      'Restore procedures shall be tested periodically, with the test outcome recorded, rather than relying on backup completion alone as evidence of recoverability',
  }, // DEFERRED(NFR-DR03)
  {
    id: 'NFR-L01',
    tier: 'D',
    status: 'DEFERRED',
    category: 'Legal',
    area: null,
    priority: 'Must',
    title:
      'Public-sector statutory timing rules shall be enforced, including minimum publication-to-close windows such as the 25-day window under WTO Government Procurement rules',
  }, // DEFERRED(NFR-L01)
  {
    id: 'NFR-L02',
    tier: 'D',
    status: 'DEFERRED',
    category: 'Legal',
    area: null,
    priority: 'Must',
    title:
      'Public-sector statutory disclosure obligations shall be enforced for contract modifications exceeding a defined value-change threshold',
  }, // DEFERRED(NFR-L02)
  {
    id: 'NFR-L03',
    tier: 'D',
    status: 'DEFERRED',
    category: 'Legal',
    area: null,
    priority: 'Must',
    title: 'The native electronic/digital signature capability shall be aligned to eIDAS',
  }, // DEFERRED(NFR-L03)
  {
    id: 'NFR-L04',
    tier: 'D',
    status: 'DEFERRED',
    category: 'Legal',
    area: null,
    priority: 'Must',
    title:
      'Signed contract records shall be retained permanently and remain recoverable, with logical delete only, and the audit trail shall be of sufficient completeness to...',
  }, // DEFERRED(NFR-L04)
  {
    id: 'NFR-R01',
    tier: 'D',
    status: 'DEFERRED',
    category: 'Regulatory & Environmental',
    area: null,
    priority: 'Must',
    title: "Institutional and customer data shall remain within the customer's own tenancy or cloud boundary",
  }, // DEFERRED(NFR-R01)
  {
    id: 'NFR-R02',
    tier: 'D',
    status: 'DEFERRED',
    category: 'Regulatory & Environmental',
    area: null,
    priority: 'Must',
    title:
      'Data shall be stored in the country the enterprise nominates, with the platform supporting a customer election to host in a specific national region',
  }, // DEFERRED(NFR-R02)
  {
    id: 'NFR-R03',
    tier: 'D',
    status: 'DEFERRED',
    category: 'Regulatory & Environmental',
    area: null,
    priority: 'Must',
    title:
      'AI population of fields shall combine in-house data with periodically refreshed external best-practice content, refreshed on a weekly or monthly cycle, without...',
  }, // DEFERRED(NFR-R03)
  {
    id: 'NFR-R04',
    tier: 'D',
    status: 'DEFERRED',
    category: 'Regulatory & Environmental',
    area: null,
    priority: 'Should',
    title:
      'Support IRAP assessment and alignment to the Australian Government Information Security Manual for public-sector customers',
  }, // DEFERRED(NFR-R04)
  {
    id: 'NFR-R05',
    tier: 'D',
    status: 'DEFERRED',
    category: 'Regulatory & Environmental',
    area: null,
    priority: 'Should',
    title:
      'ESG and socio-economic planning data captured at plan stage — carbon offset ceilings, domestic and regional labour content ratios and diversity-owned vendor...',
  }, // DEFERRED(NFR-R05)
  {
    id: 'NFR-R06',
    tier: 'D',
    status: 'DEFERRED',
    category: 'Regulatory & Environmental',
    area: null,
    priority: 'Must',
    title:
      'Probity of the sourcing process shall be demonstrable to an external auditor, evidenced by segregation of duties, conflict-of-interest records, isolated evaluation,...',
  }, // DEFERRED(NFR-R06)
  {
    id: 'SEC-A01',
    tier: 'S',
    status: 'BUILT',
    category: 'Authentication & Identity',
    area: '/admin/users',
    priority: 'Must',
    title:
      'Multi-factor authentication shall be enforced for platform user accounts, supporting TOTP and SMS one-time codes',
    batch: 'B1',
  }, // TODO(SEC-A01)
  {
    id: 'SEC-A02',
    tier: 'S',
    status: 'BUILT',
    category: 'Authentication & Identity',
    area: '/admin/users',
    priority: 'Must',
    title:
      'Single sign-on shall be supported via enterprise identity providers using SAML or OIDC federation, with identity management capabilities for enterprise customers',
    batch: 'B1',
  }, // TODO(SEC-A02)
  {
    id: 'SEC-A03',
    tier: 'S',
    status: 'PARTIAL',
    category: 'Authentication & Identity',
    area: '/admin/users',
    priority: 'Must',
    title:
      'External suppliers and tenderers shall authenticate against a separate, federated identity pool, isolated from the internal user directory',
  }, // TODO(SEC-A03)
  {
    id: 'SEC-A04',
    tier: 'S',
    status: 'BUILT',
    category: 'Authentication & Identity',
    area: '/admin/users',
    priority: 'Must',
    title:
      'Where an organisation requires it, the platform shall enforce SSO or mobile-device-based authentication for all actions, disabling any link-based approval path that...',
    batch: 'B1',
  }, // TODO(SEC-A04)
  {
    id: 'SEC-A05',
    tier: 'S',
    status: 'BUILT',
    category: 'Authentication & Identity',
    area: '/admin/users',
    priority: 'Should',
    title:
      'Identity grants for evaluation committee members, auditors, advisors and probity officers shall be time-bound, expiring automatically at a configured date or on a...',
    batch: 'B1',
  }, // TODO(SEC-A05)
  {
    id: 'SEC-A06',
    tier: 'S',
    status: 'BUILT',
    category: 'Authentication & Identity',
    area: '/admin/users',
    priority: 'Must',
    title:
      'Supplier contact access shall be reassignable and de-provisioned when a contact leaves the supplier organisation, so that departed personnel retain no access',
    batch: 'B1',
  }, // TODO(SEC-A06)
  {
    id: 'SEC-AC09',
    tier: 'D',
    status: 'DEFERRED',
    category: 'Authorisation & Access Control',
    area: null,
    priority: 'Must',
    title:
      'Enterprises shall be able to define access policies that override the default hierarchy — for example restricting the procurement pack to evaluation committee...',
  }, // DEFERRED(SEC-AC09)
  {
    id: 'SEC-AC10',
    tier: 'D',
    status: 'DEFERRED',
    category: 'Authorisation & Access Control',
    area: null,
    priority: 'Should',
    title:
      'Supplier bank account details shall be restricted to a finance-only access segment, excluded from procurement and legal roles, with the option to pass the data...',
  }, // DEFERRED(SEC-AC10)
  {
    id: 'SEC-D01',
    tier: 'D',
    status: 'DEFERRED',
    category: 'Data Protection & Privacy',
    area: null,
    priority: 'Must',
    title: 'All data shall be encrypted in transit and at rest using industry-standard algorithms',
  }, // DEFERRED(SEC-D01)
  {
    id: 'SEC-D02',
    tier: 'D',
    status: 'DEFERRED',
    category: 'Data Protection & Privacy',
    area: null,
    priority: 'Must',
    title: 'Customer-managed encryption keys shall be supported where required, with automatic key rotation',
  }, // DEFERRED(SEC-D02)
  {
    id: 'SEC-D03',
    tier: 'D',
    status: 'DEFERRED',
    category: 'Data Protection & Privacy',
    area: null,
    priority: 'Must',
    title:
      'Supplier bid submissions shall be encrypted at the point of upload and shall remain inaccessible to any internal user — including database administrators and system...',
  }, // DEFERRED(SEC-D03)
  {
    id: 'SEC-D04',
    tier: 'D',
    status: 'DEFERRED',
    category: 'Data Protection & Privacy',
    area: null,
    priority: 'Must',
    title:
      'Per-tenant envelope encryption shall be applied to the bid box, so that even privileged platform operators cannot decrypt submissions before closing time',
  }, // DEFERRED(SEC-D04)
  {
    id: 'SEC-D05',
    tier: 'D',
    status: 'DEFERRED',
    category: 'Data Protection & Privacy',
    area: null,
    priority: 'Must',
    title: 'Enterprise data shall never be exposed to public or general-availability AI endpoints',
  }, // DEFERRED(SEC-D05)
  {
    id: 'SEC-D06',
    tier: 'D',
    status: 'DEFERRED',
    category: 'Data Protection & Privacy',
    area: null,
    priority: 'Must',
    title:
      'AI conversation content shall be afforded the same protection, residency and retention controls as structured platform data',
  }, // DEFERRED(SEC-D06)
  {
    id: 'SEC-D07',
    tier: 'D',
    status: 'DEFERRED',
    category: 'Data Protection & Privacy',
    area: null,
    priority: 'Must',
    title:
      'Sensitive data — including banking details, personal information and defence-adjacent project data — shall be automatically discoverable and classifiable, feeding the...',
  }, // DEFERRED(SEC-D07)
  {
    id: 'SEC-D08',
    tier: 'D',
    status: 'DEFERRED',
    category: 'Data Protection & Privacy',
    area: null,
    priority: 'Must',
    title:
      'Personal information shall be handled in accordance with the Australian Privacy Principles under the Privacy Act 1988, including collection notices, use and...',
  }, // DEFERRED(SEC-D08)
  {
    id: 'SEC-D09',
    tier: 'D',
    status: 'DEFERRED',
    category: 'Data Protection & Privacy',
    area: null,
    priority: 'Must',
    title:
      'Cross-border disclosure controls shall prevent customer data leaving the nominated country or region, including for backup, logging and AI processing paths',
  }, // DEFERRED(SEC-D09)
  {
    id: 'SEC-D10',
    tier: 'D',
    status: 'DEFERRED',
    category: 'Data Protection & Privacy',
    area: null,
    priority: 'Must',
    title:
      "Tenant and data isolation shall be such that compromise of one tenant or component does not expose other tenants' or users' data",
  }, // DEFERRED(SEC-D10)
  {
    id: 'SEC-D11',
    tier: 'D',
    status: 'DEFERRED',
    category: 'Data Protection & Privacy',
    area: null,
    priority: 'Should',
    title:
      "Support the enterprise's elected storage topology — platform-hosted, hosted in the enterprise's own cloud, or hybrid — with equivalent protection applied in each",
  }, // DEFERRED(SEC-D11)
  {
    id: 'SEC-L02',
    tier: 'D',
    status: 'DEFERRED',
    category: 'Audit Logging & Monitoring',
    area: null,
    priority: 'Must',
    title:
      'All administrative and data-plane actions on the underlying cloud platform shall be logged immutably, feeding the platform audit trail and probity reporting',
  }, // DEFERRED(SEC-L02)
  {
    id: 'SEC-L06',
    tier: 'D',
    status: 'DEFERRED',
    category: 'Audit Logging & Monitoring',
    area: null,
    priority: 'Must',
    title:
      "Continuous threat monitoring shall detect anomalous access patterns across the platform's cloud accounts, with findings routed to the security team",
  }, // DEFERRED(SEC-L06)
  {
    id: 'SEC-L07',
    tier: 'D',
    status: 'DEFERRED',
    category: 'Audit Logging & Monitoring',
    area: null,
    priority: 'Must',
    title:
      'A compliance-grade probity and audit-trail export shall be available to auditors, providing an unalterable history of evaluator access, conflict-of-interest...',
  }, // DEFERRED(SEC-L07)
  {
    id: 'SEC-L08',
    tier: 'D',
    status: 'DEFERRED',
    category: 'Audit Logging & Monitoring',
    area: null,
    priority: 'Must',
    title:
      'Configuration compliance shall be continuously monitored with automated remediation, enforcing encryption, MFA and the absence of publicly accessible storage',
  }, // DEFERRED(SEC-L08)
  {
    id: 'SEC-AP01',
    tier: 'D',
    status: 'DEFERRED',
    category: 'Application Security',
    area: null,
    priority: 'Must',
    title:
      'A web application firewall shall protect the tender portal and supplier portal from common web exploits',
  }, // DEFERRED(SEC-AP01)
  {
    id: 'SEC-AP02',
    tier: 'D',
    status: 'DEFERRED',
    category: 'Application Security',
    area: null,
    priority: 'Must',
    title: 'Always-on denial-of-service protection shall be provided for internet-facing portals',
  }, // DEFERRED(SEC-AP02)
  {
    id: 'SEC-AP04',
    tier: 'D',
    status: 'DEFERRED',
    category: 'Application Security',
    area: null,
    priority: 'Must',
    title: 'Every uploaded file shall be scanned for malware at the point of upload',
  }, // DEFERRED(SEC-AP04)
  {
    id: 'SEC-AP05',
    tier: 'D',
    status: 'DEFERRED',
    category: 'Application Security',
    area: null,
    priority: 'Must',
    title:
      'Penetration testing shall be conducted before go-live and periodically thereafter, with findings remediated and retested',
  }, // DEFERRED(SEC-AP05)
  {
    id: 'SEC-AP08',
    tier: 'D',
    status: 'DEFERRED',
    category: 'Application Security',
    area: null,
    priority: 'Should',
    title:
      'AI-specific application controls shall be implemented, including prompt-injection resistance for content ingested from supplier submissions and uploaded documents,...',
  }, // DEFERRED(SEC-AP08)
  {
    id: 'SEC-N01',
    tier: 'D',
    status: 'DEFERRED',
    category: 'Infrastructure & Network Security',
    area: null,
    priority: 'Must',
    title:
      'Implement government-level security protocols appropriate to public-sector customers and shall be assessed against the applicable control set',
  }, // DEFERRED(SEC-N01)
  {
    id: 'SEC-N02',
    tier: 'D',
    status: 'DEFERRED',
    category: 'Infrastructure & Network Security',
    area: null,
    priority: 'Must',
    title:
      'Network segmentation shall isolate internet-facing portal components from core transactional databases and document stores',
  }, // DEFERRED(SEC-N02)
  {
    id: 'SEC-N03',
    tier: 'D',
    status: 'DEFERRED',
    category: 'Infrastructure & Network Security',
    area: null,
    priority: 'Must',
    title:
      'Credentials for third-party ERP, legal-system, sanctions-screening and e-signature integrations shall be held in a managed secret store with automatic rotation',
  }, // DEFERRED(SEC-N03)
  {
    id: 'SEC-N04',
    tier: 'D',
    status: 'DEFERRED',
    category: 'Infrastructure & Network Security',
    area: null,
    priority: 'Must',
    title: 'Document storage shall have no public read access',
  }, // DEFERRED(SEC-N04)
  {
    id: 'SEC-N05',
    tier: 'D',
    status: 'DEFERRED',
    category: 'Infrastructure & Network Security',
    area: null,
    priority: 'Must',
    title:
      'Backups shall be encrypted and access-controlled to the same standard as primary data, and shall be held within the nominated data-residency boundary',
  }, // DEFERRED(SEC-N05)
  {
    id: 'SEC-IR01',
    tier: 'D',
    status: 'DEFERRED',
    category: 'Incident Response & Vulnerability Management',
    area: null,
    priority: 'Must',
    title:
      'A documented incident response playbook shall be maintained, covering supplier data breach scenarios including exposure of bank details and bid submissions',
  }, // DEFERRED(SEC-IR01)
  {
    id: 'SEC-IR02',
    tier: 'D',
    status: 'DEFERRED',
    category: 'Incident Response & Vulnerability Management',
    area: null,
    priority: 'Must',
    title:
      'Technical vulnerabilities shall be monitored, triaged and remediated against defined severity-based service levels, with critical findings blocking pipeline deployment',
  }, // DEFERRED(SEC-IR02)
  {
    id: 'SEC-IR03',
    tier: 'D',
    status: 'DEFERRED',
    category: 'Incident Response & Vulnerability Management',
    area: null,
    priority: 'Must',
    title:
      'Threat detection and security findings shall be routed to a named security owner with defined acknowledgement and response times',
  }, // DEFERRED(SEC-IR03)
  {
    id: 'SEC-IR04',
    tier: 'D',
    status: 'DEFERRED',
    category: 'Incident Response & Vulnerability Management',
    area: null,
    priority: 'Must',
    title:
      'A business continuity and ICT readiness plan shall be maintained and tested periodically, covering loss of the platform, loss of an integrated ERP or legal system,...',
  }, // DEFERRED(SEC-IR04)
  {
    id: 'SEC-IR05',
    tier: 'D',
    status: 'DEFERRED',
    category: 'Incident Response & Vulnerability Management',
    area: null,
    priority: 'Must',
    title:
      'Eligible data breach assessment and notification obligations shall be met, with a defined process for assessing and notifying affected individuals and the regulator',
  }, // DEFERRED(SEC-IR05)
  {
    id: 'SEC-TP01',
    tier: 'D',
    status: 'DEFERRED',
    category: 'Third-Party & Vendor Security',
    area: null,
    priority: 'Must',
    title:
      'Automated sanctions and watchlist screening (for example OFAC, EU Sanctions, INTERPOL) shall be performed on suppliers during onboarding, with document access...',
  }, // DEFERRED(SEC-TP01)
  {
    id: 'SEC-TP02',
    tier: 'D',
    status: 'DEFERRED',
    category: 'Third-Party & Vendor Security',
    area: null,
    priority: 'Must',
    title:
      'Sanctions and financial risk checks shall be re-run on the counterparty where contract negotiations extend beyond 30 days, before execution can proceed',
  }, // DEFERRED(SEC-TP02)
  {
    id: 'SEC-TP03',
    tier: 'D',
    status: 'DEFERRED',
    category: 'Third-Party & Vendor Security',
    area: null,
    priority: 'Must',
    title:
      'Vendor legal name, tax registration and banking details shall be verified against ERP or vetted records before signature options unlock',
  }, // DEFERRED(SEC-TP03)
  {
    id: 'SEC-TP04',
    tier: 'D',
    status: 'DEFERRED',
    category: 'Third-Party & Vendor Security',
    area: null,
    priority: 'Must',
    title:
      'Where middleware is used for integration, it shall not constitute a weaker security link on either the platform-to-middleware or the enterprise-to-middleware leg, and...',
  }, // DEFERRED(SEC-TP04)
  {
    id: 'SEC-TP05',
    tier: 'D',
    status: 'DEFERRED',
    category: 'Third-Party & Vendor Security',
    area: null,
    priority: 'Must',
    title:
      'Supplier insurance and compliance certificate currency shall be monitored, with a transactional hold blocking new purchase orders where mandatory cover has lapsed',
  }, // DEFERRED(SEC-TP05)
  {
    id: 'SEC-TP06',
    tier: 'D',
    status: 'DEFERRED',
    category: 'Third-Party & Vendor Security',
    area: null,
    priority: 'Must',
    title:
      'Cloud service provider security responsibilities shall be documented and reviewed under a shared responsibility model, identifying which controls are inherited and...',
  }, // DEFERRED(SEC-TP06)
  {
    id: 'SEC-TP07',
    tier: 'D',
    status: 'DEFERRED',
    category: 'Third-Party & Vendor Security',
    area: null,
    priority: 'Must',
    title:
      "Third-party AI model providers shall be assessed and approved against each tenant's AI governance policy before being enabled for that tenant",
  }, // DEFERRED(SEC-TP07)
  {
    id: 'SEC-TP08',
    tier: 'D',
    status: 'DEFERRED',
    category: 'Third-Party & Vendor Security',
    area: null,
    priority: 'Should',
    title:
      "Where legacy data migration is performed by a third party or requires extracts to leave the customer's environment, the transfer and handling shall be governed by the...",
  }, // DEFERRED(SEC-TP08)
];
