/**
 * SEC-L02: platform administrative actions are logged immutably and the log can be checked by people who are not administrators.
 *
 * What already existed (migration 0001, audit-service.ts): one hash chain per tenant (sequence, prev_hash, hash over the
 * canonical content), appended inside the business transaction, with UPDATE/DELETE/TRUNCATE refused to the application role by
 * grants and to everyone (the owner too) by triggers. What this adds:
 *   - `audit_event.category`, generated by the database (migration 0026): ADMIN for the administrative action families and for
 *     anything an administrator does, else GENERAL. It cannot be written, so an event cannot be moved in or out of the class.
 *   - a database trigger that refuses an insert whose prev_hash is not the tenant's latest hash (no gaps, no forks);
 *   - GET /audit/admin-chain: the whole chain is re-computed (not trusted) and the first broken link reported, together with the
 *     administrative-event count and head; readable by PROBITY, EXEC and ADMIN, so administrators are not the only verifiers;
 *   - POST /audit/admin-chain/verify: the same check, kept as an append-only record and an audit event.
 *
 * The administrative events are a subset of the tenant chain, not a second chain: one chain cannot be forked into two stories,
 * and the verification covers every event in it. `adminDigest` is a SHA-256 over the administrative events' hashes in order, a
 * short value two verifiers can compare.
 */
import { createHash } from 'node:crypto';
import { and, asc, desc, eq, gt, sql } from 'drizzle-orm';
import type { FastifyInstance } from 'fastify';
import { guard, type GuardDeps } from '../../auth/guard.js';
import { withContext } from '../../db/client.js';
import { adminChainVerification, appUser, auditEvent } from '../../db/schema.js';

export const ADMIN_ACTION_FAMILIES = [
  'admin',
  'settings',
  'connector',
  'secret',
  'ai',
  'config',
  'security',
  'user',
  'grant',
  'delegation',
  'role',
  'workflow',
  'key',
  'kms',
  'retention',
  'residency',
  'privacy',
  'encryption',
  'compliance',
  'bank_change',
  'tenant',
] as const;

/** The same rule as the generated column in migration 0026 (a test keeps the two in step). */
export function isAdminAction(action: string, actorRole: string | null): boolean {
  return (
    new RegExp(`^(${ADMIN_ACTION_FAMILIES.join('|')})\\.`).test(action) ||
    /^policy\.(create|disable|delete)$/.test(action) ||
    /^access\.(grant|revoke)$/.test(action) ||
    actorRole === 'ADMIN'
  );
}

export const CHAIN_READERS = ['PROBITY', 'EXEC', 'ADMIN'] as const;

export interface ChainReport {
  ok: boolean;
  checked: number;
  adminEvents: number;
  headSeq: number | null;
  headHash: string | null;
  adminHeadSeq: number | null;
  adminHeadHash: string | null;
  adminDigest: string;
  brokenAtSeq: number | null;
  reason: string | null;
  categoryMismatches: number;
}

/** Re-computes the whole tenant chain and summarises the administrative events in it. */
export async function chainReport(d: GuardDeps, tenantId: string): Promise<ChainReport> {
  const v = await d.audit.verifyChain(d.database, tenantId);
  let adminEvents = 0;
  let adminHeadSeq: number | null = null;
  let adminHeadHash: string | null = null;
  let headSeq: number | null = null;
  let headHash: string | null = null;
  let mismatches = 0;
  const digest = createHash('sha256');
  let cursor = 0;
  for (;;) {
    const batch = await d.database.db
      .select({
        seq: auditEvent.seq,
        hash: auditEvent.hash,
        action: auditEvent.action,
        actorRole: auditEvent.actorRole,
        category: auditEvent.category,
      })
      .from(auditEvent)
      .where(and(eq(auditEvent.tenantId, tenantId), gt(auditEvent.seq, cursor)))
      .orderBy(asc(auditEvent.seq))
      .limit(1000);
    if (batch.length === 0) break;
    for (const r of batch) {
      cursor = r.seq;
      headSeq = r.seq;
      headHash = r.hash;
      const isAdmin = r.category === 'ADMIN';
      if (isAdmin !== isAdminAction(r.action, r.actorRole)) mismatches++;
      if (isAdmin) {
        adminEvents++;
        adminHeadSeq = r.seq;
        adminHeadHash = r.hash;
        digest.update(r.hash).update('\n');
      }
    }
  }
  return {
    ok: v.ok,
    checked: v.checked,
    adminEvents,
    headSeq,
    headHash,
    adminHeadSeq,
    adminHeadHash,
    adminDigest: digest.digest('hex'),
    brokenAtSeq: v.brokenAtSeq ?? null,
    reason: v.reason ?? null,
    categoryMismatches: mismatches,
  };
}

/** The database-level guards on the audit table, read from the catalogue (not asserted). */
async function guards(d: GuardDeps): Promise<Array<{ name: string; kind: string }>> {
  const r = await d.database.pg.query<{ tgname: string; tgtype: number }>(
    `select tgname, tgtype from pg_trigger where tgrelid = 'audit_event'::regclass and not tgisinternal order by tgname`,
  );
  const describe: Record<string, string> = {
    audit_event_no_update: 'UPDATE and DELETE are refused for every connection, the owner included',
    audit_event_no_truncate: 'TRUNCATE is refused for every connection',
    audit_event_chain_guard: 'An insert must continue the tenant chain (prev_hash = latest hash)',
  };
  return r.rows.map((x) => ({ name: x.tgname, kind: describe[x.tgname] ?? 'trigger' }));
}

export function registerAdminChain(app: FastifyInstance, p: string, d: GuardDeps): Set<string> {
  const done = new Set<string>();
  const reg = (m: string, path: string) => done.add(`${m} ${path}`);

  reg('GET', '/audit/admin-chain');
  app.get(`${p}/audit/admin-chain`, { preHandler: guard(d, [...CHAIN_READERS]) }, async (req) => {
    const a = req.auth!;
    const report = await chainReport(d, a.user.tenantId);
    const triggers = await guards(d);
    return withContext(d.database, a.ctx, async (tx) => {
      const [last] = await tx
        .select()
        .from(adminChainVerification)
        .where(eq(adminChainVerification.tenantId, a.user.tenantId))
        .orderBy(desc(adminChainVerification.verifiedAt))
        .limit(1);
      const recent = await tx
        .select({
          seq: auditEvent.seq,
          at: auditEvent.at,
          action: auditEvent.action,
          actorRole: auditEvent.actorRole,
          actorName: appUser.name,
          hash: auditEvent.hash,
          prevHash: auditEvent.prevHash,
          result: auditEvent.result,
        })
        .from(auditEvent)
        .leftJoin(appUser, eq(appUser.id, auditEvent.actorId))
        .where(and(eq(auditEvent.tenantId, a.user.tenantId), eq(auditEvent.category, 'ADMIN')))
        .orderBy(desc(auditEvent.seq))
        .limit(25);
      const [{ n } = { n: 0 }] = await tx
        .select({ n: sql<number>`count(*)::int` })
        .from(adminChainVerification)
        .where(eq(adminChainVerification.tenantId, a.user.tenantId));
      return {
        status: report.ok ? 'INTACT' : 'BROKEN',
        ...report,
        verifiedAt: d.clock.now().toISOString(),
        guards: triggers,
        lastRecordedVerification: last
          ? {
              at: last.verifiedAt.toISOString(),
              by: last.verifiedByRole,
              ok: last.ok,
              checked: last.checked,
              headHash: last.headHash,
            }
          : null,
        recordedVerifications: n,
        recent: recent.map((r) => ({
          seq: r.seq,
          at: r.at.toISOString(),
          action: r.action,
          actor: r.actorName ?? (r.actorRole === 'SYSTEM' ? 'System' : null),
          actorRole: r.actorRole,
          result: r.result,
          hash: r.hash,
          prevHash: r.prevHash,
        })),
      };
    });
  });

  reg('POST', '/audit/admin-chain/verify');
  app.post(
    `${p}/audit/admin-chain/verify`,
    { preHandler: guard(d, [...CHAIN_READERS]) },
    async (req, reply) => {
      const a = req.auth!;
      // the chain is read before the recording transaction opens: one connection, so a read inside it would wait on itself
      const report = await chainReport(d, a.user.tenantId);
      const at = d.clock.now();
      await withContext(d.database, a.ctx, async (tx) => {
        await tx.insert(adminChainVerification).values({
          tenantId: a.user.tenantId,
          verifiedBy: a.user.id,
          verifiedByRole: a.user.role,
          verifiedAt: at,
          ok: report.ok,
          checked: report.checked,
          adminEvents: report.adminEvents,
          headSeq: report.headSeq,
          headHash: report.headHash,
          brokenAtSeq: report.brokenAtSeq,
          reason: report.reason,
        });
        await d.audit.record(tx, a.ctx, {
          action: 'audit.admin_chain_verify',
          entityType: 'audit',
          after: {
            ok: report.ok,
            checked: report.checked,
            adminEvents: report.adminEvents,
            headSeq: report.headSeq,
            brokenAtSeq: report.brokenAtSeq,
          },
          result: report.ok ? 'SUCCESS' : 'FAILED',
        });
      });
      return reply
        .status(200)
        .send({ status: report.ok ? 'INTACT' : 'BROKEN', verifiedAt: at.toISOString(), ...report });
    },
  );

  return done;
}
