/**
 * How fast later-stage artefacts follow the records they were written from (FR-0870, NFR-P02). The evaluation report and the
 * contract management plans are generated by rules (a stand-in for an AI model, which would cost something every time it
 * ran). When the records behind one change, the artefact is marked out of date, and the organisation's setting decides what
 * happens next:
 *   REALTIME: it is rewritten at once, in the same step as the change.
 *   BATCHED:  it is rewritten by the next scheduled run after the batch interval, so many changes cost one rewrite.
 *   MANUAL:   it is left, marked out of date, until someone presses refresh.
 * An approved report, and one whose evaluation has moved past locking, is never rewritten.
 */
import { and, eq } from 'drizzle-orm';
import type { FastifyInstance } from 'fastify';
import { z } from 'zod';
import type { Clock } from '@if/shared';
import { MockVendorRegistry, type VendorRegistry } from '../../adapters/vendor-registry.js';
import type { AuditService } from '../../audit/audit-service.js';
import { guard, type GuardDeps } from '../../auth/guard.js';
import { withContext, withSystem, type Database, type RequestContext, type Tx } from '../../db/client.js';
import { artefactState, contract, evalReport } from '../../db/schema.js';
import { AppError, parse } from '../../http/errors.js';
import { generatePlans } from '../contract/b5-service.js';
import { composeReport, storeReport } from '../evaluation/report-compose.js';
import { EvaluationService } from '../evaluation/service.js';
import { loadSettings } from '../settings/settings.js';

export type Kind = 'EVAL_REPORT' | 'CONTRACT_PLANS';
export const ARTEFACT_MODEL = 'rules-simulated-v1';
const SYSTEM = (tenantId: string): RequestContext => ({ tenantId, userId: null, role: 'SYSTEM' });

export interface ArtefactDeps {
  audit: AuditService;
  clock: Clock;
  registry?: VendorRegistry;
}

/** Rewrites the artefact from the records as they stand now. Returns false when it must not be rewritten. */
async function rewrite(
  tx: Tx,
  deps: ArtefactDeps,
  tenantId: string,
  kind: Kind,
  subjectId: string,
  now: Date,
): Promise<boolean> {
  if (kind === 'EVAL_REPORT') {
    const svc = new EvaluationService(deps.clock, deps.audit);
    const l = await svc.load(tx, tenantId, subjectId);
    if (!l) return false;
    const [rep] = await tx.select().from(evalReport).where(eq(evalReport.evaluationId, subjectId));
    // an approved report is a decision on record, and one past locking is with the approver
    if (rep?.status === 'APPROVED' || l.ev.status !== 'LOCKED') return false;
    await storeReport(tx, tenantId, subjectId, await composeReport(tx, svc, l, now), 'DRAFT', now);
    return true;
  }
  const [c] = await tx
    .select()
    .from(contract)
    .where(and(eq(contract.id, subjectId), eq(contract.tenantId, tenantId)));
  if (
    !c ||
    c.status !== 'EXECUTED' ||
    c.deletedAt ||
    c.parentId ||
    !['CONTRACT', 'MASTER'].includes(c.docType)
  )
    return false;
  await generatePlans(
    tx,
    { registry: deps.registry ?? new MockVendorRegistry(), audit: deps.audit, now },
    SYSTEM(tenantId),
    c,
    await loadSettings(tx, tenantId),
    { manual: false },
  );
  return true;
}

async function markRefreshed(tx: Tx, tenantId: string, kind: Kind, subjectId: string, now: Date) {
  const [cur] = await tx
    .select()
    .from(artefactState)
    .where(and(eq(artefactState.kind, kind), eq(artefactState.subjectId, subjectId)));
  if (cur)
    await tx
      .update(artefactState)
      .set({ stale: false, refreshedAt: now, refreshCount: cur.refreshCount + 1 })
      .where(eq(artefactState.id, cur.id));
  else
    await tx
      .insert(artefactState)
      .values({ tenantId, kind, subjectId, stale: false, changedAt: now, refreshedAt: now, refreshCount: 1 });
}

/** The records behind an artefact changed: note it, and do what the setting says. Returns what happened. */
export async function noteChange(
  tx: Tx,
  deps: ArtefactDeps,
  tenantId: string,
  kind: Kind,
  subjectId: string,
  reason: string,
  now: Date,
): Promise<'REFRESHED' | 'STALE' | 'SKIPPED'> {
  const [cur] = await tx
    .select()
    .from(artefactState)
    .where(and(eq(artefactState.kind, kind), eq(artefactState.subjectId, subjectId)));
  if (cur)
    await tx
      .update(artefactState)
      .set({ stale: true, reason, changedAt: now })
      .where(eq(artefactState.id, cur.id));
  else
    await tx.insert(artefactState).values({ tenantId, kind, subjectId, stale: true, reason, changedAt: now });
  const s = await loadSettings(tx, tenantId);
  if (s.artefacts.laterStage !== 'REALTIME') return 'STALE';
  if (!(await rewrite(tx, deps, tenantId, kind, subjectId, now))) return 'SKIPPED';
  await markRefreshed(tx, tenantId, kind, subjectId, now);
  await deps.audit.record(tx, SYSTEM(tenantId), {
    action: 'artefact.refresh',
    entityType: kind === 'EVAL_REPORT' ? 'evaluation' : 'contract',
    entityId: subjectId,
    after: { kind, mode: 'REALTIME', reason },
  });
  return 'REFRESHED';
}

/** Brings one artefact up to date now, whatever the setting. */
export async function refreshNow(
  tx: Tx,
  deps: ArtefactDeps,
  tenantId: string,
  kind: Kind,
  subjectId: string,
  now: Date,
  mode = 'MANUAL',
): Promise<boolean> {
  if (!(await rewrite(tx, deps, tenantId, kind, subjectId, now))) return false;
  await markRefreshed(tx, tenantId, kind, subjectId, now);
  await deps.audit.record(tx, SYSTEM(tenantId), {
    action: 'artefact.refresh',
    entityType: kind === 'EVAL_REPORT' ? 'evaluation' : 'contract',
    entityId: subjectId,
    after: { kind, mode },
  });
  return true;
}

/** The scheduled run: everything out of date for longer than the batch interval, in BATCHED mode. */
export async function runDue(
  database: Database,
  deps: ArtefactDeps,
  now: Date,
  only?: { kind: Kind; subjectId: string },
): Promise<number> {
  return withSystem(database, async (tx) => {
    const rows = await tx.select().from(artefactState).where(eq(artefactState.stale, true));
    let n = 0;
    for (const r of rows) {
      if (only && (r.kind !== only.kind || r.subjectId !== only.subjectId)) continue;
      const s = await loadSettings(tx, r.tenantId);
      if (s.artefacts.laterStage !== 'BATCHED') continue;
      if (r.changedAt.getTime() > now.getTime() - s.artefacts.batchMinutes * 60_000) continue;
      if (await refreshNow(tx, deps, r.tenantId, r.kind, r.subjectId, now, 'BATCHED')) n += 1;
      else await tx.update(artefactState).set({ stale: false }).where(eq(artefactState.id, r.id)); // nothing more to do for it
    }
    return n;
  });
}

const KINDS = z.enum(['EVAL_REPORT', 'CONTRACT_PLANS']);
const READ_ROLES: Record<Kind, string[]> = {
  EVAL_REPORT: ['PROCUREMENT', 'DELEGATE', 'EXEC', 'PROBITY', 'CHAIR', 'LEGAL'],
  CONTRACT_PLANS: ['CONTRACT_MGR', 'PROCUREMENT', 'LEGAL', 'EXEC'],
};
const WRITE_ROLES: Record<Kind, string[]> = {
  EVAL_REPORT: ['PROCUREMENT'],
  CONTRACT_PLANS: ['CONTRACT_MGR', 'PROCUREMENT', 'LEGAL'],
};

export function registerArtefacts(
  app: FastifyInstance,
  p: string,
  d: GuardDeps & { audit: AuditService },
): Set<string> {
  const done = new Set<string>();
  const reg = (m: string, path: string) => done.add(`${m} ${path}`);
  const deps: ArtefactDeps = { audit: d.audit, clock: d.clock };

  reg('GET', '/artefacts/{kind}/{id}/state');
  app.get(
    `${p}/artefacts/:kind/:id/state`,
    {
      preHandler: guard(d, ['PROCUREMENT', 'DELEGATE', 'EXEC', 'PROBITY', 'CHAIR', 'LEGAL', 'CONTRACT_MGR']),
    },
    async (req) => {
      const a = req.auth!;
      const { kind, id } = parse(z.object({ kind: KINDS, id: z.string().uuid() }), req.params);
      if (!a.user.roles.some((r) => READ_ROLES[kind].includes(r)))
        throw new AppError(403, 'FORBIDDEN', 'You cannot see the state of this artefact');
      // a batch that has come due is run when someone looks, so the screen is never behind the schedule
      await runDue(d.database, deps, d.clock.now(), { kind, subjectId: id });
      return withContext(d.database, a.ctx, async (tx) => {
        const s = await loadSettings(tx, a.user.tenantId);
        const [st] = await tx
          .select()
          .from(artefactState)
          .where(and(eq(artefactState.kind, kind), eq(artefactState.subjectId, id)));
        const mode = s.artefacts.laterStage;
        return {
          kind,
          subjectId: id,
          mode,
          batchMinutes: s.artefacts.batchMinutes,
          stale: st?.stale ?? false,
          reason: st?.stale ? st.reason : null,
          changedAt: st?.changedAt.toISOString() ?? null,
          refreshedAt: st?.refreshedAt?.toISOString() ?? null,
          refreshCount: st?.refreshCount ?? 0,
          nextRefreshAt:
            st?.stale && mode === 'BATCHED'
              ? new Date(st.changedAt.getTime() + s.artefacts.batchMinutes * 60_000).toISOString()
              : null,
          model: ARTEFACT_MODEL,
        };
      });
    },
  );

  reg('POST', '/artefacts/{kind}/{id}/refresh');
  app.post(
    `${p}/artefacts/:kind/:id/refresh`,
    { preHandler: guard(d, ['PROCUREMENT', 'CONTRACT_MGR', 'LEGAL']) },
    async (req) => {
      const a = req.auth!;
      const { kind, id } = parse(z.object({ kind: KINDS, id: z.string().uuid() }), req.params);
      if (!a.user.roles.some((r) => WRITE_ROLES[kind].includes(r)))
        throw new AppError(403, 'FORBIDDEN', 'You cannot refresh this artefact');
      return withSystem(d.database, async (tx) => {
        const ok = await refreshNow(tx, deps, a.user.tenantId, kind, id, d.clock.now(), 'MANUAL');
        if (!ok)
          throw new AppError(
            409,
            'INVALID_STATE',
            kind === 'EVAL_REPORT'
              ? 'This report is approved, or has moved on from the draft stage, so it is no longer rewritten'
              : 'This contract has no plans to refresh',
          );
        return { kind, subjectId: id, refreshedAt: d.clock.now().toISOString() };
      });
    },
  );
  return done;
}
